'use client';

import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {CalendarDays,Crown,Gamepad2,Lock,MessageSquare,Plus,Shield,Users,Volume2,Video,ChevronRight,Copy,Loader2,X,Sparkles} from 'lucide-react';
import {ProfileHoverTrigger,type HoverPlayerData} from '@/components/profile/HoverProfileCard';

type CommunityListItem={id:string;owner_id:string;name:string;description:string;logo_url:string|null;banner_url:string|null;privacy:string;tags:string[];role:string;memberCount:number};
type Member={user_id:string;role:string;joined_at:string;profile:{id:string;username:string;display_name:string;avatar:string|null;status:string;favorite_game?:string|null;avatar_frame?:string|null;profile_effect?:string|null;profile_badge?:string|null}|null};
type Environment={id:string;name:string;description:string;type:string;capacity:number;lobby_id:string|null;sort_order:number};
type Post={id:string;author_id:string;type:string;title:string;body:string;media_url:string|null;created_at:string;author:Member['profile']};
type CommunityEvent={id:string;title:string;description:string;type:string;starts_at:string;ends_at:string|null;environment_id:string|null;capacity:number|null;status:string};
type Detail={community:CommunityListItem;members:Member[];environments:Environment[];posts:Post[];events:CommunityEvent[];stats:{members:number;online:number;activeRooms:number}};

function initials(name:string){return name.trim().split(/\s+/).map(p=>p[0]).join('').slice(0,2).toUpperCase()||'GL'}
function envIcon(type:string){if(type==='voice')return <Volume2 size={18}/>;if(type==='game')return <Gamepad2 size={18}/>;if(type==='clips')return <Video size={18}/>;if(type==='strategy')return <Shield size={18}/>;return <Sparkles size={18}/>}
function relativeDate(value:string){const diff=Math.max(0,Date.now()-new Date(value).getTime()),min=Math.floor(diff/60000);if(min<1)return'agora';if(min<60)return`há ${min} min`;const h=Math.floor(min/60);if(h<24)return`há ${h}h`;return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(value));}
function playerFrom(member:Member):HoverPlayerData|null{const p=member.profile;if(!p)return null;return{id:p.id,name:p.display_name||p.username,username:p.username,avatar:p.avatar,status:p.status,statusLabel:p.status==='online'?'Online':'Offline',level:0,rankName:'Membro',points:0,winRate:null,matches:0,streak:null,favoriteGame:p.favorite_game||'',memberSince:member.joined_at,frame:p.avatar_frame||'none',effect:p.profile_effect||'none',badge:p.profile_badge||'none'};}

export default function CommunityHub(){
 const [items,setItems]=useState<CommunityListItem[]>([]);const [selectedId,setSelectedId]=useState<string|null>(null);const [detail,setDetail]=useState<Detail|null>(null);const [loading,setLoading]=useState(true);const [detailLoading,setDetailLoading]=useState(false);const [createOpen,setCreateOpen]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [name,setName]=useState('');const [description,setDescription]=useState('');const [tags,setTags]=useState('');const [logoFile,setLogoFile]=useState<File|null>(null);const [bannerFile,setBannerFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);
 const loadList=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/communities',{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error||'Falha ao carregar Communities.');setItems(b.communities||[]);setSelectedId(current=>current||(b.communities?.[0]?.id??null));setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar Communities.')}finally{setLoading(false)}},[]);
 const loadDetail=useCallback(async(id:string)=>{setDetailLoading(true);try{const r=await fetch(`/api/communities/${id}`,{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error||'Falha ao abrir Community.');setDetail(b);setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao abrir Community.')}finally{setDetailLoading(false)}},[]);
 useEffect(()=>{void loadList()},[loadList]);useEffect(()=>{if(selectedId)void loadDetail(selectedId);else setDetail(null)},[selectedId,loadDetail]);
 useEffect(()=>{if(!selectedId)return;const timer=window.setInterval(()=>void loadDetail(selectedId),15000);return()=>window.clearInterval(timer)},[selectedId,loadDetail]);
 const online=useMemo(()=>detail?.members.filter(m=>m.profile?.status==='online')??[],[detail]);
 async function createCommunity(){setBusy(true);try{const r=await fetch('/api/communities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description,tags:tags.split(',').map(v=>v.trim()).filter(Boolean)})}),b=await r.json();if(!r.ok)throw new Error(b.error||'Falha ao criar Community.');for(const [kind,file] of [['logo',logoFile],['banner',bannerFile]] as const){if(!file)continue;const form=new FormData();form.set('kind',kind);form.set('file',file);const upload=await fetch(`/api/communities/${b.community.id}/upload`,{method:'POST',body:form});if(!upload.ok){const uploadBody=await upload.json().catch(()=>({}));throw new Error(uploadBody.error||`Falha no upload de ${kind}.`);}}setCreateOpen(false);setName('');setDescription('');setTags('');setLogoFile(null);setBannerFile(null);await loadList();setSelectedId(b.community.id);}catch(e){setError(e instanceof Error?e.message:'Falha ao criar Community.')}finally{setBusy(false)}}
 async function copyInvite(){if(!detail)return;setBusy(true);try{const r=await fetch(`/api/communities/${detail.community.id}/invite`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiresInHours:168,maxUses:100})}),b=await r.json();if(!r.ok)throw new Error(b.error||'Falha ao criar convite.');const url=`${location.origin}${b.url}`;await navigator.clipboard.writeText(url);setNotice('Link privado copiado.');}catch(e){setError(e instanceof Error?e.message:'Falha ao criar convite.')}finally{setBusy(false)}}
 async function openEnvironment(environment:Environment){if(!detail)return;setBusy(true);try{if(environment.lobby_id){location.href=`/lobby/${environment.lobby_id}`;return;}const r=await fetch(`/api/communities/${detail.community.id}/environments/${environment.id}/room`,{method:'POST'}),b=await r.json();if(!r.ok)throw new Error(b.error||'Falha ao abrir Ambiente.');location.href=`/lobby/${b.lobbyId}`;}catch(e){setError(e instanceof Error?e.message:'Falha ao abrir Ambiente.')}finally{setBusy(false)}}
 async function joinEvent(eventId:string){if(!detail)return;setBusy(true);try{const r=await fetch(`/api/communities/${detail.community.id}/events/${eventId}/join`,{method:'POST'}),b=await r.json();if(!r.ok)throw new Error(b.error||'Falha ao participar.');setNotice('Participação confirmada.');}catch(e){setError(e instanceof Error?e.message:'Falha ao participar.')}finally{setBusy(false)}}
 return <div className="community-shell">
  <header className="community-topbar"><Link href="/" className="community-back">← Dashboard</Link><div className="community-brand">GRIND<span>LOBBY</span></div><div className="community-top-actions"><span>COMMUNITY</span><Lock size={14}/></div></header>
  <div className="community-layout">
   <aside className="community-list"><div className="community-list-head"><div><span className="community-kicker">SEUS GRUPOS</span><h2>Minhas Communities</h2></div><button onClick={()=>setCreateOpen(true)} className="community-icon-btn" aria-label="Criar Community"><Plus size={17}/></button></div>
    {loading?<div className="community-loading"><Loader2 className="animate-spin"/>Carregando</div>:items.length?items.map(item=><button key={item.id} onClick={()=>setSelectedId(item.id)} className={`community-list-item ${selectedId===item.id?'active':''}`}><span className="community-logo">{item.logo_url?<img src={item.logo_url} alt=""/>:initials(item.name)}</span><span className="min-w-0"><b>{item.name}</b><small><Lock size={10}/> Privada · {item.memberCount} membros</small></span>{item.role==='owner'?<Crown size={14} className="community-owner"/>:null}</button>):<div className="community-empty"><Lock size={18}/><p>Você ainda não participa de nenhuma Community.</p></div>}
    <button className="community-join-disabled" title="Use um link privado de convite"><Plus size={14}/>Entrar com convite</button>
   </aside>
   <main className="community-main">
    {error?<div className="community-alert">{error}</div>:null}{notice?<div className="community-notice">{notice}</div>:null}
    {!selectedId&&!loading?<section className="community-zero"><Shield size={38}/><h1>Seu hub privado de grupo</h1><p>Crie uma Community ou entre através de um convite privado.</p><button onClick={()=>setCreateOpen(true)}>Criar Community</button></section>:null}
    {detailLoading&&!detail?<div className="community-loading large"><Loader2 className="animate-spin"/>Abrindo Community</div>:null}
    {detail?<>
      <section className="community-hero" style={detail.community.banner_url?{backgroundImage:`linear-gradient(90deg,rgba(7,7,17,.97),rgba(7,7,17,.48)),url(${detail.community.banner_url})`}:undefined}><div className="community-hero-glow"/><div className="community-hero-row"><span className="community-hero-logo">{detail.community.logo_url?<img src={detail.community.logo_url} alt=""/>:initials(detail.community.name)}</span><div className="min-w-0 flex-1"><div className="community-hero-title"><h1>{detail.community.name}</h1>{detail.community.role==='owner'?<Crown size={18}/>:null}</div><p>{detail.community.description||'Community privada do GrindLobby'}</p><div className="community-tags"><span><Lock size={11}/> Privada</span>{detail.community.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div><div className="community-hero-stats"><div><b>{detail.stats.members}</b><small>Membros</small></div><div><b>{detail.stats.activeRooms}</b><small>Salas ativas</small></div><div><b>{detail.stats.online}</b><small>Online agora</small></div></div><button disabled={busy} onClick={copyInvite} className="community-primary"><Copy size={15}/>Convidar</button></div></section>
      <div className="community-content-grid"><div className="community-center">
       <section><div className="community-section-head"><div><span className="community-kicker">AMBIENTES</span><h2>Entre onde a squad está</h2></div></div><div className="community-env-grid">{detail.environments.map(env=><article key={env.id} className="community-env-card"><div className="community-env-icon">{envIcon(env.type)}</div><div><h3>{env.name}</h3><p>{env.description}</p></div><div className="community-env-foot"><span>{env.lobby_id?'Sala ativa':'Disponível'}</span><button disabled={busy} onClick={()=>openEnvironment(env)}>{env.lobby_id?'Entrar':'Abrir sala'} <ChevronRight size={14}/></button></div></article>)}</div></section>
       <section className="community-panel"><div className="community-section-head"><div><span className="community-kicker">PAINEL DA COMMUNITY</span><h2>O que está rolando em {detail.community.name}</h2></div></div><div className="community-feed">{detail.posts.length?detail.posts.map(post=><article key={post.id} className="community-post"><span className={`community-post-type type-${post.type}`}>{post.type}</span><div><h3>{post.title}</h3>{post.body?<p>{post.body}</p>:null}<small>{post.author?.display_name||post.author?.username||'Sistema'} · {relativeDate(post.created_at)}</small></div></article>):<div className="community-empty-inline">Nenhuma atividade ainda. A Community está pronta para começar.</div>}</div></section>
       <section className="community-panel"><div className="community-section-head"><div><span className="community-kicker">PRÓXIMOS EVENTOS</span><h2>Agenda da Community</h2></div></div><div className="community-event-grid">{detail.events.length?detail.events.map(event=><article key={event.id} className="community-event"><div className="community-date"><b>{new Date(event.starts_at).getDate().toString().padStart(2,'0')}</b><small>{new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(new Date(event.starts_at)).toUpperCase()}</small></div><div><span>{event.type}</span><h3>{event.title}</h3><p><CalendarDays size={13}/>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(event.starts_at))}</p><button disabled={busy} onClick={()=>joinEvent(event.id)}>Participar</button></div></article>):<div className="community-empty-inline">Nenhum evento agendado.</div>}</div></section>
      </div><aside className="community-context"><section className="community-side-card"><span className="community-kicker">MEMBROS ONLINE</span><div className="community-online-list">{online.slice(0,8).map(member=>{const player=playerFrom(member);const row=<div className="community-online-row"><span className="community-mini-avatar">{member.profile?.avatar?<img src={member.profile.avatar} alt=""/>:initials(member.profile?.display_name||member.profile?.username||'P')}</span><span><b>{member.profile?.display_name||member.profile?.username}</b><small><i/> {member.profile?.favorite_game||'Online'}</small></span>{member.role==='owner'?<Crown size={13}/>:null}</div>;return player?<ProfileHoverTrigger key={member.user_id} player={player}>{row}</ProfileHoverTrigger>:row})}{!online.length?<p className="community-muted">Ninguém online agora.</p>:null}</div></section><section className="community-side-card private"><Lock size={21}/><span className="community-kicker">ACESSO PRIVADO</span><h3>Esta Community é privada.</h3><p>Apenas convidados ou quem possui um link válido podem acessar.</p>{['owner','admin'].includes(detail.community.role)?<button onClick={copyInvite}>Gerenciar convites</button>:null}</section><section className="community-side-card"><span className="community-kicker">ESTATÍSTICAS</span><div className="community-side-stats"><div><b>{detail.stats.members}</b><small>Membros</small></div><div><b>{detail.stats.activeRooms}</b><small>Salas ativas</small></div><div><b>{detail.stats.online}</b><small>Online</small></div></div></section></aside></div>
    </>:null}
   </main>
  </div>
  {createOpen?<div className="community-modal-backdrop" onMouseDown={()=>setCreateOpen(false)}><section className="community-modal" onMouseDown={e=>e.stopPropagation()}><button className="community-modal-close" onClick={()=>setCreateOpen(false)}><X size={17}/></button><span className="community-kicker">NOVA COMMUNITY</span><h2>Criar Community</h2><p>Um hub privado persistente para sua equipe e seus amigos.</p><label>Nome<input value={name} maxLength={60} onChange={e=>setName(e.target.value)} placeholder="Ex: GRIND FAM"/></label><label>Descrição<textarea value={description} maxLength={500} onChange={e=>setDescription(e.target.value)} placeholder="Qual é a proposta da Community?"/></label><label>Jogos / categorias<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="EA FC 27, Valorant, Competitivo"/></label><div className="community-upload-grid"><label>Logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setLogoFile(e.target.files?.[0]??null)}/><span>{logoFile?.name||'Quadrada · até 5MB'}</span></label><label>Banner<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setBannerFile(e.target.files?.[0]??null)}/><span>{bannerFile?.name||'Horizontal · até 10MB'}</span></label></div><div className="community-private-note"><Lock size={15}/>Privada por padrão. Não será listada publicamente.</div><button disabled={busy||name.trim().length<2} onClick={createCommunity} className="community-primary wide">{busy?<Loader2 size={16} className="animate-spin"/>:<Plus size={16}/>}Criar Community</button></section></div>:null}
 </div>;
}
