import { createFileRoute, Link } from "@tanstack/react-router";
import { LayoutGrid, Mic, Monitor, Settings, Star, Store, Trophy, Users, Volume2 } from "lucide-react";
import { useEffect, useState } from "react";

export const Route = createFileRoute("/configuracoes")({ component: SettingsPage });
const nav = [["Dashboard","/",LayoutGrid],["Lobbies","/lobbies",Users],["Rank","/rank",Trophy],["Loja","/loja",Store],["Pro","/pro",Star],["Configurações","/configuracoes",Settings]] as const;

type DeviceOption = { deviceId: string; label: string; kind: MediaDeviceKind };

function SettingsPage(){
  const [devices,setDevices]=useState<DeviceOption[]>([]); const [status,setStatus]=useState("");
  const [mic,setMic]=useState(""); const [out,setOut]=useState(""); const [quality,setQuality]=useState(localStorage.getItem("grind:streamQuality")||"720p30");
  const loadDevices=async()=>{try{await navigator.mediaDevices.getUserMedia({audio:true}); const list=await navigator.mediaDevices.enumerateDevices(); setDevices(list.filter(d=>d.kind==="audioinput"||d.kind==="audiooutput").map(d=>({deviceId:d.deviceId,label:d.label||"Dispositivo sem nome",kind:d.kind}))); setStatus("Dispositivos atualizados.");}catch{setStatus("Permissão de microfone não concedida ou mídia indisponível neste navegador.");}};
  useEffect(()=>{setMic(localStorage.getItem("grind:mic")||"");setOut(localStorage.getItem("grind:out")||"");},[]);
  const save=()=>{localStorage.setItem("grind:mic",mic);localStorage.setItem("grind:out",out);localStorage.setItem("grind:streamQuality",quality);setStatus("Preferências salvas neste navegador.");};
  const inputs=devices.filter(d=>d.kind==="audioinput"), outputs=devices.filter(d=>d.kind==="audiooutput");
  return <div className="min-h-screen bg-background text-foreground"><div className="mx-auto flex max-w-7xl gap-6 p-4 md:p-6"><aside className="hidden w-56 shrink-0 lg:block"><div className="panel sticky top-6 p-4"><img src="/favicon.png" alt="GrindLobby" className="mx-auto h-14 w-14 object-contain"/><nav className="mt-5 space-y-1">{nav.map(([label,to,Icon])=><Link key={label} to={to} className={`flex items-center gap-3 rounded-lg px-3 py-2 text-sm ${to==="/configuracoes"?"bg-primary/15 text-primary-glow":"text-muted-foreground hover:bg-secondary hover:text-foreground"}`}><Icon className="h-4 w-4"/>{label}</Link>)}</nav></div></aside><main className="min-w-0 flex-1 space-y-5"><header><p className="label-caps">Sistema</p><h1 className="font-display text-3xl font-bold">Configurações</h1><p className="mt-1 text-sm text-muted-foreground">Preferências reais do navegador para dispositivos e qualidade.</p></header><section className="panel p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Áudio</h2><button onClick={loadDevices} className="btn-ghost rounded-lg px-3 py-2 text-sm">Detectar dispositivos</button></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><label className="text-sm"><span className="mb-2 flex items-center gap-2 text-muted-foreground"><Mic className="h-4 w-4"/>Microfone</span><select value={mic} onChange={e=>setMic(e.target.value)} className="w-full rounded-lg border border-border bg-panel px-3 py-2"><option value="">Padrão do sistema</option>{inputs.map(d=><option key={d.deviceId} value={d.deviceId}>{d.label}</option>)}</select></label><label className="text-sm"><span className="mb-2 flex items-center gap-2 text-muted-foreground"><Volume2 className="h-4 w-4"/>Saída</span><select value={out} onChange={e=>setOut(e.target.value)} className="w-full rounded-lg border border-border bg-panel px-3 py-2"><option value="">Padrão do sistema</option>{outputs.map(d=><option key={d.deviceId} value={d.deviceId}>{d.label}</option>)}</select></label></div></section><section className="panel p-5"><h2 className="font-semibold">Transmissão</h2><label className="mt-4 block text-sm"><span className="mb-2 flex items-center gap-2 text-muted-foreground"><Monitor className="h-4 w-4"/>Perfil padrão</span><select value={quality} onChange={e=>setQuality(e.target.value)} className="w-full max-w-md rounded-lg border border-border bg-panel px-3 py-2"><option>360p30</option><option>480p30</option><option>720p30</option><option>1080p60</option></select></label><p className="mt-2 text-xs text-muted-foreground">A preferência é persistida; bitrate/resolução real só entram em vigor quando o pipeline WebRTC/SFU consumir este valor.</p></section><button onClick={save} className="btn-primary rounded-lg px-5 py-2.5 font-semibold">Salvar configurações</button>{status&&<p className="text-sm text-muted-foreground">{status}</p>}</main></div></div>;
}
