import { createFileRoute,Link } from "@tanstack/react-router";
import { Crown,Headphones,LayoutGrid,LogOut,Mic,MicOff,Plus,Settings,SignalHigh,Star,Store,Trophy,Users,UserPlus,Wifi } from "lucide-react";
import { useEffect,useMemo,useState,useSyncExternalStore } from "react";
import { supabase } from "@/lib/supabase";
import { callSession } from "@/lib/call-session";
import { PlayerProvider,usePlayer,findItem } from "@/lib/player-store";
import { getTier } from "@/lib/levels";
import { ProfileAvatar } from "@/components/ProfileAvatar";
import { ProfileSettings } from "@/components/ProfileSettings";
import { TopElos } from "@/components/TopElos";
import { LevelHero } from "@/components/LevelHero";
import { EventTicker } from "@/components/EventTicker";

export const Route=createFileRoute("/")({component:Dashboard});
const nav=[["Dashboard","/",LayoutGrid],["Lobbies","/lobbies",Users],["Rank","/rank",Trophy],["Loja","/loja",Store],["Pro","/pro",Star],["Configurações","/configuracoes",Settings]] as const;
type Presence={userId:string;name:string;avatar?:string|null;speaking?:boolean;sharing?:boolean};
type LobbyRow={route_code:string;name:string;visibility:string;max_members:number;status:string;game_label:string|null;owner_id:string};
type OnlineProfile={id:string;display_name:string|null;username:string|null;avatar:string|null;last_seen_at:string|null;status:string|null};
function fmtAgo(iso:string|null){if(!iso)return"agora";const m=Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/60000));if(m<1)return"agora";if(m<60)return`há ${m} min`;return`há ${Math.floor(m/60)} h`}
function fmtDuration(start:number|null){if(!start)return"—";const s=Math.floor((Date.now()-start)/1000);return`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}

function Dashboard(){return <PlayerProvider><DashboardInner/></PlayerProvider>}
function DashboardInner(){const{player}=usePlayer();const[profileOpen,setProfileOpen]=useState(false);const[people,setPeople]=useState<Presence[]>([]);const[lobby,setLobby]=useState<LobbyRow|null>(null);const[online,setOnline]=useState<OnlineProfile[]>([]);const[clock,setClock]=useState(0);const call=useSyncExternalStore(callSession.subscribe,()=>({...callSession.snapshot}),()=>({...callSession.snapshot}));const tier=getTier(player.level);const title=findItem(player.equipped.title)?.label;
 useEffect(()=>{const t=setInterval(()=>setClock(v=>v+1),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{void(async()=>{const since=new Date(Date.now()-15*60_000).toISOString();const{data}=await supabase.from("profiles").select("id,display_name,username,avatar,last_seen_at,status").gte("last_seen_at",since).order("last_seen_at",{ascending:false}).limit(8);setOnline((data||[]) as OnlineProfile[])})();const ch=supabase.channel("dashboard-online-profiles").on("postgres_changes",{event:"UPDATE",schema:"public",table:"profiles"},()=>{void(async()=>{const since=new Date(Date.now()-15*60_000).toISOString();const{data}=await supabase.from("profiles").select("id,display_name,username,avatar,last_seen_at,status").gte("last_seen_at",since).order("last_seen_at",{ascending:false}).limit(8);setOnline((data||[]) as OnlineProfile[])})()}).subscribe();return()=>{void supabase.removeChannel(ch)}},[]);
 useEffect(()=>{setPeople([]);setLobby(null);if(!call.lobbyId)return;let ch:any=null;void(async()=>{const{data}=await supabase.from("lobbies").select("route_code,name,visibility,max_members,status,game_label,owner_id").eq("route_code",call.lobbyId).maybeSingle();if(data)setLobby(data as LobbyRow);ch=supabase.channel(`dashboard-room:${call.lobbyId}`);const source=supabase.channel(`grind:room:${call.lobbyId}`);ch=source;source.on("presence",{event:"sync"},()=>setPeople(Object.values(source.presenceState<Presence>()).flat().map(v=>v as unknown as Presence))).subscribe()})();return()=>{if(ch)void supabase.removeChannel(ch)}},[call.lobbyId]);
 const recent=useMemo(()=>{const live=people.map(p=>({id:`room-${p.userId}`,name:p.name,text:p.sharing?"está compartilhando a tela":"está online na sua call",time:"agora",avatar:p.avatar||null}));const ids=new Set(people.map(p=>p.userId));const others=online.filter(p=>!ids.has(p.id)).slice(0,Math.max(0,5-live.length)).map(p=>({id:p.id,name:p.display_name||p.username||"Jogador",text:p.status==="online"?"está online":"esteve online",time:fmtAgo(p.last_seen_at),avatar:p.avatar}));return[...live,...others].slice(0,5)},[people,online]);
 const rtt=call.metrics.rttMs;const bitrate=call.metrics.bitrateKbps;const quality=rtt==null?"Sem amostra":rtt<60?"Excelente":rtt<120?"Boa":rtt<180?"Instável":"Ruim";const qClass=rtt==null?"text-muted-foreground":rtt<120?"text-success":rtt<180?"text-warning":"text-destructive";
 return <div className="min-h-screen bg-background text-foreground"><div className="flex min-h-screen"><aside className="hidden w-64 shrink-0 flex-col border-r border-border bg-card/60 px-5 py-6 lg:flex"><div className="flex flex-col items-center gap-3 pb-8"><img src="/grindlobby-logo.png" className="h-16 w-16 object-contain" alt="GL"/><p className="font-display text-2xl font-bold italic">GRIND<span className="text-primary-glow">LOBBY</span></p></div><nav className="space-y-1">{nav.map(([label,to,Icon])=><Link key={label} to={to} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${to==="/"?"border border-primary/40 bg-primary/15":"text-muted-foreground hover:bg-secondary"}`}><Icon className="h-4 w-4"/>{label}</Link>)}</nav><div className="mt-6 space-y-2"><Link to="/lobbies" className="btn-primary flex items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-sm"><Plus className="h-4 w-4"/>Criar lobby</Link>{call.lobbyId&&<Link to="/sala/$lobbyId" params={{lobbyId:call.lobbyId}} className="btn-ghost flex items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-sm"><Headphones className="h-4 w-4"/>Voltar para call</Link>}</div><div className="mt-8"><p className="label-caps">Atividade recente</p><div className="mt-3 space-y-3">{recent.length?recent.map(a=><div key={a.id} className="flex items-start gap-2.5">{a.avatar?<img src={a.avatar} className="h-7 w-7 rounded-full object-cover" alt=""/>:<span className="grid h-7 w-7 place-items-center rounded-full bg-primary/30 text-xs font-bold">{a.name[0]?.toUpperCase()}</span>}<div className="min-w-0 text-xs"><p className="truncate"><b>{a.name}</b> <span className="text-muted-foreground">{a.text}</span></p><p className="text-muted-foreground">{a.time}</p></div></div>):<p className="text-xs text-muted-foreground">Nenhum jogador online detectado agora.</p>}</div></div><button onClick={()=>setProfileOpen(true)} className="mt-auto flex items-center gap-3 rounded-xl border border-border bg-panel p-3 text-left"><ProfileAvatar name={player.nickname} size={40} borderId={player.equipped.border} avatarUrl={player.avatarUrl}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{player.nickname}{title&&<span className="ml-1 text-[9px] text-primary-glow">{title}</span>}</p><p className="text-[11px] text-muted-foreground">Level {player.level} • {tier.name}</p></div><Settings className="h-4 w-4 text-muted-foreground"/></button></aside>
 <main className="min-w-0 flex-1 space-y-4 p-4 md:p-6"><header className="panel flex flex-wrap items-center justify-between gap-3 px-5 py-3"><div className="flex items-center gap-2 text-sm"><Crown className="h-4 w-4 text-primary-glow"/><span className="font-semibold">{player.nickname}</span><span className="text-muted-foreground">•</span><span className="text-primary-glow">{player.email}</span></div><SignalHigh className={`h-5 w-5 ${call.lobbyId?"text-success":"text-muted-foreground"}`}/></header><EventTicker/><TopElos/><LevelHero onOpenProfile={()=>setProfileOpen(true)}/>
 <div className="grid gap-4 xl:grid-cols-[1.65fr_1fr]"><section className="panel p-5"><div className="flex items-center justify-between"><p className="label-caps">Lobby atual</p>{call.lobbyId&&<span className="text-xs text-success">● call ativa</span>}</div>{!call.lobbyId?<div className="mt-6 rounded-xl border border-dashed border-border p-8 text-center"><p className="text-sm font-semibold">Você não está em nenhum lobby.</p><Link to="/lobbies" className="btn-primary mt-4 inline-flex rounded-lg px-4 py-2 text-sm">Abrir lobbies</Link></div>:<><div className="mt-3 flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display text-2xl font-bold">{lobby?.name||call.lobbyId}</h2><div className="mt-2 flex gap-2 text-xs"><span className="rounded-md border border-border px-2 py-1">{lobby?.visibility||"pública"}</span><span className="rounded-md border border-border px-2 py-1">{lobby?.game_label||"EA FC 27"}</span><span className="rounded-md border border-border px-2 py-1">{call.lobbyId}</span></div></div><div className="flex items-center gap-3"><span className="flex items-center gap-2 text-sm"><Users className="h-4 w-4"/>{people.length}/{lobby?.max_members||10}</span><Link to="/sala/$lobbyId" params={{lobbyId:call.lobbyId}} className="btn-primary rounded-lg px-3 py-2 text-sm">Abrir sala</Link></div></div><div className="mt-5 rounded-xl border border-border bg-panel/50 p-3"><p className="label-caps">Membros online ({people.length})</p><div className="mt-2 divide-y divide-border">{people.length?people.map(p=><div key={p.userId} className="flex items-center gap-3 py-2.5"><ProfileAvatar name={p.name} size={34} avatarUrl={p.avatar||""}/><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{p.name}</p><p className="text-xs text-muted-foreground">{p.sharing?"Compartilhando tela":p.speaking?"Falando":"Na call"}</p></div>{p.speaking?<span className="text-xs text-success">falando</span>:<Mic className="h-4 w-4 text-muted-foreground"/>}</div>):<p className="py-4 text-sm text-muted-foreground">Aguardando sincronização de presença...</p>}</div></div></>}</section>
 <div className="space-y-4"><section className="panel p-5"><div className="flex items-center justify-between"><p className="label-caps flex items-center gap-2"><Wifi className="h-4 w-4"/>Conexão da call</p>{call.lobbyId&&<span className="text-xs text-success">Em call • {fmtDuration(call.startedAt)}{clock<0?"":""}</span>}</div>{!call.lobbyId?<p className="mt-5 text-sm text-muted-foreground">Entre em uma call para medir a conexão.</p>:<><div className={`mt-5 font-display text-4xl font-bold ${qClass}`}>{rtt==null?"—":Math.round(rtt)}<span className="ml-1 text-sm">ms</span></div><p className={`mt-1 text-sm ${qClass}`}>{quality}</p><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-lg border border-border p-3 text-center"><p className="text-[10px] text-muted-foreground">BITRATE REAL</p><p className="mt-1 text-sm font-semibold">{bitrate==null?"—":`${Math.round(bitrate)} kbps`}</p></div><div className="rounded-lg border border-border p-3 text-center"><p className="text-[10px] text-muted-foreground">PERDA DE PACOTES</p><p className="mt-1 text-sm font-semibold">{call.metrics.packetsLost==null?"—":call.metrics.packetsLost}</p></div></div>{rtt==null&&<p className="mt-3 text-xs text-muted-foreground">Aguardando uma amostra real do WebRTC; nenhum valor é simulado.</p>}<button onClick={()=>callSession.leave()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg border border-destructive/40 bg-destructive/10 py-2.5 text-sm text-destructive"><LogOut className="h-4 w-4"/>Sair da call</button></>}</section><section className="panel p-5"><p className="label-caps">Jogadores online</p><div className="mt-3 space-y-2">{online.length?online.slice(0,5).map(p=><div key={p.id} className="flex items-center gap-3"><ProfileAvatar name={p.display_name||p.username||"J"} size={30} avatarUrl={p.avatar||""}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{p.display_name||p.username||"Jogador"}</p><p className="text-xs text-muted-foreground">{fmtAgo(p.last_seen_at)}</p></div></div>):<p className="text-sm text-muted-foreground">Nenhum jogador online agora.</p>}</div></section></div></div>
 </main></div>{profileOpen&&<ProfileSettings onClose={()=>setProfileOpen(false)}/>}</div>}
