import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Copy, DoorOpen, LayoutGrid, Plus, Settings, Star, Store, Trophy, Users } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/lobbies")({component:LobbiesPage});
type Presence={userId:string;lobbyId:string;name:string;game:string;maxPlayers:number;sharing?:boolean;updatedAt:string};
type PublicLobby={id:string;name:string;game:string;maxPlayers:number;members:number;sharing:number};
type SavedLobby={id:string;name:string;game:string;maxPlayers:number;owner:boolean};
const nav=[["Dashboard","/",LayoutGrid],["Lobbies","/lobbies",Users],["Rank","/rank",Trophy],["Loja","/loja",Store],["Pro","/pro",Star],["Configurações","/configuracoes",Settings]] as const;
function Logo(){return <img src="/grindlobby-logo.png" alt="GrindLobby" className="mx-auto h-14 w-14 object-contain"/>}

function LobbiesPage(){const navigate=useNavigate();const[name,setName]=useState("Meu lobby");const[game,setGame]=useState("EA FC 27");const[joinCode,setJoinCode]=useState("");const[message,setMessage]=useState("");const[presence,setPresence]=useState<Presence[]>([]);const[saved,setSaved]=useState<SavedLobby[]>([]);const channelRef=useRef<ReturnType<typeof supabase.channel>|null>(null);
 async function loadMine(){const{data:{user}}=await supabase.auth.getUser();if(!user){setSaved([]);return}const{data}=await supabase.from("lobbies").select("route_code,name,game_label,max_members,owner_id,status").neq("status","closed").or(`owner_id.eq.${user.id}`);setSaved((data||[]).filter((r:any)=>r.route_code).map((r:any)=>({id:r.route_code,name:r.name||`Lobby ${r.route_code}`,game:r.game_label||"Outro",maxPlayers:r.max_members||10,owner:r.owner_id===user.id})))}
 useEffect(()=>{const q=new URLSearchParams(location.search).get("join");if(q)setJoinCode(q.toUpperCase());void loadMine();const ch=supabase.channel("grind:lobby-directory");channelRef.current=ch;ch.on("presence",{event:"sync"},()=>setPresence(Object.values(ch.presenceState<Presence>()).flat().map(v=>v as unknown as Presence))).subscribe();return()=>{void supabase.removeChannel(ch)}},[]);
 const publicLobbies=useMemo(()=>{const m=new Map<string,PublicLobby>();for(const p of presence){if(!p.lobbyId)continue;const x=m.get(p.lobbyId);if(x){x.members++;if(p.sharing)x.sharing++}else m.set(p.lobbyId,{id:p.lobbyId,name:p.name||`Lobby ${p.lobbyId}`,game:p.game||"Outro",maxPlayers:p.maxPlayers||10,members:1,sharing:p.sharing?1:0})}return[...m.values()].sort((a,b)=>b.members-a.members)},[presence]);
 const enter=(id:string)=>{localStorage.setItem("grind:activeLobby",id);navigate({to:"/sala/$lobbyId",params:{lobbyId:id}})};
 async function createLobby(){setMessage("");const{data:{user}}=await supabase.auth.getUser();if(!user){setMessage("Faça login para criar uma sala.");return}const id=`GL-${Math.random().toString(36).slice(2,8).toUpperCase()}`;const{error}=await supabase.from("lobbies").insert({owner_id:user.id,name:name.trim()||"Meu lobby",visibility:"public",max_members:10,status:"open",route_code:id,game_label:game});if(error){setMessage(`Não foi possível criar a sala: ${error.message}`);return}await loadMine();enter(id)}
 async function join(){const code=joinCode.trim().toUpperCase();if(!/^GL-[A-Z0-9]{4,12}$/.test(code)){setMessage("Código inválido. Use GL-XXXXXX.");return}const{data}=await supabase.from("lobbies").select("route_code,status").eq("route_code",code).maybeSingle();if(!data||data.status==="closed"){setMessage("Essa sala não existe mais ou já foi encerrada.");return}enter(code)}
 async function copy(id:string){await navigator.clipboard.writeText(`${location.origin}/lobbies?join=${encodeURIComponent(id)}`);setMessage("Convite copiado.")}
 return <div className="min-h-screen bg-background text-foreground"><div className="mx-auto flex max-w-7xl gap-6 p-4 md:p-6"><aside className="hidden w-56 shrink-0 lg:block"><div className="panel sticky top-6 p-4"><Logo/><nav className="mt-5 space-y-1">{nav.map(([label,to,Icon])=><Link key={label} to={to} className={`flex items-center gap-3 rounded-lg px-3 py-2 text-sm ${to==="/lobbies"?"bg-primary/15 text-primary-glow":"text-muted-foreground hover:bg-secondary"}`}><Icon className="h-4 w-4"/>{label}</Link>)}</nav></div></aside><main className="min-w-0 flex-1 space-y-5"><header><p className="label-caps">GrindLobby</p><h1 className="font-display text-3xl font-bold">Lobbies</h1><p className="mt-1 text-sm text-muted-foreground">Somente salas realmente ativas aparecem na descoberta.</p></header>
 <section className="grid gap-4 xl:grid-cols-2"><div className="panel p-5"><h2 className="font-semibold">Criar lobby</h2><div className="mt-4 grid gap-3"><input value={name} onChange={e=>setName(e.target.value)} className="rounded-lg border border-border bg-panel px-3 py-2"/><select value={game} onChange={e=>setGame(e.target.value)} className="rounded-lg border border-border bg-panel px-3 py-2"><option>EA FC 27</option><option>VALORANT</option><option>CS2</option><option>Outro</option></select><button onClick={()=>void createLobby()} className="btn-primary flex items-center justify-center gap-2 rounded-lg px-4 py-2.5"><Plus className="h-4 w-4"/>Criar e entrar</button></div></div><div className="panel p-5"><h2 className="font-semibold">Entrar com código</h2><div className="mt-4 flex gap-2"><input value={joinCode} onChange={e=>setJoinCode(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void join()} className="min-w-0 flex-1 rounded-lg border border-border bg-panel px-3 py-2 uppercase" placeholder="GL-XXXXXX"/><button onClick={()=>void join()} className="btn-ghost flex items-center gap-2 rounded-lg px-4"><DoorOpen className="h-4 w-4"/>Entrar</button></div>{message&&<p className="mt-3 text-xs text-muted-foreground">{message}</p>}</div></section>
 <section className="panel p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Lobbies públicos</h2><p className="mt-1 text-xs text-muted-foreground">Presença em tempo real — salas vazias somem automaticamente.</p></div><span className="text-xs text-emerald-400">{publicLobbies.length} ativos</span></div>{publicLobbies.length===0?<p className="mt-5 text-sm text-muted-foreground">Nenhuma sala pública com jogadores online agora.</p>:<div className="mt-4 grid gap-3 lg:grid-cols-2">{publicLobbies.map(l=><div key={l.id} className="rounded-xl border border-border bg-panel/60 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{l.name}</p><p className="text-xs text-muted-foreground">{l.game} · {l.id}</p></div><span className="text-xs text-emerald-400">{l.members}/{l.maxPlayers}</span></div>{l.sharing>0&&<p className="mt-2 text-xs text-purple-300">{l.sharing} tela(s) aberta(s)</p>}<div className="mt-4 flex gap-2"><button onClick={()=>enter(l.id)} className="btn-primary flex-1 rounded-lg px-3 py-2 text-sm">Entrar</button><button onClick={()=>void copy(l.id)} className="btn-ghost rounded-lg px-3"><Copy className="h-4 w-4"/></button></div></div>)}</div>}</section>
 <section className="panel p-5"><h2 className="font-semibold">Suas salas abertas</h2>{saved.length===0?<p className="mt-4 text-sm text-muted-foreground">Nenhuma sala aberta vinculada à sua conta.</p>:<div className="mt-4 space-y-2">{saved.map(l=><div key={l.id} className="flex items-center gap-3 rounded-xl border border-border bg-panel/60 p-4"><button onClick={()=>enter(l.id)} className="min-w-0 flex-1 text-left"><p className="font-semibold">{l.name}</p><p className="text-xs text-muted-foreground">{l.id} · {l.game}</p></button><button onClick={()=>void copy(l.id)} className="btn-ghost rounded-lg p-2"><Copy className="h-4 w-4"/></button></div>)}</div>}</section>
 </main></div></div>}
