import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Copy, Headphones, Info, MessageSquare, Mic, MicOff, MonitorUp, Settings, UserPlus, Volume2, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";

export const Route = createFileRoute("/sala/$lobbyId")({ component: RoomPage });

type MediaSettings={mic:string;output:string;micVolume:number;outputVolume:number;sensitivity:number;noiseSuppression:boolean;echoCancellation:boolean;autoGainControl:boolean;voiceActivity:boolean;quality:string;bitrate:number;systemAudio:boolean;lowLatency:boolean;hardwareAcceleration:boolean;showPreview:boolean;joinSounds:boolean;muteSounds:boolean};
const defaults:MediaSettings={mic:"",output:"",micVolume:100,outputVolume:80,sensitivity:45,noiseSuppression:true,echoCancellation:true,autoGainControl:true,voiceActivity:true,quality:"720p30",bitrate:3500,systemAudio:true,lowLatency:true,hardwareAcceleration:true,showPreview:true,joinSounds:true,muteSounds:true};
const members=[{n:"Juan",r:"Você",c:"#22c55e"},{n:"Rhaz",r:"Admin",c:"#8b5cf6"},{n:"Mayk",r:"Moderador",c:"#a855f7"},{n:"PedroFPS",r:"Membro",c:"#3b82f6"},{n:"Lucas",r:"Membro",c:"#f59e0b"},{n:"DGZ",r:"Membro",c:"#9333ea"},{n:"Vozê",r:"Membro",c:"#2563eb"},{n:"GuiZin",r:"Membro",c:"#7c3aed"}];
function readCfg(){try{return{...defaults,...JSON.parse(localStorage.getItem("grind:mediaSettings")||"{}")};}catch{return defaults;}}
function preset(q:string){if(q==="1080p60")return{width:1920,height:1080,frameRate:60};if(q==="720p30")return{width:1280,height:720,frameRate:30};if(q==="480p30")return{width:854,height:480,frameRate:30};return{width:640,height:360,frameRate:30};}

function RoomPage(){
 const {lobbyId}=Route.useParams();const navigate=useNavigate();const [cfg,setCfg]=useState<MediaSettings>(defaults);const [muted,setMuted]=useState(false);const [deafened,setDeafened]=useState(false);const [micState,setMicState]=useState("conectando");const [screen,setScreen]=useState(false);const [tab,setTab]=useState<"chat"|"info">("chat");const [msg,setMsg]=useState("");const [messages,setMessages]=useState([{u:"Rhaz",t:"Bora jogar mais uma?"},{u:"PedroFPS",t:"Partiu! 🔥"},{u:"Mayk",t:"Chama no passe!"}]);const micStream=useRef<MediaStream|null>(null);const screenStream=useRef<MediaStream|null>(null);const videoRef=useRef<HTMLVideoElement|null>(null);
 useEffect(()=>{const s=readCfg();setCfg(s);connectMic(s);return()=>{micStream.current?.getTracks().forEach(t=>t.stop());screenStream.current?.getTracks().forEach(t=>t.stop())}},[]);
 const connectMic=async(s:MediaSettings)=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:s.mic?{exact:s.mic}:undefined,noiseSuppression:s.noiseSuppression,echoCancellation:s.echoCancellation,autoGainControl:s.autoGainControl}});micStream.current=stream;setMicState("conectado")}catch{setMicState("sem permissão")}};
 const toggleMute=()=>{const n=!muted;setMuted(n);micStream.current?.getAudioTracks().forEach(t=>t.enabled=!n)};
 const stopScreen=()=>{screenStream.current?.getTracks().forEach(t=>t.stop());screenStream.current=null;if(videoRef.current)videoRef.current.srcObject=null;setScreen(false)};
 const startScreen=async()=>{try{const p=preset(cfg.quality);const s=await navigator.mediaDevices.getDisplayMedia({video:{width:{ideal:p.width},height:{ideal:p.height},frameRate:{ideal:p.frameRate,max:p.frameRate}},audio:cfg.systemAudio});screenStream.current=s;setScreen(true);if(videoRef.current){videoRef.current.srcObject=s;videoRef.current.muted=true;await videoRef.current.play().catch(()=>{})}s.getVideoTracks()[0]?.addEventListener("ended",stopScreen,{once:true})}catch{}};
 const copyInvite=()=>navigator.clipboard.writeText(`${location.origin}/lobbies?join=${encodeURIComponent(lobbyId)}`);
 const leave=()=>{micStream.current?.getTracks().forEach(t=>t.stop());stopScreen();localStorage.removeItem("grind:activeLobby");navigate({to:"/lobbies"})};
 const send=()=>{if(!msg.trim())return;setMessages(v=>[...v,{u:"Juan",t:msg.trim()}]);setMsg("")};
 return <div className="min-h-screen bg-[#070910] text-white"><main className="mx-auto max-w-[1500px] p-4 md:p-6">
  <header className="mb-5 flex flex-wrap items-center gap-3"><img src="/grindlobby-logo.png" className="h-12 w-12 object-contain" alt="GL"/><div><p className="text-[10px] uppercase tracking-[.22em] text-white/40">Lobby de voz</p><h1 className="text-xl font-semibold">{lobbyId}</h1></div><div className="ml-2 hidden gap-2 md:flex"><span className="rounded-full bg-white/5 px-3 py-1 text-xs text-white/60">Pública</span><span className="rounded-full bg-white/5 px-3 py-1 text-xs text-white/60">EA FC 27</span><span className="rounded-full bg-white/5 px-3 py-1 text-xs text-emerald-400">8/10 membros</span></div><div className="ml-auto flex gap-2"><button onClick={copyInvite} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[.03]" title="Copiar convite"><UserPlus className="h-4 w-4"/></button><Link to="/configuracoes" className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[.03]"><Settings className="h-4 w-4"/></Link></div></header>
  <div className="grid gap-4 xl:grid-cols-[1fr_330px]">
   <section className="rounded-2xl border border-white/10 bg-[#0b0e17] p-4 md:p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-purple-400">Membros da sala</p><p className="mt-1 text-xs text-white/35">Microfone {micState}</p></div><span className="text-xs text-emerald-400">● 28ms</span></div>
    {screen&&<div className="mb-4 overflow-hidden rounded-xl border border-purple-500/30 bg-black"><video ref={videoRef} autoPlay playsInline className="max-h-[420px] w-full object-contain"/></div>}
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{members.map((m,i)=><div key={m.n} className="flex min-h-36 flex-col items-center justify-center rounded-xl border border-white/[.07] bg-white/[.025] p-3"><div className="grid h-14 w-14 place-items-center rounded-full border-2 text-lg font-semibold" style={{borderColor:m.c,boxShadow:i===0?`0 0 18px ${m.c}55`:undefined}}>{m.n[0]}</div><p className="mt-2 text-sm font-medium">{m.n}</p><p className="text-[11px] text-white/40">{m.r}</p><Mic className={`mt-2 h-4 w-4 ${i===5?"text-red-400":"text-emerald-400"}`}/></div>)}</div>
    <div className="mx-auto mt-5 flex w-fit items-center gap-2 rounded-2xl border border-white/10 bg-black/25 p-2"><button onClick={screen?stopScreen:startScreen} className={`grid h-11 w-11 place-items-center rounded-xl ${screen?"bg-purple-600":"bg-white/5"}`} title="Compartilhar tela">{screen?<X className="h-5 w-5"/>:<MonitorUp className="h-5 w-5"/>}</button><button onClick={toggleMute} className={`grid h-11 w-11 place-items-center rounded-xl ${muted?"bg-red-500/20 text-red-400":"bg-white/5"}`}>{muted?<MicOff className="h-5 w-5"/>:<Mic className="h-5 w-5"/>}</button><button onClick={()=>setDeafened(v=>!v)} className={`grid h-11 w-11 place-items-center rounded-xl ${deafened?"bg-red-500/20 text-red-400":"bg-white/5"}`}><Headphones className="h-5 w-5"/></button><Link to="/configuracoes" className="grid h-11 w-11 place-items-center rounded-xl bg-white/5"><Settings className="h-5 w-5"/></Link><div className="mx-1 h-7 w-px bg-white/10"/><button onClick={leave} className="grid h-11 w-11 place-items-center rounded-xl bg-red-600 text-white"><Headphones className="h-5 w-5"/></button></div>
   </section>
   <aside className="rounded-2xl border border-white/10 bg-[#0b0e17] p-4"><div className="flex gap-1 border-b border-white/10 pb-3"><button onClick={()=>setTab("chat")} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${tab==="chat"?"bg-purple-600/20 text-purple-300":"text-white/45"}`}><MessageSquare className="h-4 w-4"/>Chat</button><button onClick={()=>setTab("info")} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${tab==="info"?"bg-purple-600/20 text-purple-300":"text-white/45"}`}><Info className="h-4 w-4"/>Info</button></div>{tab==="chat"?<><div className="h-[430px] space-y-5 overflow-y-auto py-5">{messages.map((m,i)=><div key={i}><p className="text-xs font-semibold text-purple-300">{m.u}</p><p className="mt-1 text-sm text-white/70">{m.t}</p></div>)}</div><div className="flex gap-2"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Enviar mensagem..." className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm outline-none focus:border-purple-500/50"/><button onClick={send} className="rounded-xl bg-purple-600 px-4 text-sm">Enviar</button></div></>:<div className="space-y-4 py-5 text-sm text-white/60"><div><p className="text-xs uppercase tracking-wider text-white/30">Sala</p><p className="mt-1 text-white">{lobbyId}</p></div><div><p className="text-xs uppercase tracking-wider text-white/30">Qualidade</p><p className="mt-1">{cfg.quality} · {cfg.bitrate} kbps</p></div><div><p className="text-xs uppercase tracking-wider text-white/30">Áudio</p><p className="mt-1">Ruído {cfg.noiseSuppression?"ON":"OFF"} · Eco {cfg.echoCancellation?"ON":"OFF"}</p></div><button onClick={copyInvite} className="flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 py-2"><Copy className="h-4 w-4"/>Copiar convite</button></div>}</aside>
  </div>
  <div className="mt-4 flex items-center justify-between rounded-xl border border-white/[.07] bg-white/[.02] px-4 py-3 text-xs text-white/40"><span className="flex items-center gap-2"><Volume2 className="h-4 w-4"/>Saída {cfg.outputVolume}% · Microfone {cfg.micVolume}%</span><span>{cfg.lowLatency?"Baixa latência ativa":"Latência padrão"}</span></div>
 </main></div>;
}
