"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {Bell,CalendarDays,Gamepad2,Home,MessageCircle,Music2,Search,Settings,Trophy,UserRound,Users} from "lucide-react";
import styles from "./DesktopReferenceUI.module.css";
import GrindPortalLoading from "@/components/feedback/GrindPortalLoading";
import StoreShowcase from "@/components/dashboard/StoreShowcase";
import {disconnectActiveLiveKitVoice} from "@/lib/webrtc/useLobbyVoice";

type DesktopUser={id:string;username:string;display_name:string;email?:string;account_tier?:string;app_role?:string};
type Player={id:string;username:string;display_name:string;avatar:string|null;status?:string};
type Lobby={id:string;owner_id:string;name:string;visibility:string;max_members:number;status:string;memberCount:number;joined:boolean;game?:{name:string;slug:string}|null;owner?:Player|null;members?:Array<{userId:string;profile?:Player|null}>};
type DashboardData={lobbies:Lobby[];currentLobby:Lobby|null;online:Array<Player>;topPlayers:unknown[];account:{username:string;displayName:string;level:number;xp:number;avatar:string|null;banner:string|null;frame:string|null;effect:string|null;badge:string|null;cardStyle:string|null};entitlements:{tier:"free"|"pro";isAdmin:boolean};stats:{online:number;activeLobbies:number;myLobbies:number;rank:number};games:Array<{id:number;name:string;slug:string;rank:string;points:number}>};
type FriendState={friends:Array<{id:string;profile?:Player|null}>;incoming:Array<{id:string;profile?:Player|null}>;outgoing:Array<{id:string;profile?:Player|null}>};
type Community={id:string;name:string;description?:string|null;role?:string;memberCount?:number};
type CommunityDetail={community:Community;members?:Array<{user_id:string;role:string;profile?:Player|null}>;events?:Array<{id:string;title:string;starts_at:string;type?:string;status?:string}>;environments?:Array<{id:string;name:string;description?:string|null;lobby_id?:string|null}>;stats?:{members?:number;online?:number;activeRooms?:number}};
export type DesktopReferenceView="home"|"lobbies"|"community"|"music"|"friends"|"messages"|"tournaments"|"events"|"store"|"profile"|"settings";

const nav:[DesktopReferenceView,string,React.ReactNode][]=[
  ["home","Início",<Home key="home"/>],["community","Comunidades",<Users key="communities"/>],["lobbies","Lobbies",<Gamepad2 key="lobbies"/>],["music","Música",<Music2 key="music"/>],["friends","Amigos",<UserRound key="friends"/>],["messages","Mensagens",<MessageCircle key="messages"/>],["tournaments","Torneios",<Trophy key="tournaments"/>],["profile","Perfil",<UserRound key="profile"/>],["settings","Configurações",<Settings key="settings"/>]
];

function initials(value:string){return value.trim().split(/\s+/).map(p=>p[0]).join("").slice(0,2).toUpperCase()||"GL"}
function Avatar({name,url}:{name:string;url?:string|null}){return url?<img className={styles.avatar} src={url} alt=""/>:<span className={styles.avatarFallback}>{initials(name)}</span>}
function Empty({text}:{text:string}){return <div className={styles.empty}>{text}</div>}

export default function DesktopReferenceUI({user,initialView="home"}:{user:DesktopUser;initialView?:DesktopReferenceView}){
  const router=useRouter();
  const [view,setView]=useState<DesktopReferenceView>(initialView);
  const [data,setData]=useState<DashboardData|null>(null);
  const [friends,setFriends]=useState<FriendState>({friends:[],incoming:[],outgoing:[]});
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const load=useCallback(async()=>{try{const [d,f]=await Promise.all([fetch("/api/dashboard",{cache:"no-store"}),fetch("/api/friends",{cache:"no-store"})]);const body=await d.json();if(!d.ok)throw new Error(body.error||"Falha ao abrir o GrindLobby Desktop.");setData(body);if(f.ok)setFriends(await f.json());setError("")}catch(e){setError(e instanceof Error?e.message:"Falha ao abrir o desktop.")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load();const t=window.setInterval(()=>void load(),20000);return()=>window.clearInterval(t)},[load]);
  const display=data?.account?.displayName||user.display_name||user.username;
  const friendProfiles=useMemo(()=>friends.friends.map(i=>i.profile).filter((p):p is Player=>Boolean(p)),[friends]);
  const lobbies=useMemo(()=>data?.lobbies?.filter(l=>l.status==="open")??[],[data]);
  const setRoute=(next:DesktopReferenceView)=>{setView(next);router.replace(`/?desktop=1&view=${next}`)};
  const openLobby=async(lobby:Lobby)=>{try{if(!lobby.joined){const r=await fetch(`/api/lobbies/${lobby.id}/join`,{method:"POST"});if(!r.ok)throw new Error("Não foi possível entrar no lobby.")}router.push(`/lobby/${lobby.id}?desktop=1`)}catch(e){setError(e instanceof Error?e.message:"Falha ao entrar no lobby.")}};
  const logout=async()=>{await disconnectActiveLiveKitVoice(true);await fetch("/api/auth/logout",{method:"POST"});router.push("/login?desktop=1")};
  if(loading&&!data)return <GrindPortalLoading variant="fullscreen" label="Abrindo GrindLobby"/>;
  return <main className={styles.root}>
    <aside className={styles.sidebar}>
      <div className={styles.brand}><img src="/brand/grindlobby-official.png" alt=""/><span>GRINDLOBBY</span></div>
      <nav className={styles.nav}>{nav.map(([id,label,icon])=><button key={id} onClick={()=>setRoute(id)} className={view===id?styles.active:""}>{icon}<span>{label}</span></button>)}</nav>
      <div className={styles.spacer}/>
      <button className={styles.miniProfile} onClick={()=>setRoute("profile")}><Avatar name={display} url={data?.account.avatar}/><span><b>{display}</b><small className={styles.online}>Online</small></span></button>
      <button className={styles.bottomBtn} onClick={()=>void logout()}>Sair</button>
    </aside>
    <div className={styles.shell}><section className={styles.stage}>
      {view==="home"&&<HomeView display={display} data={data} friends={friendProfiles} lobbies={lobbies} openLobby={openLobby} go={setRoute}/>} 
      {view==="community"&&<CommunityView lobbies={lobbies} openLobby={openLobby}/>} 
      {view==="lobbies"&&<LobbiesView lobbies={lobbies} openLobby={openLobby}/>} 
      {view==="music"&&<MusicView/>}
      {view==="friends"&&<FriendsView friends={friendProfiles}/>} 
      {view==="messages"&&<MessagesView friends={friendProfiles}/>} 
      {(view==="tournaments"||view==="events")&&<TournamentsView/>}
      {view==="store"&&<div className={styles.page}><StoreShowcase display={display} isAdmin={Boolean(data?.entitlements.isAdmin)}/></div>}
      {view==="profile"&&<ProfileView display={display} data={data}/>} 
      {view==="settings"&&<SettingsView data={data}/>} 
      {error&&<div className={styles.section}>{error}</div>}
    </section></div>
  </main>
}

function HomeView({display,data,friends,lobbies,openLobby,go}:{display:string;data:DashboardData|null;friends:Player[];lobbies:Lobby[];openLobby:(l:Lobby)=>void;go:(v:DesktopReferenceView)=>void}){
  const rank=data?.stats?.rank??0;return <div className={`${styles.page} ${styles.homeGrid}`}><div>
    <section className={styles.hero}><div><h1>Boa noite, {display}</h1><p>Que comece o grind.</p></div><img className={styles.heroLogo} src="/brand/grindlobby-official.png" alt="GrindLobby"/></section>
    <div className={styles.stats}><div className={styles.stat}><small>Nível</small><b>{data?.account.level??1}</b></div><div className={styles.stat}><small>XP</small><b>{data?.account.xp??0}</b></div><div className={styles.stat}><small>Lobbies</small><b>{data?.stats.myLobbies??0}</b></div><div className={styles.stat}><small>Online</small><b>{data?.stats.online??0}</b></div><div className={styles.stat}><small>Ranking</small><b>{rank||"—"}</b></div></div>
    <section className={styles.section}><div className={styles.sectionHead}><h3>Destaques</h3><button className={styles.linkBtn} onClick={()=>go("tournaments")}>Ver todos</button></div><div className={styles.playlistCards}><div className={styles.playlist}><div className={styles.playlistArt}/><b>Torneios</b><small>Competição GrindLobby</small></div><div className={styles.playlist}><div className={styles.playlistArt}/><b>Comunidades</b><small>Atividade recente</small></div><div className={styles.playlist}><div className={styles.playlistArt}/><b>Música</b><small>Player separado</small></div><div className={styles.playlist}><div className={styles.playlistArt}/><b>Lobbies</b><small>Entre rápido</small></div></div></section>
    <section className={styles.section}><div className={styles.sectionHead}><h3>Atividade recente</h3><button className={styles.linkBtn} onClick={()=>go("lobbies")}>Ver lobbies</button></div>{lobbies.slice(0,5).map(l=><div className={styles.lobbyRow} key={l.id}><span className={styles.avatarFallback}>{initials(l.game?.name||l.name)}</span><span><b>{l.name}</b><small>{l.game?.name||"GrindLobby"} · {l.memberCount}/{l.max_members}</small></span><div className={styles.spacer}/><button className={styles.secondary} onClick={()=>openLobby(l)}>Entrar</button></div>)}{!lobbies.length&&<Empty text="Nenhum lobby aberto agora."/>}</section>
  </div><aside className={styles.rightRail}><section className={styles.railCard}><h4>Amigos online</h4>{friends.slice(0,7).map(f=><div className={styles.friendRow} key={f.id}><Avatar name={f.display_name||f.username} url={f.avatar}/><span><b>{f.display_name||f.username}</b><small className={styles.online}>{f.status||"Online"}</small></span></div>)}{!friends.length&&<Empty text="Nenhum amigo online."/>}</section><section className={styles.railCard}><h4>Status</h4><div className={styles.stat}><small>Desempenho</small><b>Otimizado</b></div><div className={styles.stat}><small>Call e tela</small><b>Dentro de lobbies/comunidades</b></div></section></aside></div>
}

function CommunityView({lobbies,openLobby}:{lobbies:Lobby[];openLobby:(l:Lobby)=>void}){
  const [list,setList]=useState<Community[]>([]);const [detail,setDetail]=useState<CommunityDetail|null>(null);const [busy,setBusy]=useState(true);
  useEffect(()=>{let live=true;(async()=>{const r=await fetch("/api/communities",{cache:"no-store"});if(r.ok){const b=await r.json();const c=(b.communities??[]) as Community[];if(!live)return;setList(c);if(c[0]){const d=await fetch(`/api/communities/${c[0].id}`,{cache:"no-store"});if(d.ok&&live)setDetail(await d.json())}}if(live)setBusy(false)})();return()=>{live=false}},[]);
  if(busy)return <div className={styles.page}><Empty text="Carregando comunidades..."/></div>;
  if(!list.length)return <div className={styles.page}><Empty text="Você ainda não participa de uma comunidade."/></div>;
  const c=detail?.community||list[0];const env=detail?.environments??[];const members=detail?.members??[];const events=detail?.events??[];
  return <div className={`${styles.page} ${styles.communityLayout}`}><header className={styles.communityTop}><div><h2>{c.name}</h2><small>{detail?.stats?.members??c.memberCount??0} membros · {detail?.stats?.online??0} online</small></div><button className={styles.primary}>Convidar</button></header>
  <aside className={styles.sidePanel}><h4>Canais</h4>{env.map((e,i)=><div key={e.id} className={`${styles.channel} ${i===0?styles.active:""}`}><span>{e.name}</span><small>{e.lobby_id?"ativo":"—"}</small></div>)}{!env.length&&<Empty text="Nenhum canal configurado."/>}</aside>
  <main className={styles.feed}><div className={styles.feedTabs}><button>Tudo</button><button>Discussões</button><button>Atualizações</button><button>Mídia</button><button>Partidas</button></div><article className={styles.post}><div className={styles.postHead}><span className={styles.avatarFallback}>GL</span><div><b>{c.name}</b><small> · agora</small></div></div><p>{c.description||"Central da comunidade. Organize treinos, estratégias, eventos e partidas sem transformar a experiência em um clone do Discord."}</p></article>{events.slice(0,3).map(e=><article className={styles.post} key={e.id}><b>{e.title}</b><p>{new Date(e.starts_at).toLocaleString("pt-BR")}</p><div className={styles.postMedia}>Evento da comunidade</div></article>)}<article className={styles.post}><b>Salas ativas</b>{env.filter(e=>e.lobby_id).map(e=>{const l=lobbies.find(x=>String(x.id)===String(e.lobby_id));return <div className={styles.lobbyRow} key={e.id}><span><b>{e.name}</b><small>{l?`${l.memberCount}/${l.max_members}`:"Sala vinculada"}</small></span><div className={styles.spacer}/>{l&&<button className={styles.primary} onClick={()=>openLobby(l)}>Entrar</button>}</div>})}</article></main>
  <aside className={styles.infoPanel}><h4>Atividade ao vivo</h4>{members.slice(0,8).map(m=><div className={styles.friendRow} key={m.user_id}><Avatar name={m.profile?.display_name||m.profile?.username||"GL"} url={m.profile?.avatar}/><span><b>{m.profile?.display_name||m.profile?.username||"Membro"}</b><small>{m.role}</small></span></div>)}</aside></div>
}

function LobbiesView({lobbies,openLobby}:{lobbies:Lobby[];openLobby:(l:Lobby)=>void}){return <div className={styles.page}><section className={styles.section}><div className={styles.sectionHead}><h3>Lobbies</h3><button className={styles.primary}>Criar lobby</button></div>{lobbies.map(l=><div className={styles.lobbyRow} key={l.id}><span className={styles.avatarFallback}>{initials(l.game?.name||l.name)}</span><span><b>{l.name}</b><small>{l.game?.name||"GrindLobby"} · {l.visibility}</small></span><div className={styles.spacer}/><small>{l.memberCount}/{l.max_members}</small><button className={styles.primary} onClick={()=>openLobby(l)}>Entrar</button></div>)}{!lobbies.length&&<Empty text="Nenhum lobby aberto agora."/>}</section></div>}

function MusicView(){const lists=["Focus Mode","Energy Boost","Chill Lobby","Trap Legends","Daily Mix","Grind Session","Night Drives","E-sports Hits"];return <div className={`${styles.page} ${styles.musicGrid}`}><section className={styles.musicPane}><div className={styles.sectionHead}><h3>Música</h3><button className={styles.linkBtn}>Histórico</button></div><input className={styles.search} placeholder="Buscar músicas, artistas, playlists..."/><div className={styles.playlistCards}>{lists.map(x=><div className={styles.playlist} key={x}><div className={styles.playlistArt}/><b>{x}</b><small>Playlist GrindLobby</small></div>)}</div></section><aside className={styles.player}><div className={styles.playerCover}/><b>Player separado</b><p style={{color:"#8a91a3",fontSize:10}}>A música fica fora da call. O áudio de voz e compartilhamento continua pertencendo ao lobby ou à comunidade.</p><div className={styles.playerControls}><button className={styles.secondary}>◀</button><button className={styles.primary}>▶</button><button className={styles.secondary}>▶</button></div></aside></div>}

function FriendsView({friends}:{friends:Player[]}){return <div className={`${styles.page} ${styles.friendsGrid}`}><section className={styles.friendsPane}><div className={styles.sectionHead}><h3>Amigos</h3><button className={styles.primary}>Adicionar amigo</button></div><input className={styles.search} placeholder="Buscar amigos..."/>{friends.map(f=><div className={styles.friendRow} key={f.id}><Avatar name={f.display_name||f.username} url={f.avatar}/><span><b>{f.display_name||f.username}</b><small className={styles.online}>{f.status||"Online"}</small></span><div className={styles.spacer}/><button className={styles.secondary}>Mensagem</button></div>)}{!friends.length&&<Empty text="Sua lista de amigos está vazia."/>}</section><aside className={styles.railCard}><h4>Social</h4><p style={{color:"#8a91a3",fontSize:10}}>Mensagens, convites e presença ficam separados da experiência de call para manter a interface leve.</p></aside></div>}

function MessagesView({friends}:{friends:Player[]}){const active=friends[0];return <div className={`${styles.page} ${styles.messagesGrid}`}><aside className={styles.messagesPane}><h3 style={{fontSize:13}}>Mensagens</h3><input className={styles.search} placeholder="Buscar conversas..."/>{friends.slice(0,10).map(f=><div className={styles.conversationRow} key={f.id}><Avatar name={f.display_name||f.username} url={f.avatar}/><span><b>{f.display_name||f.username}</b><small>{f.status||"Online"}</small></span></div>)}</aside><main className={styles.chat}><div className={styles.chatHead}><b>{active?.display_name||active?.username||"Conversa"}</b></div><div className={styles.chatBody}><div className={styles.bubble}>A interface de mensagens continua simples e independente das calls.</div><div className={`${styles.bubble} ${styles.bubbleMine}`}>Fechado. A call aparece apenas quando eu entro em uma sala.</div></div><div className={styles.chatInput}><input placeholder="Digite sua mensagem..."/><button className={styles.primary}>Enviar</button></div></main><aside className={styles.infoPanel}><h4>Detalhes</h4>{active?<><Avatar name={active.display_name||active.username} url={active.avatar}/><p style={{fontSize:10,color:"#8a91a3"}}>{active.display_name||active.username}</p></>:<Empty text="Selecione uma conversa."/>}</aside></div>}

function ProfileView({display,data}:{display:string;data:DashboardData|null}){const avatar=data?.account.avatar;const [preview,setPreview]=useState<string|null>(null);const [aiState,setAiState]=useState<"idle"|"working"|"unavailable">("idle");async function generate(){setAiState("working");try{const r=await fetch("/api/profile/avatar-3d",{method:"POST"});if(!r.ok){setAiState("unavailable");return}const b=await r.json();setPreview(b.imageUrl||null);setAiState("idle")}catch{setAiState("unavailable")}}return <div className={`${styles.page} ${styles.profileLayout}`}><section className={styles.characterCard}>{preview?<img className={styles.character} src={preview} alt="Prévia 3D"/>:<div className={styles.characterFallback}/>}<small style={{color:"#8a91a3"}}>Prévia do personagem no perfil</small></section><section className={styles.profilePane}><header className={styles.profileTop}><div><h2>{display}</h2><small>Nível {data?.account.level??1} · {data?.account.xp??0} XP</small></div><button className={styles.secondary}>Editar perfil</button></header><div className={styles.customGrid}><section className={styles.customSection}><h4>Avatar IA</h4><div className={styles.aiBox}><div>{avatar?<img className={styles.aiPhoto} src={avatar} alt="Foto do perfil"/>:<span className={styles.aiPhoto}/>}</div><div><b>Transformar foto em personagem 3D</b><p style={{fontSize:10,color:"#8a91a3"}}>A IA usa a foto atual do perfil como referência facial e gera somente uma prévia visual para o perfil.</p><button className={styles.primary} onClick={()=>void generate()} disabled={!avatar||aiState==="working"}>{aiState==="working"?"Gerando...":"Gerar prévia 3D"}</button>{aiState==="unavailable"&&<small style={{display:"block",marginTop:8,color:"#d9a7ff"}}>O endpoint de geração precisa de um provedor de imagem configurado para produzir a prévia real.</small>}</div><div className={styles.aiPreview}>{preview?<img src={preview} alt="Avatar 3D"/>:<span className={styles.avatarFallback}>3D</span>}</div></div></section><section className={styles.customSection}><h4>Trajes</h4><div className={styles.thumbRow}>{[1,2,3,4,5].map((n)=><div key={n} className={`${styles.thumb} ${n===1?styles.active:""}`}/>)}</div></section><section className={styles.customSection}><h4>Efeitos de entrada</h4><div className={styles.thumbRow}>{[1,2,3,4,5].map(n=><div className={styles.effect} key={n}/>)}</div></section><section className={styles.customSection}><h4>Insígnias</h4><div className={styles.thumbRow}>{[1,2,3,4,5].map(n=><div className={styles.badge} key={n}/>)}</div></section><button className={styles.primary}>Salvar alterações</button></div></section></div>}

function TournamentsView(){return <div className={styles.page}><section className={styles.tournamentHero}><div><small>GRINDLOBBY</small><h2 style={{margin:"6px 0"}}>GL CUP</h2><p style={{fontSize:10,color:"#8a91a3"}}>Competição integrada ao hub, sem poluir a experiência principal.</p></div><button className={styles.primary}>Ver inscrições</button></section><section className={styles.tournamentsPane}><div className={styles.sectionHead}><h3>Chaveamento</h3><button className={styles.linkBtn}>Classificação</button></div><div className={styles.bracket}>{["Quartas","Semifinal","Final","Campeão"].map((r,i)=><div className={styles.round} key={r}><b style={{fontSize:10}}>{r}</b>{Array.from({length:Math.max(1,4-i)}).map((_,n)=><div className={styles.match} key={n}>Squad {n+1}<br/><small style={{color:"#8a91a3"}}>vs · aguardando</small></div>)}</div>)}</div></section></div>}

function SettingsView({data}:{data:DashboardData|null}){return <div className={`${styles.page} ${styles.settingsGrid}`}><aside className={styles.sidePanel}><h4>Configurações</h4><div className={`${styles.channel} ${styles.active}`}>Desempenho</div><div className={styles.channel}>Áudio</div><div className={styles.channel}>Notificações</div><div className={styles.channel}>Atalhos</div><div className={styles.channel}>Conta</div></aside><main className={styles.settingsPane}><h3 style={{fontSize:13}}>Desempenho</h3>{["Modo leve","Priorizar jogos","Otimizar memória","Pausar animações em segundo plano","Limpar cache automaticamente"].map(x=><div className={styles.settingRow} key={x}><span>{x}</span><span className={styles.toggle}/></div>)}</main><aside className={styles.infoPanel}><h4>Monitoramento</h4><div className={styles.stat}><small>Online</small><b>{data?.stats.online??0}</b></div><div className={styles.stat}><small>Lobbies ativos</small><b>{data?.stats.activeLobbies??0}</b></div><p style={{fontSize:10,color:"#8a91a3"}}>Esta versão desktop prioriza interface enxuta, menos efeitos permanentes e menor carga visual.</p></aside></div>}
