"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {Bell,CalendarDays,ChevronRight,Gamepad2,Headphones,Home,LogOut,Mic,Plus,RefreshCw,Search,Settings,ShoppingCart,Store,Trophy,UserRound,Users,Wifi,Zap} from "lucide-react";
import GrindPortalLoading from "@/components/feedback/GrindPortalLoading";
import StoreShowcase from "@/components/dashboard/StoreShowcase";
import {disconnectActiveLiveKitVoice} from "@/lib/webrtc/useLobbyVoice";

type DesktopUser={id:string;username:string;display_name:string;email?:string;account_tier?:string;app_role?:string};
type Player={id:string;username:string;display_name:string;avatar:string|null;status?:string};
type Lobby={id:string;owner_id:string;name:string;visibility:string;max_members:number;status:string;memberCount:number;joined:boolean;game?:{name:string;slug:string}|null;owner?:Player|null;members?:Array<{userId:string;profile?:Player|null}>};
type DashboardData={lobbies:Lobby[];currentLobby:Lobby|null;online:Array<Player&{player?:unknown}>;topPlayers:unknown[];account:{username:string;displayName:string;level:number;xp:number;avatar:string|null;banner:string|null;frame:string|null;effect:string|null;badge:string|null;cardStyle:string|null};entitlements:{tier:"free"|"pro";isAdmin:boolean};stats:{online:number;activeLobbies:number;myLobbies:number;rank:number};games:Array<{id:number;name:string;slug:string;rank:string;points:number}>};
type View="home"|"store"|"profile"|"settings";

function initials(value:string){return value.trim().split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase()||"GL"}
function Avatar({name,url}:{name:string;url?:string|null}){return <span className="nh-avatar">{url?<img src={url} alt=""/>:initials(name)}</span>}

export default function DesktopHome({user,initialView="home"}:{user:DesktopUser;initialView?:View}){
  const router=useRouter();
  const [data,setData]=useState<DashboardData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState<string|null>(null),[view,setView]=useState<View>(initialView);
  const load=useCallback(async()=>{try{const response=await fetch("/api/dashboard",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Falha ao carregar o desktop.");setData(body as DashboardData);setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Falha ao carregar o desktop.")}finally{setLoading(false)}},[]);
  useEffect(()=>{const start=window.setTimeout(()=>void load(),0),timer=window.setInterval(()=>void load(),20_000);return()=>{window.clearTimeout(start);window.clearInterval(timer)}},[load]);

  const display=data?.account?.displayName||user.display_name||user.username,online=data?.online??[],publicLobbies=useMemo(()=>data?.lobbies?.filter(item=>item.visibility==="public"&&item.status==="open").slice(0,6)??[],[data?.lobbies]);
  const current=data?.currentLobby??null,isAdmin=Boolean(data?.entitlements?.isAdmin),isPro=isAdmin||data?.entitlements?.tier==="pro";
  const route=(path:string)=>router.push(`${path}${path.includes("?")?"&":"?"}desktop=1`);
  const selectView=(next:View)=>{setView(next);router.replace(`/?desktop=1&view=${next}`)};
  async function openLobby(lobby:Lobby){setBusy(lobby.id);try{if(!lobby.joined){const response=await fetch(`/api/lobbies/${lobby.id}/join`,{method:"POST"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Não foi possível entrar.")}route(`/lobby/${lobby.id}`)}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível entrar.")}finally{setBusy(null)}}
  async function logout(){setBusy("logout");try{await disconnectActiveLiveKitVoice(true);await fetch("/api/auth/logout",{method:"POST"});router.push("/login?desktop=1");router.refresh()}finally{setBusy(null)}}

  if(loading&&!data)return <GrindPortalLoading variant="fullscreen" label="Abrindo GrindLobby Desktop"/>;

  return <main className="native-home">
    <aside className="nh-rail"><button className="nh-logo" onClick={()=>selectView("home")}><img src="/brand/grindlobby-official.png" alt=""/></button><nav><button className={view==="home"?"active":""} onClick={()=>selectView("home")}><Home/><span>Início</span></button><button onClick={()=>route("/community")}><Users/><span>Comunidades</span></button><button onClick={()=>current?route(`/lobby/${current.id}`):selectView("home")}><Mic/><span>Voz</span></button><button onClick={()=>route("/competitive/valorant")}><Trophy/><span>Matchmaking</span></button><button onClick={()=>route("/competitive/valorant")}><CalendarDays/><span>Eventos</span></button><button className={view==="store"?"active":""} onClick={()=>selectView("store")}><Store/><span>Loja</span></button></nav><div className="nh-rail-fill"/><nav><button className={view==="profile"?"active":""} onClick={()=>selectView("profile")}><UserRound/><span>Perfil</span></button><button className={view==="settings"?"active":""} onClick={()=>selectView("settings")}><Settings/><span>Configurações</span></button></nav></aside>

    <header className="nh-top"><div className="nh-search"><Search/><span>Buscar jogadores, squads ou jogos…</span><kbd>Ctrl K</kbd></div><div className="nh-top-icons"><button><Bell/></button><button onClick={()=>void load()}><RefreshCw/></button><div className="nh-user"><Avatar name={display} url={data?.account?.avatar}/><span><b>{display}</b><small><i/>Online</small></span></div></div></header>

    {view==="home"?<>
      <aside className="nh-left"><section><div className="nh-section-title"><span>SUAS COMUNIDADES</span><button onClick={()=>route("/community")}><Plus/></button></div><div className="nh-community-list"><button onClick={()=>route("/community")} className="active"><span className="nh-emblem purple">GL</span><span><b>GrindLobby</b><small><i/>{data?.stats?.online??1} online</small></span></button><button onClick={()=>route("/competitive/valorant")}><span className="nh-emblem red">V</span><span><b>VALORANT</b><small>Competitivo</small></span></button></div><button className="nh-browse" onClick={()=>route("/community")}><Users/>Explorar comunidades</button></section><section className="nh-channels"><div className="nh-section-title"><span>CANAIS DE VOZ</span><Headphones/></div>{current?<button className="active" onClick={()=>route(`/lobby/${current.id}`)}><Headphones/><span><b>{current.name}</b><small>{current.memberCount}/{current.max_members} membros</small></span></button>:<div className="nh-empty-small">Nenhuma call ativa.</div>}<button onClick={()=>selectView("home")}><Headphones/><span><b>Lobby</b><small>Salas públicas abaixo</small></span></button></section><div className="nh-voice-card"><span className={current?"connected":""}><i/>{current?"Voice Connected":"Voice Ready"}</span><small>{current?.name||"Sem sala ativa"}</small><div><button onClick={()=>current&&route(`/lobby/${current.id}`)}><Mic/></button><button onClick={()=>current&&route(`/lobby/${current.id}`)}><Headphones/></button><button onClick={()=>selectView("settings")}><Settings/></button></div></div></aside>

      <section className="nh-main"><div className="nh-hero"><div><span>DESKTOP HUB</span><h1>{current?current.name:"PRONTO PARA JOGAR"}</h1><p>{current?`${current.game?.name||"GrindLobby"} · ${current.memberCount}/${current.max_members} jogadores`:"Encontre seu squad, entre na call e prepare a partida sem sair do GrindLobby."}</p><div>{current?<button className="primary" onClick={()=>route(`/lobby/${current.id}`)}><Headphones/>Abrir call</button>:<button className="primary" onClick={()=>route("/competitive/valorant")}><Trophy/>Encontrar partida</button>}<button onClick={()=>route("/community")}><Users/>Comunidades</button></div></div><div className="nh-hero-mark"><img src="/brand/grindlobby-official.png" alt=""/></div></div><div className="nh-grid-head"><span><b>LOBBIES ATIVOS</b><small>{data?.stats?.activeLobbies??0} disponíveis</small></span><button onClick={()=>void load()}>Atualizar<ChevronRight/></button></div><div className="nh-lobby-grid">{publicLobbies.map(lobby=><article key={lobby.id}><div className="nh-lobby-icon">{initials(lobby.game?.name||lobby.name)}</div><div><b>{lobby.name}</b><small>{lobby.game?.name||"GrindLobby"} · host {lobby.owner?.display_name||lobby.owner?.username||"Player"}</small><span>{lobby.memberCount}/{lobby.max_members} jogadores</span></div><button onClick={()=>void openLobby(lobby)} disabled={busy===lobby.id}>{busy===lobby.id?"…":"Entrar"}</button></article>)}{!publicLobbies.length?<div className="nh-empty">Nenhum lobby público disponível agora.</div>:null}</div><div className="nh-quick"><button onClick={()=>route("/competitive/valorant")}><Trophy/><span><b>Encontrar partida</b><small>VALORANT competitivo</small></span></button><button onClick={()=>route("/community")}><Users/><span><b>Comunidades</b><small>Entre com convite ou link</small></span></button><button onClick={()=>selectView("store")}><ShoppingCart/><span><b>Loja</b><small>Cosméticos e bundles</small></span></button></div></section>

      <aside className="nh-right"><section><div className="nh-section-title"><span>STATUS</span><Wifi/></div><div className="nh-status"><i/><span><b>Online</b><small>{isAdmin?"Admin":isPro?"Pro":"Free"}</small></span></div></section><section><div className="nh-section-title"><span>AMIGOS ONLINE</span><small>{online.length}</small></div><div className="nh-friends">{online.slice(0,7).map(person=><div key={person.id}><Avatar name={person.display_name||person.username} url={person.avatar}/><span><b>{person.display_name||person.username}</b><small><i/>Online</small></span><Gamepad2/></div>)}{!online.length?<p>Ninguém online agora.</p>:null}</div></section><section><div className="nh-section-title"><span>CONTA</span><Settings/></div><div className="nh-account"><b>Nível {data?.account?.level??1}</b><small>{data?.account?.xp??0} XP · Rank #{data?.stats?.rank||"—"}</small><button onClick={()=>selectView("profile")}>Abrir perfil</button><button onClick={()=>void logout()} disabled={busy==="logout"}><LogOut/>Sair</button></div></section></aside>
    </>:null}

    {view==="store"?<section className="nh-view"><StoreShowcase display={display} isAdmin={isAdmin}/></section>:null}
    {view==="profile"?<section className="nh-view"><div className="nh-native-panel"><Avatar name={display} url={data?.account?.avatar}/><span>PERFIL DESKTOP</span><h1>{display}</h1><p>@{data?.account?.username||user.username} · Nível {data?.account?.level??1} · {data?.account?.xp??0} XP</p><div className="nh-profile-stats"><article><b>{data?.stats?.rank||"—"}</b><small>Ranking</small></article><article><b>{data?.stats?.myLobbies??0}</b><small>Meus lobbies</small></article><article><b>{isPro?"PRO":"FREE"}</b><small>Plano</small></article></div><button onClick={()=>selectView("home")}><Home/>Voltar ao início</button></div></section>:null}
    {view==="settings"?<section className="nh-view"><div className="nh-native-panel"><Settings/><span>CONFIGURAÇÕES DESKTOP</span><h1>Cliente Windows</h1><p>Áudio detalhado, saída, filtros e transmissão são ajustados dentro da sala para aplicar diretamente ao LiveKit sem duplicar estados.</p><div className="nh-settings-list"><article><b>Modo</b><small>Standard Desktop</small></article><article><b>Transmissão</b><small>{isPro?"até 1080p60":"até 720p30"}</small></article><article><b>Voz</b><small>Opus + RED · SFU</small></article></div><button onClick={()=>selectView("home")}><Home/>Voltar ao início</button></div></section>:null}
    {error?<div className="nh-error">{error}</div>:null}
  </main>;
}
