"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {Bell,CalendarDays,Gamepad2,Headphones,Home,MessageCircle,Mic,MicOff,MoreHorizontal,Music2,Plus,RefreshCw,Search,Send,Settings,Store,UserPlus,UserRound,Users,Video,Volume2} from "lucide-react";
import GrindPortalLoading from "@/components/feedback/GrindPortalLoading";
import StoreShowcase from "@/components/dashboard/StoreShowcase";
import {disconnectActiveLiveKitVoice} from "@/lib/webrtc/useLobbyVoice";

type DesktopUser={id:string;username:string;display_name:string;email?:string;account_tier?:string;app_role?:string};
type Player={id:string;username:string;display_name:string;avatar:string|null;status?:string};
type Lobby={id:string;owner_id:string;name:string;visibility:string;max_members:number;status:string;memberCount:number;joined:boolean;game?:{name:string;slug:string}|null;owner?:Player|null;members?:Array<{userId:string;profile?:Player|null}>};
type DashboardData={lobbies:Lobby[];currentLobby:Lobby|null;online:Array<Player&{player?:unknown}>;topPlayers:unknown[];account:{username:string;displayName:string;level:number;xp:number;avatar:string|null;banner:string|null;frame:string|null;effect:string|null;badge:string|null;cardStyle:string|null};entitlements:{tier:"free"|"pro";isAdmin:boolean};stats:{online:number;activeLobbies:number;myLobbies:number;rank:number};games:Array<{id:number;name:string;slug:string;rank:string;points:number}>};
type FriendItem={id:string;profile?:Player|null};
type FriendState={friends:FriendItem[];incoming:FriendItem[];outgoing:FriendItem[]};
type DirectMessage={id:string;sender_id:string;recipient_id:string;body:string;created_at:string};
type Community={id:string;name:string;description?:string|null;role?:string;memberCount?:number};
type CommunityDetail={community:Community;members?:Array<{user_id:string;role:string;profile?:Player|null}>;events?:Array<{id:string;title:string;starts_at:string;type?:string;status?:string}>;environments?:Array<{id:string;name:string;description?:string|null;lobby_id?:string|null}>;stats?:{members?:number;online?:number;activeRooms?:number}};
type View="home"|"lobbies"|"community"|"friends"|"messages"|"events"|"store"|"profile"|"settings";

function initials(value:string){return value.trim().split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase()||"GL"}
function Avatar({name,url,lg=false}:{name:string;url?:string|null;lg?:boolean}){return <span className={`gl-avatar${lg?" lg":""}`}>{url?<img src={url} alt=""/>:initials(name)}</span>}
function Status({label="Online"}:{label?:string}){return <small className="gl-status"><i/>{label}</small>}
function EmptyState({title,text}:{title:string;text:string}){return <div className="gl-empty"><b>{title}</b><small>{text}</small></div>}

export default function DesktopHome({user,initialView="home"}:{user:DesktopUser;initialView?:View}){
  const router=useRouter();
  const [data,setData]=useState<DashboardData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState<string|null>(null),[view,setView]=useState<View>(initialView);
  const [friends,setFriends]=useState<FriendState>({friends:[],incoming:[],outgoing:[]});
  const load=useCallback(async()=>{try{const [dashboardResponse,friendsResponse]=await Promise.all([fetch("/api/dashboard",{cache:"no-store"}),fetch("/api/friends",{cache:"no-store"})]);const dashboardBody=await dashboardResponse.json();if(!dashboardResponse.ok)throw new Error(dashboardBody.error||"Falha ao carregar o desktop.");setData(dashboardBody as DashboardData);if(friendsResponse.ok)setFriends(await friendsResponse.json() as FriendState);setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Falha ao carregar o desktop.")}finally{setLoading(false)}},[]);
  useEffect(()=>{const start=window.setTimeout(()=>void load(),0),timer=window.setInterval(()=>void load(),20_000);return()=>{window.clearTimeout(start);window.clearInterval(timer)}},[load]);

  const display=data?.account?.displayName||user.display_name||user.username;
  const lobbies=useMemo(()=>data?.lobbies?.filter(item=>item.status==="open").slice(0,8)??[],[data?.lobbies]);
  const current=data?.currentLobby??null,isAdmin=Boolean(data?.entitlements?.isAdmin),isPro=isAdmin||data?.entitlements?.tier==="pro";
  const friendProfiles=useMemo(()=>friends.friends.map(item=>item.profile).filter((profile):profile is Player=>Boolean(profile)),[friends.friends]);
  const selectView=(next:View)=>{setView(next);router.replace(`/?desktop=1&view=${next}`)};
  const route=(path:string)=>router.push(`${path}${path.includes("?")?"&":"?"}desktop=1`);
  async function openLobby(lobby:Lobby){setBusy(lobby.id);try{if(!lobby.joined){const response=await fetch(`/api/lobbies/${lobby.id}/join`,{method:"POST"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Não foi possível entrar.")}route(`/lobby/${lobby.id}`)}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível entrar.")}finally{setBusy(null)}}
  async function logout(){setBusy("logout");try{await disconnectActiveLiveKitVoice(true);await fetch("/api/auth/logout",{method:"POST"});router.push("/login?desktop=1");router.refresh()}finally{setBusy(null)}}

  if(loading&&!data)return <GrindPortalLoading variant="fullscreen" label="Abrindo GrindLobby Desktop"/>;

  const nav:[View,string,React.ReactNode][]=[["home","Início",<Home key="h"/>],["lobbies","Lobbies",<Gamepad2 key="l"/>],["community","Community",<Users key="c"/>],["friends","Amigos",<UserRound key="f"/>],["messages","Mensagens",<MessageCircle key="m"/>],["events","Eventos",<CalendarDays key="e"/>],["store","Loja",<Store key="s"/>],["settings","Configurações",<Settings key="g"/>]];

  return <main className="gl-desktop">
    <aside className="gl-sidebar">
      <div className="gl-brand"><img src="/brand/grindlobby-official.png" alt=""/><b>GRIND<span>LOBBY</span></b></div>
      <button className="gl-profile-mini" onClick={()=>selectView("profile")}><Avatar name={display} url={data?.account?.avatar}/><span><b>{display}</b><Status/><em>Nível {data?.account?.level??1}</em></span></button>
      <div className="gl-xp"><i style={{width:`${Math.min(100,((data?.account?.xp??0)/5000)*100)}%`}}/><small>{data?.account?.xp??0} / 5.000 XP</small></div>
      <nav>{nav.map(([id,label,icon])=><button key={id} className={view===id?"active":""} onClick={()=>selectView(id)}>{icon}<span>{label}</span></button>)}</nav>
      <div className="gl-side-spacer"/>
      <div className="gl-pro-card"><span>GRIND PRO</span><b>{isPro?"Ativo":"720p30 incluído"}</b><small>{isPro?"1080p60 + extras":"Upgrade para 1080p60"}</small></div>
      <button onClick={()=>void logout()} disabled={busy==="logout"}>Sair</button>
    </aside>

    <header className="gl-topbar"><div className="gl-search"><Search/><span>Buscar...</span><kbd>Ctrl K</kbd></div><div className="gl-top-actions"><button><Bell/></button><button onClick={()=>void load()}><RefreshCw/></button><button onClick={()=>selectView("profile")}><Avatar name={display} url={data?.account?.avatar}/></button></div></header>

    <section className="gl-stage">
      {view==="home"?<DashboardView display={display} data={data} friends={friendProfiles} current={current} lobbies={lobbies} busy={busy} openLobby={openLobby} selectView={selectView}/>:null}
      {view==="lobbies"?<LobbiesView lobbies={lobbies} busy={busy} openLobby={openLobby}/>:null}
      {view==="community"?<CommunityView onJoin={openLobby} lobbies={lobbies}/>:null}
      {view==="friends"?<FriendsView state={friends} reload={load}/>:null}
      {view==="messages"?<MessagesView friends={friendProfiles}/>:null}
      {view==="events"?<EventsView/>:null}
      {view==="store"?<div className="gl-store-wrap"><StoreShowcase display={display} isAdmin={isAdmin}/></div>:null}
      {view==="profile"?<ProfileView display={display} data={data}/>:null}
      {view==="settings"?<SettingsView isPro={isPro}/>:null}
    </section>

    <footer className="gl-player"><span className="gl-cover"><Music2/></span><span><b>Nenhuma música tocando</b><small>Use o player do GrindLobby para iniciar uma faixa.</small></span><div/><Volume2/><input aria-label="volume" type="range" defaultValue="70"/></footer>
    {error?<div className="gl-error">{error}</div>:null}
  </main>;
}

function DashboardView({display,data,friends,current,lobbies,busy,openLobby,selectView}:{display:string;data:DashboardData|null;friends:Player[];current:Lobby|null;lobbies:Lobby[];busy:string|null;openLobby:(l:Lobby)=>void;selectView:(v:View)=>void}){
  return <div className="gl-dashboard"><div className="gl-main-col">
    <div className="gl-welcome"><div><h1>Olá, <span>{display}.</span></h1><p>Pronto para mais uma sessão?</p></div><div><button className="primary" onClick={()=>selectView("lobbies")}><Plus/>Criar lobby</button><button onClick={()=>selectView("lobbies")}><Gamepad2/>Entrar em lobby</button></div></div>
    <div className="gl-feature-grid"><article><Headphones/><div><b>Voice & Chat</b><small>Entre em uma sala ativa para iniciar a call.</small></div><button disabled={!current} onClick={()=>current&&location.assign(`/lobby/${current.id}?desktop=1`)}>Entrar em call</button></article><article className="accent"><Video/><div><b>Transmitir</b><small>A transmissão fica disponível dentro de uma call ativa.</small></div><button disabled={!current} onClick={()=>current&&location.assign(`/lobby/${current.id}?desktop=1`)}>Abrir sala</button></article><article><Music2/><div><b>Música</b><small>Busque e reproduza faixas pelo player real.</small></div><button onClick={()=>selectView("home")}>Player</button></article></div>
    <div className="gl-section-head"><b>Lobbies recentes</b><button onClick={()=>selectView("lobbies")}>Ver todos</button></div>
    <div className="gl-lobby-list">{lobbies.length?lobbies.slice(0,4).map((l,i)=><article key={l.id}><span className={`game-mark g${i}`}>{initials(l.game?.name||l.name)}</span><span><b>{l.name}</b><small>{l.game?.name||"GrindLobby"} · {l.memberCount}/{l.max_members} jogadores</small></span><div/><button onClick={()=>openLobby(l)} disabled={busy===l.id}>Entrar</button></article>):<EmptyState title="Nenhum lobby aberto" text="Quando uma sala real estiver disponível, ela aparecerá aqui."/>}</div>
  </div><aside className="gl-right-col"><section><div className="gl-section-head"><b>Call ativa</b><MoreHorizontal/></div>{current?<><h3>{current.name}</h3><small>{current.memberCount}/{current.max_members} membros</small><button onClick={()=>location.assign(`/lobby/${current.id}?desktop=1`)}>Abrir call</button></>:<EmptyState title="Nenhuma call ativa" text="Entre em um lobby para iniciar voz ou transmissão."/>}</section><section><div className="gl-section-head"><b>Amigos</b><button onClick={()=>selectView("friends")}>Ver todos</button></div>{friends.length?friends.slice(0,4).map(f=><div className="friend-mini" key={f.id}><Avatar name={f.display_name||f.username} url={f.avatar}/><span><b>{f.display_name||f.username}</b><Status label={f.status||"offline"}/></span></div>):<EmptyState title="Nenhum amigo" text="Sua lista real de amigos aparecerá aqui."/>}</section><section><b>Online agora</b><small>{data?.stats?.online??0}</small></section></aside></div>
}

function LobbiesView({lobbies,busy,openLobby}:{lobbies:Lobby[];busy:string|null;openLobby:(l:Lobby)=>void}){return <div className="gl-page"><div className="gl-page-head"><div><h2>Lobbies</h2><p>Somente salas reais disponíveis no backend.</p></div></div><div className="gl-table">{lobbies.length?lobbies.map((l,i)=><div className="gl-table-row" key={l.id}><span className={`game-mark g${i}`}>{initials(l.game?.name||l.name)}</span><span><b>{l.name}</b><small>{l.game?.name||"Geral"} · {l.visibility}</small></span><span className="capacity">{l.memberCount}/{l.max_members}</span><button onClick={()=>openLobby(l)} disabled={busy===l.id}>Entrar</button></div>):<EmptyState title="Nenhum lobby encontrado" text="Crie uma sala ou aguarde novos lobbies públicos."/>}</div></div>}

function CommunityView({onJoin,lobbies}:{onJoin:(l:Lobby)=>void;lobbies:Lobby[]}){const[communities,setCommunities]=useState<Community[]>([]),[selected,setSelected]=useState<CommunityDetail|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{let live=true;(async()=>{const response=await fetch("/api/communities",{cache:"no-store"});if(!live)return;if(response.ok){const body=await response.json();const list=(body.communities??[]) as Community[];setCommunities(list);if(list[0]){const detail=await fetch(`/api/communities/${list[0].id}`,{cache:"no-store"});if(live&&detail.ok)setSelected(await detail.json() as CommunityDetail)}}setLoading(false)})();return()=>{live=false}},[]);if(loading)return <div className="gl-page"><EmptyState title="Carregando Communities" text="Buscando seus dados no backend."/></div>;if(!communities.length)return <div className="gl-page"><EmptyState title="Nenhuma Community" text="Você ainda não participa de uma Community."/></div>;const c=selected?.community??communities[0],members=selected?.members??[],events=selected?.events??[],environments=selected?.environments??[];return <div className="gl-page community"><div className="community-hero"><div className="community-logo">{initials(c.name)}</div><div><h2>{c.name}</h2><p>{c.description||"Sem descrição."}</p><span>{selected?.stats?.online??0} online · {selected?.stats?.members??c.memberCount??0} membros</span></div></div><div className="community-grid"><main><h3>Salas</h3>{environments.length?environments.map(env=><section className="channel-block" key={env.id}><div><span>{env.name}</span><small>{env.description||"Sala da Community"}</small><button disabled={!env.lobby_id} onClick={()=>{const lobby=lobbies.find(item=>String(item.id)===String(env.lobby_id));if(lobby)onJoin(lobby)}}>{env.lobby_id?"Entrar":"Offline"}</button></div></section>):<EmptyState title="Nenhuma sala configurada" text="As salas reais da Community aparecerão aqui."/>}</main><aside><section><h3>Eventos</h3>{events.length?events.slice(0,4).map(event=><div className="event-mini" key={event.id}><b>{event.title}</b><small>{new Date(event.starts_at).toLocaleString("pt-BR")}</small></div>):<EmptyState title="Sem eventos" text="Nenhum evento foi agendado."/>}</section><section><h3>Membros</h3>{members.length?members.slice(0,6).map(member=>{const p=member.profile;return <div className="friend-mini" key={member.user_id}><Avatar name={p?.display_name||p?.username||"Membro"} url={p?.avatar}/><span><b>{p?.display_name||p?.username||"Membro"}</b><Status label={p?.status||member.role}/></span></div>}):<EmptyState title="Sem membros carregados" text="Nenhum membro foi retornado agora."/>}</section></aside></div></div>}

function FriendsView({state,reload}:{state:FriendState;reload:()=>Promise<void>|void}){async function act(id:string,action:string){await fetch(`/api/friends/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});await reload()}return <div className="gl-page"><div className="gl-page-head"><div><h2>Amigos</h2><p>Dados reais da sua conta.</p></div></div><div className="friend-list">{state.friends.length?state.friends.map(item=>{const p=item.profile;const name=p?.display_name||p?.username||"Jogador";return <article key={item.id}><Avatar name={name} url={p?.avatar}/><span><b>{name}</b><Status label={p?.status||"offline"}/></span><button onClick={()=>void act(item.id,"remove")}>Remover</button></article>}):<EmptyState title="Nenhum amigo adicionado" text="Use a busca de jogadores para adicionar pessoas reais."/>}</div>{state.incoming.length?<><h3>Solicitações recebidas</h3><div className="friend-list">{state.incoming.map(item=><article key={item.id}><span>{item.profile?.display_name||item.profile?.username||"Jogador"}</span><button onClick={()=>void act(item.id,"accept")}>Aceitar</button><button onClick={()=>void act(item.id,"decline")}>Recusar</button></article>)}</div></>:null}</div>}

function MessagesView({friends}:{friends:Player[]}){const[selected,setSelected]=useState<Player|null>(friends[0]??null),[messages,setMessages]=useState<DirectMessage[]>([]),[draft,setDraft]=useState("");useEffect(()=>{setSelected(current=>current??friends[0]??null)},[friends]);useEffect(()=>{let live=true;if(!selected){setMessages([]);return()=>{live=false}};(async()=>{const response=await fetch(`/api/messages?with=${encodeURIComponent(selected.id)}&limit=80`,{cache:"no-store"});if(live&&response.ok){const body=await response.json();setMessages(body.messages??[])}})();return()=>{live=false}},[selected]);async function send(){const body=draft.trim();if(!body||!selected)return;const response=await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recipientId:selected.id,body})});if(response.ok){const result=await response.json();setMessages(items=>[...items,result.message]);setDraft("")}}if(!friends.length)return <div className="gl-page"><EmptyState title="Nenhuma conversa" text="Adicione um amigo para começar a conversar."/></div>;return <div className="gl-page messages"><aside>{friends.map(friend=><button className={selected?.id===friend.id?"active":""} key={friend.id} onClick={()=>setSelected(friend)}><Avatar name={friend.display_name||friend.username} url={friend.avatar}/><span><b>{friend.display_name||friend.username}</b><small>{friend.status||"offline"}</small></span></button>)}</aside><main>{selected?<><header><Avatar name={selected.display_name||selected.username} url={selected.avatar}/><span><b>{selected.display_name||selected.username}</b><Status label={selected.status||"offline"}/></span></header><div className="chat-log">{messages.length?messages.map(m=><div key={m.id} className={m.recipient_id===selected.id?"mine":""}><p>{m.body}</p><small>{new Date(m.created_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</small></div>):<EmptyState title="Sem mensagens" text="Esta conversa ainda não possui mensagens."/>}</div><div className="chat-input"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void send()} placeholder="Digite sua mensagem..."/><button onClick={()=>void send()}><Send/></button></div></>:null}</main></div>}

function EventsView(){const[events,setEvents]=useState<Array<{id:string;title:string;starts_at:string;communityName:string;type?:string}>>([]),[loading,setLoading]=useState(true);useEffect(()=>{let live=true;(async()=>{const response=await fetch("/api/communities",{cache:"no-store"});if(!response.ok){setLoading(false);return}const body=await response.json();const communities=(body.communities??[]) as Community[];const details=await Promise.all(communities.map(c=>fetch(`/api/communities/${c.id}`,{cache:"no-store"}).then(r=>r.ok?r.json():null)));if(!live)return;const merged:Array<{id:string;title:string;starts_at:string;communityName:string;type?:string}>=[];details.forEach((detail,index)=>{(detail?.events??[]).forEach((event:{id:string;title:string;starts_at:string;type?:string})=>merged.push({...event,communityName:communities[index].name}))});merged.sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime());setEvents(merged);setLoading(false)})();return()=>{live=false}},[]);return <div className="gl-page"><div className="gl-page-head"><div><h2>Eventos</h2><p>Agenda real das suas Communities.</p></div></div>{loading?<EmptyState title="Carregando eventos" text="Buscando agenda no backend."/>:events.length?<div className="event-list large">{events.map(event=><article key={event.id}><span className="datebox">{new Date(event.starts_at).toLocaleDateString("pt-BR",{day:"2-digit",month:"short"})}</span><span><b>{event.title}</b><small>{event.communityName} · {new Date(event.starts_at).toLocaleString("pt-BR")}</small></span></article>)}</div>:<EmptyState title="Nenhum evento agendado" text="Quando uma Community criar um evento ele aparecerá aqui."/>}</div>}

function ProfileView({display,data}:{display:string;data:DashboardData|null}){return <div className="gl-page profile-page"><div className="profile-banner" style={data?.account?.banner?{backgroundImage:`url(${data.account.banner})`}:undefined}><div className="profile-avatar"><Avatar lg name={display} url={data?.account?.avatar}/></div></div><div className="profile-info"><h2>{display}</h2><p>@{data?.account?.username||""}</p><div className="gl-xp big"><i style={{width:`${Math.min(100,((data?.account?.xp??0)/5000)*100)}%`}}/><small>Nível {data?.account?.level??1} · {data?.account?.xp??0}/5.000 XP</small></div></div></div>}
function SettingsView({isPro}:{isPro:boolean}){return <div className="gl-page settings-page"><main><h2>Configurações</h2><section><h3>Transmissão</h3><p>{isPro?"Até 1080p 60fps":"Até 720p 30fps"}</p></section></main></div>}
