"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {Bell,CalendarDays,ChevronRight,Gamepad2,Headphones,Home,LogOut,MessageCircle,Mic,MicOff,MoreHorizontal,Music2,Plus,RefreshCw,Search,Send,Settings,ShoppingBag,Store,Trophy,UserPlus,UserRound,Users,Video,Volume2} from "lucide-react";
import GrindPortalLoading from "@/components/feedback/GrindPortalLoading";
import StoreShowcase from "@/components/dashboard/StoreShowcase";
import {disconnectActiveLiveKitVoice} from "@/lib/webrtc/useLobbyVoice";

type DesktopUser={id:string;username:string;display_name:string;email?:string;account_tier?:string;app_role?:string};
type Player={id:string;username:string;display_name:string;avatar:string|null;status?:string};
type Lobby={id:string;owner_id:string;name:string;visibility:string;max_members:number;status:string;memberCount:number;joined:boolean;game?:{name:string;slug:string}|null;owner?:Player|null;members?:Array<{userId:string;profile?:Player|null}>};
type DashboardData={lobbies:Lobby[];currentLobby:Lobby|null;online:Array<Player&{player?:unknown}>;topPlayers:unknown[];account:{username:string;displayName:string;level:number;xp:number;avatar:string|null;banner:string|null;frame:string|null;effect:string|null;badge:string|null;cardStyle:string|null};entitlements:{tier:"free"|"pro";isAdmin:boolean};stats:{online:number;activeLobbies:number;myLobbies:number;rank:number};games:Array<{id:number;name:string;slug:string;rank:string;points:number}>};
type View="home"|"lobbies"|"community"|"friends"|"messages"|"tournaments"|"events"|"store"|"profile"|"settings";

const fallbackFriends=["ShadowZ","KillerBee","Luna","Rafa","GuiZin"];
const convoSeed=[{who:"ShadowZ",text:"Eae, bora jogar mais tarde?",mine:false},{who:"Você",text:"Bora sim! Chama geral 👀",mine:true},{who:"ShadowZ",text:"Fechou, te aviso quando entrar.",mine:false}];

function initials(value:string){return value.trim().split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase()||"GL"}
function Avatar({name,url,lg=false}:{name:string;url?:string|null;lg?:boolean}){return <span className={`gl-avatar${lg?" lg":""}`}>{url?<img src={url} alt=""/>:initials(name)}</span>}
function Status({label="Online"}:{label?:string}){return <small className="gl-status"><i/>{label}</small>}

export default function DesktopHome({user,initialView="home"}:{user:DesktopUser;initialView?:View}){
  const router=useRouter();
  const [data,setData]=useState<DashboardData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState<string|null>(null),[view,setView]=useState<View>(initialView);
  const [muted,setMuted]=useState(false),[deafened,setDeafened]=useState(false),[messages,setMessages]=useState(convoSeed),[draft,setDraft]=useState("");
  const load=useCallback(async()=>{try{const response=await fetch("/api/dashboard",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Falha ao carregar o desktop.");setData(body as DashboardData);setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Falha ao carregar o desktop.")}finally{setLoading(false)}},[]);
  useEffect(()=>{const start=window.setTimeout(()=>void load(),0),timer=window.setInterval(()=>void load(),20_000);return()=>{window.clearTimeout(start);window.clearInterval(timer)}},[load]);

  const display=data?.account?.displayName||user.display_name||user.username;
  const online=data?.online??[];
  const lobbies=useMemo(()=>data?.lobbies?.filter(item=>item.status==="open").slice(0,8)??[],[data?.lobbies]);
  const current=data?.currentLobby??null,isAdmin=Boolean(data?.entitlements?.isAdmin),isPro=isAdmin||data?.entitlements?.tier==="pro";
  const selectView=(next:View)=>{setView(next);router.replace(`/?desktop=1&view=${next}`)};
  const route=(path:string)=>router.push(`${path}${path.includes("?")?"&":"?"}desktop=1`);
  async function openLobby(lobby:Lobby){setBusy(lobby.id);try{if(!lobby.joined){const response=await fetch(`/api/lobbies/${lobby.id}/join`,{method:"POST"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Não foi possível entrar.")}route(`/lobby/${lobby.id}`)}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível entrar.")}finally{setBusy(null)}}
  async function logout(){setBusy("logout");try{await disconnectActiveLiveKitVoice(true);await fetch("/api/auth/logout",{method:"POST"});router.push("/login?desktop=1");router.refresh()}finally{setBusy(null)}}
  function sendMessage(){const text=draft.trim();if(!text)return;setMessages(items=>[...items,{who:"Você",text,mine:true}]);setDraft("")}

  if(loading&&!data)return <GrindPortalLoading variant="fullscreen" label="Abrindo GrindLobby Desktop"/>;

  const friends=(online.length?online.map(p=>p.display_name||p.username):fallbackFriends).slice(0,7);
  const nav:[View,string,React.ReactNode][]=[["home","Início",<Home key="h"/>],["lobbies","Lobbies",<Gamepad2 key="l"/>],["community","Community",<Users key="c"/>],["friends","Amigos",<UserRound key="f"/>],["messages","Mensagens",<MessageCircle key="m"/>],["tournaments","Torneios",<Trophy key="t"/>],["events","Eventos",<CalendarDays key="e"/>],["store","Loja",<Store key="s"/>],["settings","Configurações",<Settings key="g"/>]];

  return <main className="gl-desktop">
    <aside className="gl-sidebar">
      <div className="gl-brand"><img src="/brand/grindlobby-official.png" alt=""/><b>GRIND<span>LOBBY</span></b></div>
      <button className="gl-profile-mini" onClick={()=>selectView("profile")}><Avatar name={display} url={data?.account?.avatar}/><span><b>{display}</b><Status/><em>Nível {data?.account?.level??18}</em></span></button>
      <div className="gl-xp"><i style={{width:`${Math.min(100,((data?.account?.xp??2450)/5000)*100)}%`}}/><small>{data?.account?.xp??2450} / 5.000 XP</small></div>
      <nav>{nav.map(([id,label,icon])=><button key={id} className={view===id?"active":""} onClick={()=>selectView(id)}>{icon}<span>{label}</span>{id==="messages"?<b>3</b>:null}</button>)}</nav>
      <div className="gl-side-spacer"/>
      <div className="gl-pro-card"><span>GRIND PRO</span><b>{isPro?"Ativo":"720p30 incluído"}</b><small>{isPro?"1080p60 + extras":"Upgrade para 1080p60"}</small></div>
    </aside>

    <header className="gl-topbar"><div className="gl-search"><Search/><span>Buscar...</span><kbd>Ctrl K</kbd></div><div className="gl-top-actions"><button><Bell/></button><button onClick={()=>void load()}><RefreshCw/></button><button onClick={()=>selectView("profile")}><Avatar name={display} url={data?.account?.avatar}/></button></div></header>

    <section className="gl-stage">
      {view==="home"?<DashboardView display={display} data={data} friends={friends} current={current} lobbies={lobbies} busy={busy} openLobby={openLobby} muted={muted} setMuted={setMuted} deafened={deafened} setDeafened={setDeafened} selectView={selectView}/>:null}
      {view==="lobbies"?<LobbiesView lobbies={lobbies} busy={busy} openLobby={openLobby}/>:null}
      {view==="community"?<CommunityView friends={friends}/>:null}
      {view==="friends"?<FriendsView friends={friends}/>:null}
      {view==="messages"?<MessagesView friends={friends} messages={messages} draft={draft} setDraft={setDraft} sendMessage={sendMessage}/>:null}
      {view==="tournaments"?<TournamentsView/>:null}
      {view==="events"?<EventsView/>:null}
      {view==="store"?<div className="gl-store-wrap"><StoreShowcase display={display} isAdmin={isAdmin}/></div>:null}
      {view==="profile"?<ProfileView display={display} data={data}/>:null}
      {view==="settings"?<SettingsView isPro={isPro}/>:null}
    </section>

    <footer className="gl-player"><span className="gl-cover">A7X</span><span><b>Afterlife</b><small>Avenged Sevenfold</small></span><div className="gl-player-controls"><button>◀</button><button className="play">Ⅱ</button><button>▶</button></div><Volume2/><input aria-label="volume" type="range" defaultValue="70"/></footer>
    {error?<div className="gl-error">{error}</div>:null}
  </main>;
}

function DashboardView({display,data,friends,current,lobbies,busy,openLobby,muted,setMuted,deafened,setDeafened,selectView}:{display:string;data:DashboardData|null;friends:string[];current:Lobby|null;lobbies:Lobby[];busy:string|null;openLobby:(l:Lobby)=>void;muted:boolean;setMuted:(v:boolean)=>void;deafened:boolean;setDeafened:(v:boolean)=>void;selectView:(v:View)=>void}){
  return <div className="gl-dashboard">
    <div className="gl-main-col">
      <div className="gl-welcome"><div><h1>Boa noite, <span>{display}.</span></h1><p>Pronto para mais uma sessão?</p></div><div><button className="primary" onClick={()=>selectView("lobbies")}><Plus/>Criar lobby</button><button onClick={()=>selectView("lobbies")}><Gamepad2/>Entrar em lobby</button></div></div>
      <div className="gl-feature-grid"><article><Headphones/><div><b>Voice & Chat</b><small>Conecte-se com seu time com qualidade máxima.</small></div><button onClick={()=>current&&location.assign(`/lobby/${current.id}?desktop=1`)}>Entrar em call</button></article><article className="accent"><Video/><div><b>Transmitir</b><small>Compartilhe sua tela com baixa latência.</small></div><span className="pill">1080p 60fps</span><button>Iniciar transmissão</button></article><article><Music2/><div><b>Música</b><small>Ouça suas playlists sem sair do jogo.</small></div><button>Abrir player</button></article></div>
      <div className="gl-section-head"><b>Lobbies recentes</b><button onClick={()=>selectView("lobbies")}>Ver todos</button></div>
      <div className="gl-lobby-list">{lobbies.slice(0,4).map((l,i)=><article key={l.id}><span className={`game-mark g${i}`}>{initials(l.game?.name||l.name)}</span><span><b>{l.name}</b><small>{l.game?.name||"GrindLobby"} · {l.memberCount}/{l.max_members} jogadores</small></span><div className="gl-avatars">{Array.from({length:Math.min(5,l.memberCount||2)},(_,x)=><i key={x}>{x+1}</i>)}</div><button onClick={()=>openLobby(l)} disabled={busy===l.id}>Entrar</button></article>)}{!lobbies.length?<article><span className="game-mark">GL</span><span><b>Resenha Geral</b><small>5/10 jogadores</small></span><div/><button>Entrar</button></article>:null}</div>
      <div className="gl-tourney-banner"><div><small>TORNEIO EM DESTAQUE</small><h3>Copa GrindLobby</h3><span>32 equipes · R$ 5.000,00 · Inscrições abertas</span></div><button onClick={()=>selectView("tournaments")}>Ver detalhes</button></div>
    </div>
    <aside className="gl-right-col"><section><div className="gl-section-head"><b>Atividade</b><button>Ver tudo</button></div><ul className="activity"><li><i/>KillerBee entrou em 5v5 Competitivo <small>Agora</small></li><li><i/>ShadowZ iniciou uma transmissão <small>2 min</small></li><li><i/>Luna enviou uma mensagem <small>5 min</small></li></ul></section><section><div className="gl-section-head"><b>Call ativa</b><MoreHorizontal/></div><h3>{current?.name||"5v5 Competitivo"}</h3><small className="call-time">00:24:16</small>{friends.slice(0,5).map((f,i)=><div className="call-person" key={f}><Avatar name={f}/><span>{f}</span>{i<3?<Mic/>:<MicOff/>}</div>)}<div className="call-controls"><button onClick={()=>setMuted(!muted)} className={muted?"danger":""}>{muted?<MicOff/>:<Mic/>}</button><button onClick={()=>setDeafened(!deafened)} className={deafened?"danger":""}><Headphones/></button><button><Video/></button><button className="hang">●</button></div></section><section><div className="gl-section-head"><b>Amigos online</b><button onClick={()=>selectView("friends")}>Ver todos</button></div>{friends.slice(0,4).map(f=><div className="friend-mini" key={f}><Avatar name={f}/><span><b>{f}</b><Status label="Em lobby"/></span></div>)}</section></aside>
  </div>
}

function LobbiesView({lobbies,busy,openLobby}:{lobbies:Lobby[];busy:string|null;openLobby:(l:Lobby)=>void}){const rows=lobbies.length?lobbies:[{id:"demo1",owner_id:"",name:"5v5 Competitivo",visibility:"public",max_members:10,status:"open",memberCount:7,joined:false,game:{name:"VALORANT",slug:"valorant"}},{id:"demo2",owner_id:"",name:"Resenha da madrugada",visibility:"public",max_members:10,status:"open",memberCount:6,joined:false,game:{name:"Geral",slug:"geral"}}] as Lobby[];return <div className="gl-page"><div className="gl-page-head"><div><h2>Lobbies</h2><p>Encontre uma sala ou crie a sua.</p></div><button className="primary"><Plus/>Criar lobby</button></div><div className="gl-toolbar"><div className="gl-search wide"><Search/><span>Buscar lobbies...</span></div><button className="active">Todos</button><button>Públicos</button><button>Privados</button><button>Meus lobbies</button></div><div className="gl-table">{rows.map((l,i)=><div className="gl-table-row" key={l.id}><span className={`game-mark g${i}`}>{initials(l.game?.name||l.name)}</span><span><b>{l.name}</b><small>{l.game?.name||"Geral"} · {l.visibility}</small></span><div className="gl-avatars">{[1,2,3,4].map(x=><i key={x}>{x}</i>)}</div><span className="capacity">{l.memberCount}/{l.max_members}</span><span className="ping">● 12 ms</span><button onClick={()=>!l.id.startsWith("demo")&&openLobby(l)} disabled={busy===l.id}>Entrar</button></div>)}</div></div>}

function CommunityView({friends}:{friends:string[]}){return <div className="gl-page community"><div className="community-hero"><div className="community-logo">G</div><div><h2>GrindHouse ✓</h2><p>Comunidade oficial do GrindLobby.</p><span>● 1.842 online &nbsp;·&nbsp; 8.753 membros</span></div><button className="primary"><UserPlus/>Convidar</button><button><MoreHorizontal/></button></div><div className="community-tabs"><button className="active">Visão geral</button><button>Canais</button><button>Eventos</button><button>Membros</button><button>Configurações</button></div><div className="community-grid"><main><h3>Canais</h3>{[["BEM-VINDO",["# regras","# anúncios"]],["GERAL",["# chat-geral","🔊 Sala Geral"]],["JOGOS",["# valorant","# cs2","# lol"]],["MÍDIA",["# clipes","# memes"]]].map(([cat,items])=><section className="channel-block" key={cat as string}><b>{cat as string}</b>{(items as string[]).map((x,i)=><div className={x.includes("Sala")?"voice":""} key={x}><span>{x}</span><small>{x.includes("Sala")?"24/30 · ":""}{i?"3 min atrás":"Agora"}</small></div>)}</section>)}</main><aside><section><h3>Sobre a comunidade</h3><p>Participe de discussões, encontre novos players e fique por dentro de tudo.</p></section><section><h3>Eventos próximos</h3><div className="event-mini"><b>Copa GrindLobby</b><small>24 de Mai · 19:00</small></div><div className="event-mini"><b>Scrim Volo</b><small>Amanhã · 20:30</small></div></section><section><h3>Membros online</h3>{friends.slice(0,6).map(f=><div className="friend-mini" key={f}><Avatar name={f}/><span><b>{f}</b><Status/></span></div>)}</section></aside></div></div>}

function FriendsView({friends}:{friends:string[]}){return <div className="gl-page"><div className="gl-page-head"><div><h2>Amigos</h2><p>Veja quem está online e entre na resenha.</p></div><button className="primary"><UserPlus/>Adicionar amigo</button></div><div className="gl-toolbar"><button className="active">Todos</button><button>Online</button><button>Em jogo</button><button>Pendentes</button><button>Bloqueados</button></div><div className="friend-list">{friends.concat(["Mika","Voxzera"]).map((f,i)=><article key={f}><Avatar name={f}/><span><b>{f}</b><Status label={i%3===0?"Em lobby":i%3===1?"Jogando VALORANT":"Online"}/></span><button><MessageCircle/></button><button><MoreHorizontal/></button></article>)}</div></div>}

function MessagesView({friends,messages,draft,setDraft,sendMessage}:{friends:string[];messages:{who:string;text:string;mine:boolean}[];draft:string;setDraft:(v:string)=>void;sendMessage:()=>void}){return <div className="gl-page messages"><aside><div className="gl-search wide"><Search/><span>Buscar...</span></div>{friends.slice(0,6).map((f,i)=><button className={i===0?"active":""} key={f}><Avatar name={f}/><span><b>{f}</b><small>{i===0?"Bora jogar mais tarde?":"Online"}</small></span></button>)}</aside><main><header><Avatar name={friends[0]||"ShadowZ"}/><span><b>{friends[0]||"ShadowZ"}</b><Status/></span><button><Video/></button><button><Headphones/></button></header><div className="chat-log">{messages.map((m,i)=><div key={i} className={m.mine?"mine":""}><small>{m.who}</small><p>{m.text}</p></div>)}</div><div className="chat-input"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&sendMessage()} placeholder="Digite sua mensagem..."/><button onClick={sendMessage}><Send/></button></div></main></div>}

function TournamentsView(){return <div className="gl-page"><div className="gl-page-head"><div><h2>Torneios</h2><p>Competições e eventos da comunidade.</p></div></div><div className="tourney-hero"><div><small>EM DESTAQUE</small><h2>Copa GrindLobby</h2><p>32 equipes · R$ 5.000,00</p><button className="primary">Inscrever-se</button></div><Trophy/></div><div className="gl-section-head"><b>Próximos torneios</b><button>Ver todos</button></div><div className="event-list">{[["Scrim Valorant","16 equipes · Amanhã 20:00"],["Campeonato CS2","64 equipes · 24 de Mai 19:00"],["Dupla League of Legends","32 equipes · 27 de Mai 18:00"]].map(([a,b])=><article key={a}><Trophy/><span><b>{a}</b><small>{b}</small></span><button>Inscrever-se</button></article>)}</div></div>}
function EventsView(){return <div className="gl-page"><div className="gl-page-head"><div><h2>Eventos</h2><p>Agenda da comunidade e sessões especiais.</p></div></div><div className="event-list large">{[["Copa GrindLobby","24 MAI","32 equipes · R$ 5.000,00"],["Noite de Resenha","28 MAI","Evento casual · Premiação surpresa"],["Treino Comunitário","30 MAI","Com a staff do GrindLobby"]].map(([a,d,b])=><article key={a}><span className="datebox">{d}</span><span><b>{a}</b><small>{b}</small></span><button>Participar</button></article>)}</div></div>}
function ProfileView({display,data}:{display:string;data:DashboardData|null}){return <div className="gl-page profile-page"><div className="profile-banner"><div className="profile-avatar"><Avatar lg name={display} url={data?.account?.avatar}/></div></div><div className="profile-info"><h2>{display} ✓</h2><p>@{data?.account?.username||"nightfury"} · Brasil</p><div className="gl-xp big"><i style={{width:"49%"}}/><small>Nível {data?.account?.level??18} · {data?.account?.xp??2450}/5.000 XP</small></div><button className="primary">Editar perfil</button></div><div className="profile-stats"><article><b>127</b><small>Lobbies criados</small></article><article><b>32</b><small>Torneios</small></article><article><b>86</b><small>Amigos</small></article><article><b>256h</b><small>Tempo em call</small></article></div><div className="achievements"><h3>Conquistas recentes</h3>{["◇","✦","⬢","✹","◆"].map((x,i)=><span key={i}>{x}</span>)}</div></div>}
function SettingsView({isPro}:{isPro:boolean}){return <div className="gl-page settings-page"><aside>{["Geral","Conta","Privacidade","Notificações","Voz & Vídeo","Transmissão","Aparência","Atalhos","Sobre"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</aside><main><h2>Configurações</h2><section><h3>Geral</h3><label>Idioma <select defaultValue="pt"><option value="pt">Português (Brasil)</option></select></label><label>Tema <select defaultValue="dark"><option value="dark">Escuro</option></select></label><label>Iniciar com o Windows <input type="checkbox" defaultChecked/></label><label>Minimizar para a bandeja <input type="checkbox" defaultChecked/></label></section><section><h3>Voz & Vídeo</h3><label>Volume de entrada <input type="range" defaultValue="78"/></label><label>Redução de ruído <input type="checkbox" defaultChecked/></label><label>Cancelamento de eco <input type="checkbox" defaultChecked/></label><label>Ganho automático <input type="checkbox" defaultChecked/></label></section><section><h3>Transmissão</h3><p>{isPro?"Até 1080p 60fps":"Até 720p 30fps"}</p></section></main></div>}
