-- GrindLobby v2 - Supabase production foundation
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[A-Za-z0-9_]{3,24}$'),
  email text not null,
  display_name text not null check (char_length(display_name) between 2 and 40),
  avatar text,
  status text not null default 'offline' check (status in ('online','idle','dnd','offline')),
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_username_lower_uidx on public.profiles(lower(username));
create unique index if not exists profiles_email_lower_uidx on public.profiles(lower(email));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, username, email, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'username', 'Player')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique
);

insert into public.games(name, slug) values
 ('EA FC 27','ea-fc-27'),
 ('Valorant','valorant'),
 ('Rocket League','rocket-league'),
 ('Fortnite','fortnite'),
 ('Counter-Strike 2','counter-strike-2')
on conflict (slug) do nothing;

create table if not exists public.user_game_ranks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  game_id bigint not null references public.games(id) on delete cascade,
  rank_name text not null,
  points integer not null default 0 check (points >= 0),
  wins integer not null default 0 check (wins >= 0),
  losses integer not null default 0 check (losses >= 0),
  updated_at timestamptz not null default now(),
  unique(user_id, game_id)
);

create index if not exists user_game_ranks_user_idx on public.user_game_ranks(user_id);

create table if not exists public.lobbies (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  game_id bigint references public.games(id) on delete set null,
  name text not null check (char_length(name) between 2 and 80),
  description text,
  visibility text not null default 'public' check (visibility in ('public','private','friends')),
  max_members integer not null default 5 check (max_members between 2 and 100),
  status text not null default 'open' check (status in ('open','full','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lobbies_owner_idx on public.lobbies(owner_id);
create index if not exists lobbies_status_idx on public.lobbies(status);

create table if not exists public.lobby_members (
  lobby_id uuid not null references public.lobbies(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','moderator','member')),
  joined_at timestamptz not null default now(),
  primary key(lobby_id, user_id)
);

create index if not exists lobby_members_user_idx on public.lobby_members(user_id);

alter table public.profiles enable row level security;
alter table public.games enable row level security;
alter table public.user_game_ranks enable row level security;
alter table public.lobbies enable row level security;
alter table public.lobby_members enable row level security;

create policy "users view own profile"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

create or replace view public.public_profiles
with (security_invoker = true)
as select id, username, display_name, avatar, status, last_seen_at, created_at
from public.profiles;

create policy "users update own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "games readable by everyone"
on public.games for select
to anon, authenticated
using (true);

create policy "ranks readable by authenticated users"
on public.user_game_ranks for select
to authenticated
using (true);

create policy "users manage own ranks"
on public.user_game_ranks for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "users update own ranks"
on public.user_game_ranks for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "open lobbies readable by authenticated users"
on public.lobbies for select
to authenticated
using (visibility = 'public' or owner_id = (select auth.uid()));

create policy "users create own lobbies"
on public.lobbies for insert
to authenticated
with check (owner_id = (select auth.uid()));

create policy "owners update lobbies"
on public.lobbies for update
to authenticated
using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));

create policy "owners delete lobbies"
on public.lobbies for delete
to authenticated
using (owner_id = (select auth.uid()));

create policy "members can view memberships"
on public.lobby_members for select
to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1 from public.lobbies l
    where l.id = lobby_id and (l.visibility = 'public' or l.owner_id = (select auth.uid()))
  )
);

create policy "users join lobbies as themselves"
on public.lobby_members for insert
to authenticated
with check (user_id = (select auth.uid()));

create policy "users leave lobby"
on public.lobby_members for delete
to authenticated
using (
  user_id = (select auth.uid())
  or exists (select 1 from public.lobbies l where l.id = lobby_id and l.owner_id = (select auth.uid()))
);
