"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {Home,Gamepad2,Trophy,Users,Radio,Settings,Search,Bell,Plus,Activity,Crown,LogOut,Mic2,MonitorUp,ShieldCheck,Sparkles,ChevronRight,Zap} from "lucide-react";

const games=[{name:"EA FC 27",rank:"Division 2",pts:"1.842",p:72,tag:"FC"},{name:"Valorant",rank:"Diamond 2",pts:"487",p:61,tag:"V"},{name:"Rocket League",rank:"Champion II",pts:"1.184",p:84,tag:"RL"}];
const lobbies=[{name:"Night Grind",game:"EA FC 27",mode:"Pro Clubs",slots:"8/11",ping:"12ms"},{name:"Ranked Squad",game:"Valorant",mode:"Competitive",slots:"4/5",ping:"18ms"},{name:"Late Night",game:"Rocket League",mode:"2v2",slots:"3/4",ping:"9ms"}];

export default function Dashboard({user}:{user:any}){
 const [create,setCreate]=useState(false); const router=useRouter();
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.push("/login");router.refresh()}
 const display=user.display_name||user.username||"Player";
 return <main className="app-shell min-h-screen text-white"><div className="ambient a1"/><div className="ambient a2"/><div className="relative flex min-h-screen">
  <aside className="sidebar hidden w-[268px] shrink-0 lg:flex lg:flex-col">
   <div className="brand"><div className="brand-mark">G</div><div><b>GRIND<span>LOBBY</span></b><small>COMPETITIVE NETWORK</small></div></div>
   <div className="nav-label">NETWORK</div><nav className="space-y-1">{[[Home,"Overview"],[Gamepad2,"Games"],[Trophy,"Rankings"],[Users,"Lobbies"],[Radio,"Live"]].map(([I,l],i:any)=><button key={l as string} className={`nav-item ${i===0?"active":""}`}><I size={18}/>{l as string}{i===3&&<em>42</em>}</button>)}</nav>
   <div className="pro-card"><div><Zap size={14}/> GRIND PRO</div><p>1080p 60fps, perfil premium e recursos competitivos.</p><button>Ver benefícios →</button></div>
   <div className="mt-auto"><button className="nav-item"><Settings size={18}/>Settings</button><button onClick={logout} className="nav-item"><LogOut size={18}/>Sair</button><div className="profile-mini"><div className="avatar">{display.slice(0,2).toUpperCase()}<i/></div><div><b>{display}</b><span>Online agora</span></div></div></div>
  </aside>
  <section className="min-w-0 flex-1"><header className="topbar"><div className="lg:hidden font-black">GRIND<span className="text-violet-400">LOBBY</span></div><div className="search"><Search size={16}/><input placeholder="Buscar players, jogos, lobbies..."/></div><button className="icon-btn"><Bell size={18}/><i/></button><button onClick={()=>setCreate(true)} className="primary hidden sm:flex"><Plus size={17}/> Criar lobby</button></header>
   <div className="mx-auto max-w-[1540px] p-4 pb-24 lg:p-8">
    <section className="hero"><div className="gridfx"/><div className="glow"/><div className="relative z-10 max-w-2xl"><div className="eyebrow"><Activity size={13}/> SESSION READY · 18 FRIENDS ONLINE</div><h1>YOUR NEXT<br/><span>GRIND STARTS HERE.</span></h1><p>Monte sua squad, encontre partidas no seu nível e entre em voz sem sair do fluxo. Uma central competitiva feita para jogar.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>setCreate(true)} className="primary"><Plus size={17}/> Criar lobby</button><button className="secondary"><Users size={17}/> Encontrar squad</button></div></div><div className="hero-status hidden xl:block"><small>NETWORK STATUS</small><b><i/> ALL SYSTEMS READY</b><div><span>VOICE</span><strong>LOW LATENCY</strong></div><div><span>STREAM</span><strong>1080P · 60FPS PRO</strong></div></div></section>
    <section className="stats">{[[Users,"18","Amigos online","+4 hoje"],[Gamepad2,"42","Lobbies ativos","12 no seu rank"],[Radio,"7","Ao vivo","3 amigos"],[Trophy,"#284","Seu ranking","Top 8%"]].map(([I,v,l,s]:any)=><div className="stat" key={l}><div className="stat-icon"><I size={18}/></div><div><small>{l}</small><b>{v}</b><span>{s}</span></div></div>)}</section>
    <div className="content"><div className="min-w-0"><div className="section-head"><div><small>COMPETITIVE IDENTITY</small><h2>Seus jogos</h2></div><button>Gerenciar <ChevronRight size={14}/></button></div><div className="game-grid">{games.map(g=><article className="game" key={g.name}><div className="game-top"><div className="game-logo">{g.tag}</div><span>RANKED</span></div><h3>{g.name}</h3><p>{g.rank}</p><div className="points"><b>{g.pts}</b><small>GRIND PTS</small></div><div className="progress"><i style={{width:`${g.p}%`}}/></div><div className="progress-label"><span>Próximo nível</span><b>{g.p}%</b></div></article>)}</div>
     <div className="section-head mt-9"><div><small>PLAY NOW</small><h2>Lobbies recomendados</h2></div><button>Ver todos <ChevronRight size={14}/></button></div><div className="lobby-list">{lobbies.map((l,i)=><article className="lobby" key={l.name}><div className="lobby-logo"><Gamepad2 size={19}/></div><div className="lobby-main"><div className="flex items-center gap-2"><h3>{l.name}</h3>{i===0&&<span className="hot">HOT</span>}</div><p>{l.game} · {l.mode}</p></div><div className="lobby-meta hidden md:flex"><span><Mic2 size={14}/> Voice ready</span><span><MonitorUp size={14}/> {l.ping}</span></div><div className="slots"><small>PLAYERS</small><b>{l.slots}</b></div><button className="join">Entrar</button></article>)}</div></div>
     <aside className="rail"><div className="profile-card"><div className="cover"/><div className="big-avatar">{display.slice(0,2).toUpperCase()}<i/></div><div className="mt-11"><div className="flex justify-between"><div><h3>{display}</h3><p>@{user.username}</p></div><Crown size={18} className="text-violet-300"/></div><div className="profile-stats"><div><b>284</b><span>GLOBAL</span></div><div><b>1.8K</b><span>POINTS</span></div><div><b>63%</b><span>WIN RATE</span></div></div><div className="verified"><ShieldCheck size={16}/><div><b>Grinder verificado</b><span>Conta protegida e pronta</span></div></div></div></div><div className="friends"><div className="flex justify-between"><div><small>SQUAD</small><h3>Online agora</h3></div><span>18</span></div>{["Nox","Mika","Rafa","Zed"].map((n,i)=><div className="friend" key={n}><div className="friend-avatar">{n[0]}<i/></div><div><b>{n}</b><span>{i%2?"Valorant · Ranked":"EA FC 27 · Lobby"}</span></div><button>+</button></div>)}</div></aside></div>
   </div></section></div>
  {create&&<div className="modal-bg"><div className="modal"><div className="modal-head"><div><div className="eyebrow"><Sparkles size={13}/> QUICK CREATE</div><h2>Criar novo lobby</h2><p>Configure a sessão e chame sua squad.</p></div><button onClick={()=>setCreate(false)}>✕</button></div><div className="modal-fields">{["JOGO · EA FC 27","MODO · Pro Clubs","VAGAS · 11","PRIVACIDADE · Público"].map(x=><div key={x}>{x}</div>)}</div><button onClick={()=>setCreate(false)} className="primary mt-6 w-full justify-center">Criar lobby</button></div></div>}
 </main>
}
