"use client";
import {useState} from "react"; import {useRouter} from "next/navigation";
import {Home,Gamepad2,Trophy,Users,Radio,Settings,Search,Bell,Plus,Activity,Crown,LogOut} from "lucide-react";
export default function Dashboard({user}:{user:any}){
 const [create,setCreate]=useState(false); const router=useRouter();
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.push("/login");router.refresh()}
 const games=[["EA FC 27","Division 2","1.842",72],["Valorant","Diamond 2","487",61],["Rocket League","Champion II","1.184",84]];
 return <main className="min-h-screen bg-[#07080b] text-white"><div className="flex min-h-screen">
 <aside className="hidden w-64 shrink-0 border-r border-white/[.06] bg-[#0b0d12] p-4 lg:flex lg:flex-col"><div className="mb-8 flex items-center gap-3 px-2"><div className="grid h-10 w-10 place-items-center rounded-xl bg-violet-600 font-black">G</div><div><b>GRIND<span className="text-violet-400">LOBBY</span></b><div className="text-[10px] uppercase tracking-[.25em] text-zinc-500">gaming network</div></div></div><nav className="space-y-1">{[[Home,"Home"],[Gamepad2,"Games"],[Trophy,"Rankings"],[Users,"Lobbies"],[Radio,"Live"]].map(([I,l])=><button key={l as string} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm text-zinc-400 hover:bg-white/[.04] hover:text-white"><I size={18}/>{l as string}</button>)}</nav><div className="mt-auto"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm text-zinc-400"><Settings size={18}/>Settings</button><button onClick={logout} className="mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm text-zinc-400 hover:text-red-300"><LogOut size={18}/>Sair</button><div className="mt-3 flex items-center gap-3 rounded-2xl border border-white/[.06] bg-white/[.025] p-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-violet-600 text-xs font-bold">{(user.display_name||user.username).slice(0,2).toUpperCase()}</div><div><div className="text-sm font-semibold">{user.display_name}</div><div className="text-xs text-emerald-400">Online</div></div></div></div></aside>
 <section className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-16 items-center gap-4 border-b border-white/[.06] bg-[#07080b]/90 px-4 backdrop-blur-xl lg:px-8"><div className="lg:hidden font-black">GRIND<span className="text-violet-400">LOBBY</span></div><div className="relative max-w-xl flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-600" size={17}/><input placeholder="Buscar jogadores, jogos ou lobbies..." className="field pl-10"/></div><Bell size={19} className="text-zinc-400"/><button onClick={()=>setCreate(true)} className="hidden items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold sm:flex"><Plus size={17}/>Criar Lobby</button></header>
 <div className="mx-auto max-w-[1500px] p-4 pb-24 lg:p-8"><section className="relative overflow-hidden rounded-3xl border border-white/[.07] bg-gradient-to-br from-[#151121] via-[#11131b] to-[#0e1016] p-6 lg:p-9"><div className="max-w-2xl"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-400/10 px-3 py-1 text-xs font-semibold text-violet-300"><Activity size={13}/> Bem-vindo, {user.display_name}</div><h1 className="text-3xl font-black tracking-tight sm:text-5xl">PLAY. CONNECT.<br/><span className="text-violet-400">GRIND.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-zinc-400 sm:text-base">Encontre sua squad, entre no lobby certo e continue subindo. Jogos, ranks, voz e sessões ao vivo em um só lugar.</p><div className="mt-6"><button onClick={()=>setCreate(true)} className="flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-black"><Plus size={17}/>Criar lobby</button></div></div></section>
 <section className="mt-7 grid gap-4 sm:grid-cols-3">{[["Amigos online","18",Users],["Lobbies ativos","42",Gamepad2],["Ao vivo","7",Radio]].map(([l,v,I])=><div key={l as string} className="glass rounded-2xl p-5"><div className="flex justify-between text-sm text-zinc-500"><span>{l as string}</span><I size={18}/></div><div className="mt-3 text-2xl font-black">{v as string}</div></div>)}</section>
 <div className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Seus jogos</h2><span className="text-xs text-zinc-500">Rank por jogo</span></div><div className="grid gap-4 md:grid-cols-3">{games.map(g=><div key={g[0]} className="glass rounded-2xl p-5"><div className="mb-5 grid h-11 w-11 place-items-center rounded-xl bg-violet-600"><Gamepad2 size={21}/></div><div className="text-sm font-bold">{g[0]}</div><div className="mt-1 text-xs text-zinc-500">{g[1]}</div><div className="mt-5 flex justify-between"><span className="text-xl font-black">{g[2]}</span><span className="text-[10px] text-zinc-500">PTS</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-violet-500" style={{width:`${g[3]}%`}}/></div></div>)}</div></div>
 <div className="mt-8 grid gap-8 xl:grid-cols-[1fr_320px]"><div><div className="mb-4 flex justify-between"><h2 className="text-lg font-bold">Lobbies ativos</h2><span className="text-xs text-violet-400">42 ativos</span></div>{[["Night Grind","EA FC 27","Pro Clubs","8/11"],["Ranked Squad","Valorant","Competitive","4/5"],["Late Night","Rocket League","2v2","3/4"]].map(l=><div key={l[0]} className="glass mb-3 flex items-center gap-4 rounded-2xl p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/[.05]"><Gamepad2 size={19}/></div><div className="flex-1"><b>{l[0]}</b><div className="text-xs text-zinc-500">{l[1]} · {l[2]}</div></div><span className="text-xs text-zinc-400">{l[3]}</span><button className="rounded-xl border border-white/10 px-4 py-2 text-xs font-semibold">Entrar</button></div>)}</div><aside className="glass rounded-2xl p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Seu perfil</h2><Crown size={17} className="text-violet-400"/></div><div className="text-xl font-black">{user.display_name}</div><div className="text-sm text-zinc-500">@{user.username}</div><div className="mt-5 rounded-xl bg-white/[.03] p-4"><div className="text-xs text-zinc-500">Status</div><div className="mt-1 font-semibold text-emerald-400">Online</div></div></aside></div>
 </div></section></div>{create&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><div className="glass w-full max-w-lg rounded-3xl p-6"><div className="flex justify-between"><div><h2 className="text-xl font-black">Criar lobby</h2><p className="mt-1 text-sm text-zinc-500">A próxima etapa ligará isso ao backend persistente.</p></div><button onClick={()=>setCreate(false)}>✕</button></div><div className="mt-6 space-y-3">{["EA FC 27","Pro Clubs","11 jogadores","Divisão 3+","Público"].map(x=><div key={x} className="rounded-xl border border-white/[.07] bg-white/[.03] p-3 text-sm">{x}</div>)}</div><button onClick={()=>setCreate(false)} className="mt-6 w-full rounded-xl bg-violet-600 py-3 font-bold">Fechar</button></div></div>}</main>
}