"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import AudioSettings from './AudioSettings';
import GrindLobbyLogo from '@/components/brand/GrindLobbyLogo';
import {Home,Gamepad2,Trophy,Users,Radio,Settings,Search,Bell,Plus,Activity,Crown,LogOut,Mic2,MonitorUp,ShieldCheck,Sparkles,ChevronRight,Zap,Loader2} from "lucide-react";

type GameCard={id:number;name:string;slug:string;rank:string;points:number;winRate:number;progress:number};
type LobbyCard={id:string;owner_id:string;game_id:number|null;name:string;description:string|null;visibility:string;max_members:number;status:string;created_at:string;game:{id:number;name:string;slug:string}|null;owner:{id:string;username:string;display_name:string;avatar:string|null;status:string}|null;memberCount:number;joined:boolean};
type OnlineUser={id:string;username:string;display_name:string;avatar:string|null;status:string};
type DashboardData={games:GameCard[];lobbies:LobbyCard[];online:OnlineUser[];stats:{online:number;activeLobbies:number;myLobbies:number;rank:number}};

const fallbackGames=[{id:0,name:"EA FC 27",slug:"ea-fc-27",rank:"Sem rank",points:0,winRate:0,progress:8},{id:-1,name:"Valorant",slug:"valorant",rank:"Sem rank",points:0,winRate:0,progress:8},{id:-2,name:"Rocket League",slug:"rocket-league",rank:"Sem rank",points:0,winRate:0,progress:8}];

export default function Dashboard({user}:{user:any}){
 const [create,setCreate]=useState(false); const [data,setData]=useState<DashboardData|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState("");
 const [view,setView]=useState("overview");
 const [name,setName]=useState(""); const [gameId,setGameId]=useState(""); const [maxMembers,setMaxMembers]=useState("5"); const [visibility,setVisibility]=useState("public");
 const router=useRouter(); const display=user.display_name||user.username||"Player";
 const games=data?.games?.length?data.games:fallbackGames;
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/dashboard',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao carregar');setData(j);if(!gameId&&j.games?.[0]?.id)setGameId(String(j.games[0].id));}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load();const timer=setInterval(load,10000);return()=>clearInterval(timer)},[]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.push("/login");router.refresh()}
 async function createLobby(){setError("");if(!name.trim()||!gameId)return setError('Preencha nome e jogo.');setBusy('create');try{const r=await fetch('/api/lobbies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,gameId:Number(gameId),maxMembers:Number(maxMembers),visibility})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao criar lobby');setCreate(false);setName('');await load();router.push(`/lobby/${j.lobbyId}`)}catch(e:any){setError(e.message)}finally{setBusy(null)}}
 async function enterLobby(l:LobbyCard){setBusy(l.id);setError('');try{if(!l.joined){const r=await fetch(`/api/lobbies/${l.id}/join`,{method:'POST'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Não foi possível entrar.')}router.push(`/lobby/${l.id}`)}catch(e:any){setError(e.message)}finally{setBusy(null)}}
 const online=data?.online??[]; const stats=data?.stats??{online:1,activeLobbies:0,myLobbies:0,rank:0};
 return <main className="app-shell min-h-screen text-white"><div className="ambient a1"/><div className="ambient a2"/><div className="relative flex min-h-screen">
  <aside className="sidebar hidden w-[268px] shrink-0 lg:flex lg:flex-col">
   <GrindLobbyLogo variant="full" size="md"/>
  <div className="nav-label">NETWORK</div><nav className="space-y-1">{[[Home,"Overview"],[Gamepad2,"Games"],[Trophy,"Rankings"],[Users,"Lobbies"],[Radio,"Live"]].map(([I,l])=><button key={l as string} onClick={()=>setView(String(l).toLowerCase())} className={`nav-item ${view===String(l).toLowerCase()?"active":""}`}><I size={18}/>{l as string}{l==="Lobbies"&&<em>{stats.activeLobbies}</em>}</button>)}</nav>
   <div className="pro-card"><div><Zap size={14}/> GRIND PRO</div><p>1080p 60fps, perfil premium e recursos competitivos.</p><button>Ver benefícios →</button></div>
  <div className="mt-auto"><button onClick={()=>setView("settings")} className={`nav-item ${view==="settings"?"active":""}`}><Settings size={18}/>Settings</button><button onClick={logout} className="nav-item"><LogOut size={18}/>Sair</button><div className="profile-mini"><div className="avatar">{display.slice(0,2).toUpperCase()}<i/></div><div><b>{display}</b><span>Online agora</span></div></div></div>
  </aside>
  <section className="min-w-0 flex-1"><header className="topbar"><GrindLobbyLogo variant="symbol" size="sm" className="lg:hidden"/><div className="search"><Search size={16}/><input placeholder="Buscar players, jogos, lobbies..."/></div><button className="icon-btn" onClick={()=>setView("settings")} aria-label="Configurações"><Settings size={18}/></button><button className="icon-btn"><Bell size={18}/><i/></button><button onClick={()=>setCreate(true)} className="primary hidden sm:flex"><Plus size={17}/> Criar lobby</button></header>
  <div className={`mx-auto max-w-[1540px] p-4 pb-24 lg:p-8 ${view!=="overview"?"hidden":""}`}>
    <section className="hero"><div className="gridfx"/><div className="glow"/><div className="relative z-10 max-w-2xl"><div className="eyebrow"><Activity size={13}/> SESSION READY · {stats.online} PLAYERS ONLINE</div><h1>YOUR NEXT<br/><span>GRIND STARTS HERE.</span></h1><p>Monte sua squad, encontre partidas no seu nível e entre em voz sem sair do fluxo. Uma central competitiva feita para jogar.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>setCreate(true)} className="primary"><Plus size={17}/> Criar lobby</button><button className="secondary"><Users size={17}/> Encontrar squad</button></div></div><div className="hero-status hidden xl:block"><small>NETWORK STATUS</small><b><i/> ALL SYSTEMS READY</b><div><span>VOICE</span><strong>LOW LATENCY</strong></div><div><span>STREAM</span><strong>1080P · 60FPS PRO</strong></div></div></section>
    {error&&<div className="dash-error">{error}</div>}
    <section className="stats">{[[Users,String(stats.online),"Players online","tempo real"],[Gamepad2,String(stats.activeLobbies),"Lobbies ativos",`${stats.myLobbies} seus`],[Radio,String(stats.myLobbies),"Seus lobbies","persistentes"],[Trophy,stats.rank?String(stats.rank):"—","Seu melhor score","Grind points"]].map(([I,v,l,s]:any)=><div className="stat" key={l}><div className="stat-icon"><I size={18}/></div><div><small>{l}</small><b>{loading?<Loader2 size={15} className="animate-spin"/>:v}</b><span>{s}</span></div></div>)}</section>
    <div className="content"><div className="min-w-0"><div className="section-head"><div><small>COMPETITIVE IDENTITY</small><h2>Seus jogos</h2></div><button>Gerenciar <ChevronRight size={14}/></button></div><div className="game-grid">{games.map((g:any)=><article className="game" key={g.name}><div className="game-top"><div className="game-logo">{g.name.split(' ').map((x:string)=>x[0]).join('').slice(0,2)}</div><span>RANKED</span></div><h3>{g.name}</h3><p>{g.rank}</p><div className="points"><b>{g.points.toLocaleString('pt-BR')}</b><small>GRIND PTS</small></div><div className="progress"><i style={{width:`${g.progress}%`}}/></div><div className="progress-label"><span>{g.winRate?`${g.winRate}% win rate`:'Comece a competir'}</span><b>{g.progress}%</b></div></article>)}</div>
     <div className="section-head mt-9"><div><small>PLAY NOW</small><h2>Lobbies recomendados</h2></div><button onClick={load}>Atualizar <ChevronRight size={14}/></button></div><div className="lobby-list">{loading&&<div className="empty-state"><Loader2 className="animate-spin" size={18}/> Buscando lobbies...</div>}{!loading&&data?.lobbies?.length===0&&<div className="empty-state">Nenhum lobby aberto ainda. Crie o primeiro da rede.</div>}{data?.lobbies?.slice(0,6).map((l,i)=><article className="lobby" key={l.id}><div className="lobby-logo"><Gamepad2 size={19}/></div><div className="lobby-main"><div className="flex items-center gap-2"><h3>{l.name}</h3>{i===0&&<span className="hot">NEW</span>}</div><p>{l.game?.name??'Jogo livre'} · por {l.owner?.display_name??l.owner?.username??'Player'}</p></div><div className="lobby-meta hidden md:flex"><span><Mic2 size={14}/> Voice ready</span><span><MonitorUp size={14}/> Online</span></div><div className="slots"><small>PLAYERS</small><b>{l.memberCount}/{l.max_members}</b></div><button disabled={busy===l.id||l.memberCount>=l.max_members} onClick={()=>enterLobby(l)} className="join">{busy===l.id?<Loader2 size={14} className="animate-spin"/>:l.joined?'Abrir':'Entrar'}</button></article>)}</div></div>
     <aside className="rail"><div className="profile-card"><div className="cover"/><div className="big-avatar">{display.slice(0,2).toUpperCase()}<i/></div><div className="mt-11"><div className="flex justify-between"><div><h3>{display}</h3><p>@{user.username}</p></div><Crown size={18} className="text-violet-300"/></div><div className="profile-stats"><div><b>{stats.myLobbies}</b><span>LOBBIES</span></div><div><b>{stats.rank||0}</b><span>POINTS</span></div><div><b>{games[0]?.winRate||0}%</b><span>WIN RATE</span></div></div><div className="verified"><ShieldCheck size={16}/><div><b>Grinder verificado</b><span>Conta protegida e pronta</span></div></div></div></div><div className="friends"><div className="flex justify-between"><div><small>NETWORK</small><h3>Online agora</h3></div><span>{stats.online}</span></div>{online.slice(0,4).map(n=><div className="friend" key={n.id}><div className="friend-avatar">{(n.display_name||n.username)[0].toUpperCase()}<i/></div><div><b>{n.display_name||n.username}</b><span>@{n.username} · Online</span></div><button>+</button></div>)}{!online.length&&!loading&&<div className="empty-mini">Você é o primeiro online agora.</div>}</div></aside></div>
  </div>
  {view!=="overview"&&<div className="mx-auto max-w-[1540px] p-4 pb-24 lg:p-8">
   {view==="games"&&<section className="dashboard-view"><div className="section-head"><div><small>COMPETITIVE IDENTITY</small><h2>Seus jogos</h2></div></div><div className="game-grid">{games.map(g=><article className="game" key={g.name}><div className="game-top"><div className="game-logo">{g.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><span>RANKED</span></div><h3>{g.name}</h3><p>{g.rank}</p><div className="points"><b>{g.points.toLocaleString("pt-BR")}</b><small>GRIND PTS</small></div><div className="progress"><i style={{width:`${g.progress}%`}}/></div><div className="progress-label"><span>{g.winRate?`${g.winRate}% win rate`:"Comece a competir"}</span><b>{g.progress}%</b></div></article>)}</div></section>}
   {view==="lobbies"&&<section className="dashboard-view"><div className="section-head"><div><small>PLAY NOW</small><h2>Lobbies disponíveis</h2></div><button onClick={()=>setCreate(true)}><Plus size={14}/> Criar lobby</button></div><div className="lobby-list">{data?.lobbies?.map((l,i)=><article className="lobby" key={l.id}><div className="lobby-logo"><Gamepad2 size={19}/></div><div className="lobby-main"><div className="flex items-center gap-2"><h3>{l.name}</h3>{i===0&&<span className="hot">NEW</span>}</div><p>{l.game?.name??"Jogo livre"} · por {l.owner?.display_name??l.owner?.username??"Player"}</p></div><div className="slots"><small>PLAYERS</small><b>{l.memberCount}/{l.max_members}</b></div><button disabled={busy===l.id||l.memberCount>=l.max_members} onClick={()=>enterLobby(l)} className="join">{busy===l.id?<Loader2 size={14}/>:l.joined?"Abrir":"Entrar"}</button></article>)}{!loading&&!data?.lobbies?.length&&<div className="empty-state">Nenhum lobby aberto ainda. Crie o primeiro da rede.</div>}</div></section>}
   {view==="rankings"&&<section className="dashboard-view empty-view"><Trophy size={28}/><small>GRIND RANKINGS</small><h2>Rankings da comunidade</h2><p>As classificações competitivas estarão disponíveis em breve.</p></section>}
   {view==="live"&&<section className="dashboard-view empty-view"><Radio size={28}/><small>GRIND LIVE</small><h2>Transmissões ao vivo</h2><p>Em breve você poderá acompanhar as partidas e transmissões da rede.</p></section>}
  {view==="settings"&&<AudioSettings/>}
  </div>}
  </section></div>
  {create&&<div className="modal-bg"><div className="modal"><div className="modal-head"><div><div className="eyebrow"><Sparkles size={13}/> QUICK CREATE</div><h2>Criar novo lobby</h2><p>Agora ele será salvo de verdade no Supabase.</p></div><button onClick={()=>setCreate(false)}>✕</button></div><div className="modal-fields"><label>Nome do lobby<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex: Night Grind"/></label><label>Jogo<select value={gameId} onChange={e=>setGameId(e.target.value)}>{games.filter(g=>g.id>0).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label>Vagas<input type="number" min="2" max="100" value={maxMembers} onChange={e=>setMaxMembers(e.target.value)}/></label><label>Privacidade<select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="public">Público</option><option value="friends">Amigos</option><option value="private">Privado</option></select></label></div></div><button disabled={busy==='create'} onClick={createLobby} className="primary mt-6 w-full justify-center">{busy==='create'?<><Loader2 size={15} className="animate-spin"/>Criando...</>:<>Criar lobby</>}</button></div></div>}
 </main>
}
