[package]
name = "grindlobby-desktop"
version = "0.2.1"
description = "GrindLobby native desktop client"
authors = ["GrindLobby"]
edition = "2021"

[features]
default = []
lite = []

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
tauri = { version = "=2.11.5", features = [] }
url = "=2.5.8"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.145"
sysinfo = { version = "=0.33.1", default-features = false, features = ["system"] }
reqwest = { version = "=0.12.23", default-features = false, features = ["json", "cookies", "rustls-tls"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
