from __future__ import annotations

import hashlib
import hmac
import json
import os
import secrets
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Mapping

from fastapi import Depends, FastAPI, Header, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from sqlalchemy import create_engine, text
from sqlalchemy.exc import IntegrityError

BASE = Path(__file__).resolve().parent
TOKEN_TTL = 60 * 60 * 24 * 30


def normalize_database_url(raw: str | None) -> str:
    if not raw:
        return f"sqlite:///{BASE / 'football_iq.db'}"
    raw = raw.strip()
    if raw.startswith("postgres://"):
        return "postgresql+psycopg://" + raw[len("postgres://"):]
    if raw.startswith("postgresql://"):
        return "postgresql+psycopg://" + raw[len("postgresql://"):]
    return raw


DATABASE_URL = normalize_database_url(os.getenv("DATABASE_URL"))
ENGINE_KWARGS: dict[str, Any] = {"pool_pre_ping": True}
if DATABASE_URL.startswith("sqlite:"):
    ENGINE_KWARGS["connect_args"] = {"check_same_thread": False}
engine = create_engine(DATABASE_URL, **ENGINE_KWARGS)
DB_DIALECT = engine.dialect.name

app = FastAPI(title="Football IQ V9 API", version="9.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://127.0.0.1:8000", "http://localhost:8000", "null", "*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


@contextmanager
def db():
    with engine.begin() as conn:
        yield conn


def init_db() -> None:
    is_pg = DB_DIALECT == "postgresql"
    id_col = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if is_pg else "INTEGER PRIMARY KEY AUTOINCREMENT"
    user_id_type = "BIGINT" if is_pg else "INTEGER"
    username_col = "TEXT NOT NULL" if is_pg else "TEXT NOT NULL UNIQUE COLLATE NOCASE"

    statements = [
        f"""
        CREATE TABLE IF NOT EXISTS users (
            id {id_col},
            username {username_col},
            salt TEXT NOT NULL,
            password_hash TEXT NOT NULL,
            created_at BIGINT NOT NULL
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS sessions (
            token_hash TEXT PRIMARY KEY,
            user_id {user_id_type} NOT NULL,
            expires_at BIGINT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS scores (
            user_id {user_id_type} PRIMARY KEY,
            xp BIGINT NOT NULL DEFAULT 0,
            level INTEGER NOT NULL DEFAULT 1,
            coins BIGINT NOT NULL DEFAULT 0,
            online_wins BIGINT NOT NULL DEFAULT 0,
            online_losses BIGINT NOT NULL DEFAULT 0,
            stats_json TEXT NOT NULL DEFAULT '{{}}',
            updated_at BIGINT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS saves (
            user_id {user_id_type} PRIMARY KEY,
            data_json TEXT NOT NULL,
            updated_at BIGINT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """,
    ]

    with engine.begin() as c:
        if DB_DIALECT == "sqlite":
            c.execute(text("PRAGMA journal_mode=WAL"))
            c.execute(text("PRAGMA foreign_keys=ON"))
        for statement in statements:
            c.execute(text(statement))
        if is_pg:
            c.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS users_username_ci ON users (LOWER(username))"))
        c.execute(text("CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions (expires_at)"))
        c.execute(text("CREATE INDEX IF NOT EXISTS scores_rank_idx ON scores (xp DESC, online_wins DESC, updated_at ASC)"))


init_db()


class AuthPayload(BaseModel):
    username: str = Field(min_length=3, max_length=24, pattern=r"^[A-Za-z0-9_.-]+$")
    password: str = Field(min_length=6, max_length=128)


class ScorePayload(BaseModel):
    xp: int = Field(ge=0, le=100_000_000)
    level: int = Field(ge=1, le=10_000)
    coins: int = Field(ge=0, le=100_000_000)
    stats: dict[str, Any] = Field(default_factory=dict)


class SavePayload(BaseModel):
    data: dict[str, Any]


def password_digest(password: str, salt_hex: str) -> str:
    return hashlib.pbkdf2_hmac("sha256", password.encode(), bytes.fromhex(salt_hex), 210_000).hex()


def hash_token(token: str) -> str:
    return hashlib.sha256(token.encode()).hexdigest()


def make_session(user_id: int) -> str:
    token = secrets.token_urlsafe(32)
    now = int(time.time())
    with db() as c:
        c.execute(text("DELETE FROM sessions WHERE expires_at < :now"), {"now": now})
        c.execute(
            text("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(:token_hash,:user_id,:expires_at)"),
            {"token_hash": hash_token(token), "user_id": user_id, "expires_at": now + TOKEN_TTL},
        )
    return token


def user_for_token(token: str | None) -> Mapping[str, Any] | None:
    if not token:
        return None
    with db() as c:
        return c.execute(
            text(
                """
                SELECT u.* FROM sessions s
                JOIN users u ON u.id=s.user_id
                WHERE s.token_hash=:token_hash AND s.expires_at>=:now
                """
            ),
            {"token_hash": hash_token(token), "now": int(time.time())},
        ).mappings().first()


def current_user(authorization: str | None = Header(default=None)) -> Mapping[str, Any]:
    if not authorization or not authorization.lower().startswith("bearer "):
        raise HTTPException(401, "authentication required")
    user = user_for_token(authorization.split(" ", 1)[1].strip())
    if not user:
        raise HTTPException(401, "invalid or expired session")
    return user


@app.get("/api/health")
def health():
    with db() as c:
        c.execute(text("SELECT 1"))
    return {
        "ok": True,
        "version": "9.1.0",
        "database": DB_DIALECT,
        "persistent": DB_DIALECT == "postgresql",
    }


@app.post("/api/register")
def register(payload: AuthPayload):
    username = payload.username.strip()
    salt = secrets.token_hex(16)
    digest = password_digest(payload.password, salt)
    now = int(time.time())
    try:
        with db() as c:
            user_id = c.execute(
                text(
                    """
                    INSERT INTO users(username,salt,password_hash,created_at)
                    VALUES(:username,:salt,:password_hash,:created_at)
                    RETURNING id
                    """
                ),
                {"username": username, "salt": salt, "password_hash": digest, "created_at": now},
            ).scalar_one()
            c.execute(
                text(
                    """
                    INSERT INTO scores(user_id,xp,level,coins,online_wins,online_losses,stats_json,updated_at)
                    VALUES(:user_id,0,1,0,0,0,'{}',:updated_at)
                    """
                ),
                {"user_id": int(user_id), "updated_at": now},
            )
    except IntegrityError:
        raise HTTPException(409, "username already exists")
    token = make_session(int(user_id))
    return {"token": token, "user": {"id": int(user_id), "username": username}}


@app.post("/api/login")
def login(payload: AuthPayload):
    username = payload.username.strip()
    with db() as c:
        user = c.execute(
            text("SELECT * FROM users WHERE LOWER(username)=LOWER(:username)"),
            {"username": username},
        ).mappings().first()
    if not user:
        raise HTTPException(401, "invalid username or password")
    candidate = password_digest(payload.password, user["salt"])
    if not hmac.compare_digest(candidate, user["password_hash"]):
        raise HTTPException(401, "invalid username or password")
    token = make_session(int(user["id"]))
    return {"token": token, "user": {"id": int(user["id"]), "username": user["username"]}}


@app.get("/api/me")
def me(user: Mapping[str, Any] = Depends(current_user)):
    return {"id": int(user["id"]), "username": user["username"]}


@app.post("/api/score")
def update_score(payload: ScorePayload, user: Mapping[str, Any] = Depends(current_user)):
    user_id = int(user["id"])
    stats_json = json.dumps(payload.stats, ensure_ascii=False, separators=(",", ":"))
    wins = int(payload.stats.get("onlineWins", 0) or 0)
    losses = int(payload.stats.get("onlineLosses", 0) or 0)
    now = int(time.time())
    with db() as c:
        existing = c.execute(
            text("SELECT xp,level,online_wins,online_losses FROM scores WHERE user_id=:user_id"),
            {"user_id": user_id},
        ).mappings().first()
        if existing:
            c.execute(
                text(
                    """
                    UPDATE scores SET xp=:xp, level=:level, coins=:coins,
                        online_wins=:online_wins, online_losses=:online_losses,
                        stats_json=:stats_json, updated_at=:updated_at
                    WHERE user_id=:user_id
                    """
                ),
                {
                    "user_id": user_id,
                    "xp": max(int(existing["xp"]), payload.xp),
                    "level": max(int(existing["level"]), payload.level),
                    "coins": payload.coins,
                    "online_wins": max(int(existing["online_wins"]), wins),
                    "online_losses": max(int(existing["online_losses"]), losses),
                    "stats_json": stats_json,
                    "updated_at": now,
                },
            )
        else:
            c.execute(
                text(
                    """
                    INSERT INTO scores(user_id,xp,level,coins,online_wins,online_losses,stats_json,updated_at)
                    VALUES(:user_id,:xp,:level,:coins,:online_wins,:online_losses,:stats_json,:updated_at)
                    """
                ),
                {
                    "user_id": user_id,
                    "xp": payload.xp,
                    "level": payload.level,
                    "coins": payload.coins,
                    "online_wins": wins,
                    "online_losses": losses,
                    "stats_json": stats_json,
                    "updated_at": now,
                },
            )
    return {"ok": True}


@app.get("/api/leaderboard")
def leaderboard(limit: int = 50):
    limit = max(1, min(limit, 100))
    with db() as c:
        rows = c.execute(
            text(
                """
                SELECT u.username,s.xp,s.level,s.online_wins,s.online_losses,s.updated_at
                FROM scores s JOIN users u ON u.id=s.user_id
                ORDER BY s.xp DESC, s.online_wins DESC, s.updated_at ASC
                LIMIT :limit
                """
            ),
            {"limit": limit},
        ).mappings().all()
    return {"items": [dict(r) for r in rows]}


@app.put("/api/save")
def put_save(payload: SavePayload, user: Mapping[str, Any] = Depends(current_user)):
    user_id = int(user["id"])
    raw = json.dumps(payload.data, ensure_ascii=False, separators=(",", ":"))
    if len(raw.encode()) > 2_000_000:
        raise HTTPException(413, "save too large")
    now = int(time.time())
    with db() as c:
        exists = c.execute(
            text("SELECT 1 FROM saves WHERE user_id=:user_id"), {"user_id": user_id}
        ).first()
        if exists:
            c.execute(
                text("UPDATE saves SET data_json=:data_json,updated_at=:updated_at WHERE user_id=:user_id"),
                {"data_json": raw, "updated_at": now, "user_id": user_id},
            )
        else:
            c.execute(
                text("INSERT INTO saves(user_id,data_json,updated_at) VALUES(:user_id,:data_json,:updated_at)"),
                {"user_id": user_id, "data_json": raw, "updated_at": now},
            )
    return {"ok": True, "updated_at": now}


@app.get("/api/save")
def get_save(user: Mapping[str, Any] = Depends(current_user)):
    with db() as c:
        row = c.execute(
            text("SELECT data_json,updated_at FROM saves WHERE user_id=:user_id"),
            {"user_id": int(user["id"])},
        ).mappings().first()
    if not row:
        return {"data": None, "updated_at": None}
    try:
        data = json.loads(row["data_json"])
    except json.JSONDecodeError:
        data = None
    return {"data": data, "updated_at": row["updated_at"]}


class RoomHub:
    def __init__(self) -> None:
        self.rooms: dict[str, dict[str, WebSocket]] = {}

    async def connect(self, room: str, name: str, ws: WebSocket) -> bool:
        room = room.upper()
        members = self.rooms.setdefault(room, {})
        if name not in members and len(members) >= 2:
            await ws.accept()
            await ws.send_json({"type": "error", "message": "room full"})
            await ws.close(code=4003)
            return False
        await ws.accept()
        members[name] = ws
        await self.broadcast(room, {"type": "presence", "count": len(members), "players": list(members)})
        return True

    async def disconnect(self, room: str, name: str) -> None:
        room = room.upper()
        members = self.rooms.get(room, {})
        members.pop(name, None)
        if not members:
            self.rooms.pop(room, None)
            return
        await self.broadcast(room, {"type": "peer_left", "name": name})
        await self.broadcast(room, {"type": "presence", "count": len(members), "players": list(members)})

    async def broadcast(self, room: str, payload: dict[str, Any]) -> None:
        dead: list[str] = []
        for name, ws in list(self.rooms.get(room.upper(), {}).items()):
            try:
                await ws.send_json(payload)
            except Exception:
                dead.append(name)
        for name in dead:
            self.rooms.get(room.upper(), {}).pop(name, None)


hub = RoomHub()


@app.websocket("/ws/{room}/{name}")
async def room_socket(ws: WebSocket, room: str, name: str, token: str | None = None):
    room = room.strip().upper()[:8]
    name = name.strip()[:32] or "Guest"
    user = user_for_token(token)
    if user:
        name = user["username"]
    connected = await hub.connect(room, name, ws)
    if not connected:
        return
    try:
        while True:
            data = await ws.receive_json()
            if not isinstance(data, dict):
                continue
            msg_type = str(data.get("type", ""))[:32]
            if msg_type not in {"start", "answer", "ping", "chat"}:
                continue
            safe = {"type": msg_type, "sender": name}
            if msg_type == "start":
                indices = data.get("indices", [])
                if isinstance(indices, list):
                    safe["indices"] = [int(x) for x in indices[:10] if (isinstance(x, int) or str(x).isdigit()) and 0 <= int(x) < 12]
            elif msg_type == "answer":
                safe["correct"] = bool(data.get("correct"))
                safe["index"] = int(data.get("index", 0))
            elif msg_type == "chat":
                safe["message"] = str(data.get("message", ""))[:280]
            else:
                safe["ts"] = int(time.time() * 1000)
            await hub.broadcast(room, safe)
    except WebSocketDisconnect:
        await hub.disconnect(room, name)
    except Exception:
        await hub.disconnect(room, name)
        try:
            await ws.close()
        except Exception:
            pass


@app.get("/")
def index():
    return FileResponse(BASE / "index.html")


@app.get("/{path:path}")
def static_fallback(path: str):
    return FileResponse(BASE / "index.html")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("server:app", host="0.0.0.0", port=int(os.getenv("PORT", "8000")), reload=False)
