import { useMemo, useState } from "react";
import { Check, ImagePlus, Loader2, Save, X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { ProfileAvatar } from "@/components/ProfileAvatar";
import { LogoutButton } from "@/components/LogoutButton";
import { findItem, usePlayer } from "@/lib/player-store";
import { STORE_ITEMS } from "@/lib/store-items";
import { getTier } from "@/lib/levels";

const STATUSES=[{id:"online",label:"Online"},{id:"ausente",label:"Ausente"},{id:"ocupado",label:"Ocupado"},{id:"invisivel",label:"Invisível"}] as const;

export function ProfileSettings({onClose}:{onClose:()=>void}){
 const {player,update,equip}=usePlayer();
 const [form,setForm]=useState(player);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState<"avatar"|"banner"|null>(null);const [error,setError]=useState("");
 const tier=getTier(player.level);
 const ownedBorders=useMemo(()=>STORE_ITEMS.filter(i=>i.kind==="border"&&player.owned.includes(i.id)),[player.owned]);
 const ownedTitles=useMemo(()=>STORE_ITEMS.filter(i=>i.kind==="title"&&player.owned.includes(i.id)),[player.owned]);
 const ownedBanners=useMemo(()=>STORE_ITEMS.filter(i=>i.kind==="banner"&&player.owned.includes(i.id)),[player.owned]);

 async function upload(kind:"avatar"|"banner",file:File){
  setError("");if(!file.type.startsWith("image/")){setError("Escolha uma imagem válida.");return}if(file.size>5*1024*1024){setError("A imagem deve ter no máximo 5 MB.");return}
  setUploading(kind);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sessão expirada");const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=`${user.id}/${kind}-${Date.now()}.${ext}`;const{error:upErr}=await supabase.storage.from("profile-assets").upload(path,file,{upsert:true,cacheControl:"3600"});if(upErr)throw upErr;const{data}=supabase.storage.from("profile-assets").getPublicUrl(path);if(kind==="avatar")setForm(v=>({...v,avatarUrl:data.publicUrl}));else setForm(v=>({...v,bannerUrl:data.publicUrl}))}catch(e){setError(e instanceof Error?e.message:"Falha ao enviar imagem.")}finally{setUploading(null)}}

 async function save(){setSaving(true);setError("");try{await update({nickname:form.nickname.trim()||"jogador",handle:form.handle.trim().replace(/^@/,"")||"jogador",bio:form.bio,status:form.status,region:form.region,game:form.game,privateProfile:form.privateProfile,allowInvites:form.allowInvites,avatarUrl:form.avatarUrl,bannerUrl:form.bannerUrl});onClose()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar o perfil.")}finally{setSaving(false)}}

 const cardBg=form.bannerUrl?`linear-gradient(180deg,rgba(4,5,10,.18),rgba(4,5,10,.82)),url(${form.bannerUrl})`:findItem(player.equipped.banner)?.gradient;
 return <div className="fixed inset-0 z-50 grid place-items-center bg-background/85 p-4 backdrop-blur-sm"><div className="panel max-h-[90vh] w-full max-w-3xl overflow-y-auto p-5">
  <div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-xl font-bold">Configurações de perfil</h2><p className="mt-1 text-xs text-muted-foreground">Level {player.level} • {tier.name} • cosméticos equipáveis somente entre itens conquistados</p></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg border border-border bg-panel"><X className="h-4 w-4"/></button></div>
  <div className="mt-4 overflow-hidden rounded-xl border border-border bg-cover bg-center p-5" style={{backgroundImage:cardBg}}><div className="flex items-center gap-4"><ProfileAvatar name={form.nickname} size={76} borderId={player.equipped.border} avatarUrl={form.avatarUrl}/><div><p className="font-display text-lg font-bold">{form.nickname}</p><p className="text-xs text-muted-foreground">@{form.handle}</p><p className="mt-1 text-xs" style={{color:tier.glow}}>{tier.name}</p></div></div></div>
  <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="rounded-xl border border-border bg-panel/60 p-3 text-sm"><span className="label-caps">Foto do perfil</span><div className="mt-2 flex items-center gap-3"><ProfileAvatar name={form.nickname} size={46} borderId={player.equipped.border} avatarUrl={form.avatarUrl}/><span className="relative inline-flex cursor-pointer items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs"><ImagePlus className="h-4 w-4"/>{uploading==="avatar"?"Enviando...":"Escolher foto"}<input type="file" accept="image/*" className="absolute inset-0 cursor-pointer opacity-0" disabled={!!uploading} onChange={e=>{const f=e.target.files?.[0];if(f)void upload("avatar",f)}}/></span></div></label><label className="rounded-xl border border-border bg-panel/60 p-3 text-sm"><span className="label-caps">Background personalizado</span><div className="mt-2"><span className="relative inline-flex cursor-pointer items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs"><ImagePlus className="h-4 w-4"/>{uploading==="banner"?"Enviando...":"Escolher imagem"}<input type="file" accept="image/*" className="absolute inset-0 cursor-pointer opacity-0" disabled={!!uploading} onChange={e=>{const f=e.target.files?.[0];if(f)void upload("banner",f)}}/></span></div></label></div>
  <div className="mt-4 grid gap-4 sm:grid-cols-2"><label><span className="label-caps">Nick</span><input value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})} className="mt-1.5 w-full rounded-lg border border-input bg-panel px-3 py-2 text-sm"/></label><label><span className="label-caps">Usuário</span><input value={form.handle} onChange={e=>setForm({...form,handle:e.target.value})} className="mt-1.5 w-full rounded-lg border border-input bg-panel px-3 py-2 text-sm"/></label><label className="sm:col-span-2"><span className="label-caps">Bio</span><textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} rows={2} className="mt-1.5 w-full rounded-lg border border-input bg-panel px-3 py-2 text-sm"/></label><label><span className="label-caps">Região</span><select value={form.region} onChange={e=>setForm({...form,region:e.target.value})} className="mt-1.5 w-full rounded-lg border border-input bg-panel px-3 py-2 text-sm">{["BR-Sul","BR-Sudeste","BR-Nordeste","LATAM","NA-Leste"].map(r=><option key={r}>{r}</option>)}</select></label><label><span className="label-caps">Jogo principal</span><select value={form.game} onChange={e=>setForm({...form,game:e.target.value})} className="mt-1.5 w-full rounded-lg border border-input bg-panel px-3 py-2 text-sm">{["EA FC 27","Valorant","CS2","Rocket League","Fortnite"].map(g=><option key={g}>{g}</option>)}</select></label></div>
  <div className="mt-4"><p className="label-caps">Status</p><div className="mt-2 flex flex-wrap gap-2">{STATUSES.map(s=><button key={s.id} onClick={()=>setForm({...form,status:s.id})} className={`rounded-lg border px-3 py-1.5 text-xs font-semibold ${form.status===s.id?"border-primary/50 bg-primary/20":"border-border bg-panel text-muted-foreground"}`}>{s.label}</button>)}</div></div>
  <div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={()=>setForm({...form,privateProfile:!form.privateProfile})} className="flex items-center justify-between rounded-lg border border-border bg-panel px-3 py-2.5 text-sm">Perfil privado<span>{form.privateProfile?"Ativo":"Desativado"}</span></button><button onClick={()=>setForm({...form,allowInvites:!form.allowInvites})} className="flex items-center justify-between rounded-lg border border-border bg-panel px-3 py-2.5 text-sm">Permitir convites<span>{form.allowInvites?"Ativo":"Desativado"}</span></button></div>
  <div className="mt-5 space-y-4">{[{title:"Molduras conquistadas",list:ownedBorders,slot:"border" as const},{title:"Títulos conquistados",list:ownedTitles,slot:"title" as const},{title:"Backgrounds conquistados",list:ownedBanners,slot:"banner" as const}].map(group=><div key={group.slot}><p className="label-caps">{group.title}</p><div className="mt-2 flex flex-wrap gap-2">{group.list.length?group.list.map(item=><button key={item.id} onClick={()=>void equip(item)} className={`flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs ${player.equipped[group.slot]===item.id?"border-success/50 bg-success/15 text-success":"border-border bg-panel text-muted-foreground"}`}>{player.equipped[group.slot]===item.id&&<Check className="h-3.5 w-3.5"/>}{item.name}</button>):<span className="text-xs text-muted-foreground">Nenhum item conquistado nesta categoria.</span>}</div></div>)}</div>
  {error&&<p className="mt-4 rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-xs text-destructive">{error}</p>}
  <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><LogoutButton onError={setError}/><button onClick={()=>void save()} disabled={saving||!!uploading} className="btn-primary flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Salvar alterações</button></div>
 </div></div>
}
