import { useEffect, useState } from "react";
import { Crown, Gamepad2, Swords, TrendingUp } from "lucide-react";
import { ProfileAvatar } from "@/components/ProfileAvatar";
import { supabase } from "@/lib/supabase";
import { getTier, tierGradient } from "@/lib/levels";

type Row={id:string;name:string;handle:string;level:number;points:number;matches:number;wins:number;avatar:string;border:string;game:string;status:string};
function parseBorder(v:unknown){if(v&&typeof v==="object"&&typeof (v as any).border==="string")return (v as any).border;return "border-none"}
export function TopElos(){const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const{data}=await supabase.from("profiles").select("id,display_name,username,account_level,competitive_points,matches_played,matches_won,avatar,cosmetic_equipped,favorite_game,status").gt("matches_played",0).order("competitive_points",{ascending:false}).limit(7);setRows((data||[]).map((p:any)=>({id:p.id,name:p.display_name||p.username||"Jogador",handle:p.username||"jogador",level:p.account_level||0,points:Number(p.competitive_points||0),matches:p.matches_played||0,wins:p.matches_won||0,avatar:p.avatar||"",border:parseBorder(p.cosmetic_equipped),game:p.favorite_game||"—",status:p.status||"offline"})));setLoading(false)};
 useEffect(()=>{void load();const ch=supabase.channel("top-elos-live").on("postgres_changes",{event:"UPDATE",schema:"public",table:"profiles"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(ch)}},[]);
 return <section className="panel px-5 py-4"><div className="flex items-center justify-between"><p className="label-caps flex items-center gap-2"><Crown className="h-4 w-4 text-warning"/>Top elos do servidor</p><span className="flex items-center gap-1.5 text-xs text-muted-foreground"><TrendingUp className="h-3.5 w-3.5 text-success"/>partidas confirmadas</span></div>{loading?<p className="mt-4 text-sm text-muted-foreground">Carregando ranking...</p>:rows.length===0?<div className="mt-4 rounded-xl border border-dashed border-border p-4 text-sm text-muted-foreground">Ainda não há jogadores ranqueados. O Top Elos começa a preencher quando partidas reais forem finalizadas.</div>:<ol className="mt-3 flex gap-3 overflow-x-auto pb-1">{rows.map((p,i)=>{const tier=getTier(p.level);const wr=p.matches?Math.round((p.wins/p.matches)*100):0;return <li key={p.id} className="min-w-[205px] rounded-xl border border-border bg-panel/60 p-3"><div className="flex items-center gap-3"><span className="font-display text-sm font-bold text-muted-foreground">#{i+1}</span><ProfileAvatar name={p.name} size={38} borderId={p.border} avatarUrl={p.avatar}/><div className="min-w-0"><p className="truncate text-sm font-semibold">{p.name}</p><p className="text-[11px] text-muted-foreground">@{p.handle}</p></div></div><div className="mt-3 flex items-center justify-between text-[11px]"><span className="rounded px-1.5 py-0.5 font-bold text-background" style={{backgroundImage:tierGradient(tier)}}>{p.points} pts</span><span className="text-muted-foreground">Lv {p.level} · {tier.name}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-center text-[10px]"><div className="rounded-lg border border-border p-1.5"><Swords className="mx-auto h-3 w-3"/><b className="mt-1 block text-xs">{wr}%</b><span className="text-muted-foreground">winrate</span></div><div className="rounded-lg border border-border p-1.5"><Gamepad2 className="mx-auto h-3 w-3"/><b className="mt-1 block text-xs">{p.matches}</b><span className="text-muted-foreground">partidas</span></div></div></li>})}</ol>}</section>}
