"use client";
import Link from "next/link";import {FormEvent,Suspense,useState} from "react";import {useRouter,useSearchParams} from "next/navigation";import AuthShell from "@/components/auth/AuthShell";import PasswordField from "@/components/auth/PasswordField";import GrindLoading from "@/components/feedback/GrindLoading";
const messages:Record<string,string>={confirmed:"E-mail confirmado. Sua conta está pronta.",password_updated:"Senha atualizada. Entre novamente.",confirmation_failed:"O link de confirmação é inválido ou expirou."};
function LoginForm(){
 const query=useSearchParams(),router=useRouter(),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[remember,setRemember]=useState(true),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError("");try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identifier:email,password,remember})}),data=await response.json();if(!response.ok){if(data.code==="email_unconfirmed")router.push(`/verify-email?email=${encodeURIComponent(email)}`);else setError(data.error||"Não foi possível entrar.");return}router.push("/");router.refresh()}catch{setError("Sem conexão. Verifique sua rede e tente novamente.")}finally{setLoading(false)}}
 return <AuthShell eyebrow="WELCOME BACK" title="Entre no GrindLobby" description="Sua party está esperando."><form onSubmit={submit} className="auth-form">{messages[query.get("status")||""]?<div className="auth-success">{messages[query.get("status")||""]}</div>:null}<label className="auth-label">E-mail ou username<input className="auth-input" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><PasswordField value={password} onChange={setPassword}/><div className="auth-row"><label className="auth-check"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span/>Lembrar de mim</label><Link href="/forgot-password">Esqueci minha senha</Link></div>{error?<div className="auth-error">{error}</div>:null}<button className="auth-primary" disabled={loading}>{loading?<GrindLoading label="Entrando…"/>:"Entrar"}</button><p className="auth-switch">Novo por aqui? <Link href="/register">Criar conta</Link></p></form></AuthShell>;
}
export default function Login(){return <Suspense fallback={<GrindLoading variant="fullscreen" label="Preparando login…"/>}><LoginForm/></Suspense>}
