"use client";
import {useEffect,useRef,useState} from "react";import {Expand,MonitorUp,Radio,Square,Volume2,X} from "lucide-react";import {ConnectionState,LocalVideoTrack,RemoteAudioTrack,RemoteVideoTrack,Room,RoomEvent,Track,type VideoTrack} from "livekit-client";import {subscribeActiveLiveKitRoom} from "@/lib/webrtc/useLobbyVoice";import GrindLoading from "@/components/feedback/GrindLoading";
type Entitlement={tier:"free"|"pro";maxWidth:number;maxHeight:number;maxFps:number};
type Share={ownerId:string;ownerName:string;track:VideoTrack;audioTrack:RemoteAudioTrack|null;local:boolean;quality:string};
const freeEntitlement:Entitlement={tier:"free",maxWidth:1280,maxHeight:720,maxFps:30};
function trackQuality(track:VideoTrack){const settings=track.mediaStreamTrack.getSettings(),width=settings.width,height=settings.height,fps=settings.frameRate;return width&&height?`${width}×${height}${fps?` · ${Math.round(fps)} FPS`:""}`:"Qualidade adaptativa"}
function snapshot(room:Room|null):Share[]{if(!room||room.state!==ConnectionState.Connected)return[];const shares:Share[]=[];const local=room.localParticipant.getTrackPublication(Track.Source.ScreenShare)?.track,localAudio=room.localParticipant.getTrackPublication(Track.Source.ScreenShareAudio)?.track;if(local instanceof LocalVideoTrack)shares.push({ownerId:room.localParticipant.identity,ownerName:room.localParticipant.name||"Você",track:local,audioTrack:null,local:true,quality:trackQuality(local)+(localAudio?" · com áudio":" · sem áudio")});for(const participant of room.remoteParticipants.values()){const track=participant.getTrackPublication(Track.Source.ScreenShare)?.track,audio=participant.getTrackPublication(Track.Source.ScreenShareAudio)?.track;if(track instanceof RemoteVideoTrack)shares.push({ownerId:participant.identity,ownerName:participant.name||"Player",track,audioTrack:audio instanceof RemoteAudioTrack?audio:null,local:false,quality:trackQuality(track)+(audio?" · com áudio":" · sem áudio")})}return shares}
function StreamVideo({share,volume}:{share:Share;volume:number}){const videoRef=useRef<HTMLVideoElement>(null),audioRef=useRef<HTMLAudioElement>(null);useEffect(()=>{const element=videoRef.current;if(!element)return;share.track.attach(element);return()=>{share.track.detach(element)}},[share]);useEffect(()=>{const element=audioRef.current,track=share.audioTrack;if(!element||!track)return;track.attach(element);element.volume=volume/100;return()=>{track.detach(element)}},[share.audioTrack,volume]);return <><video ref={videoRef} autoPlay playsInline muted/><audio ref={audioRef} autoPlay/></>}
export default function ScreenShare({isPro=false}:{isPro?:boolean}){
 const initialEntitlement=isPro?{tier:"pro" as const,maxWidth:1920,maxHeight:1080,maxFps:60}:freeEntitlement;
 const [room,setRoom]=useState<Room|null>(null),[shares,setShares]=useState<Share[]>([]),[panel,setPanel]=useState(false),[viewerId,setViewerId]=useState<string|null>(null),[busy,setBusy]=useState(false),[reconnecting,setReconnecting]=useState(false),[surface,setSurface]=useState<"monitor"|"window"|"browser">("monitor"),[volume,setVolume]=useState(100),[error,setError]=useState(""),[entitlement,setEntitlement]=useState<Entitlement>(initialEntitlement);
 useEffect(()=>subscribeActiveLiveKitRoom(setRoom),[]);useEffect(()=>{fetch("/api/me/capabilities",{cache:"no-store"}).then(response=>response.ok?response.json():null).then(data=>{if(data?.screenShare)setEntitlement(data.screenShare)}).catch(()=>{})},[]);useEffect(()=>{if(!room){setShares([]);return}const sync=()=>setShares(snapshot(room)),onReconnecting=()=>{setReconnecting(true);sync()},onReconnected=()=>{setReconnecting(false);sync()};sync();room.on(RoomEvent.Connected,sync).on(RoomEvent.ParticipantConnected,sync).on(RoomEvent.ParticipantDisconnected,sync).on(RoomEvent.TrackPublished,sync).on(RoomEvent.TrackUnpublished,sync).on(RoomEvent.TrackSubscribed,sync).on(RoomEvent.TrackUnsubscribed,sync).on(RoomEvent.LocalTrackPublished,sync).on(RoomEvent.LocalTrackUnpublished,sync).on(RoomEvent.Reconnecting,onReconnecting).on(RoomEvent.Reconnected,onReconnected).on(RoomEvent.ConnectionStateChanged,sync).on(RoomEvent.Disconnected,sync);return()=>{room.off(RoomEvent.Connected,sync).off(RoomEvent.ParticipantConnected,sync).off(RoomEvent.ParticipantDisconnected,sync).off(RoomEvent.TrackPublished,sync).off(RoomEvent.TrackUnpublished,sync).off(RoomEvent.TrackSubscribed,sync).off(RoomEvent.TrackUnsubscribed,sync).off(RoomEvent.LocalTrackPublished,sync).off(RoomEvent.LocalTrackUnpublished,sync).off(RoomEvent.Reconnecting,onReconnecting).off(RoomEvent.Reconnected,onReconnected).off(RoomEvent.ConnectionStateChanged,sync).off(RoomEvent.Disconnected,sync)}},[room]);
 const localShare=shares.find(item=>item.local),remoteShares=shares.filter(item=>!item.local),viewer=shares.find(item=>item.ownerId===viewerId)??null,audioSupported=typeof navigator!=="undefined"&&Boolean(navigator.mediaDevices?.getDisplayMedia);
 useEffect(()=>{const mediaTrack=localShare?.track.mediaStreamTrack;if(!mediaTrack||!room)return;const ended=()=>{setShares(snapshot(room));void room.localParticipant.setScreenShareEnabled(false)};mediaTrack.addEventListener("ended",ended,{once:true});return()=>mediaTrack.removeEventListener("ended",ended)},[localShare?.track,room]);
 async function getServerEntitlement(){const response=await fetch("/api/me/capabilities",{cache:"no-store"});if(!response.ok)throw new Error("Não foi possível validar o plano da conta.");const data=await response.json() as {screenShare:Entitlement};setEntitlement(data.screenShare);return data.screenShare}
 async function start(){if(!room||room.state!==ConnectionState.Connected)return setError("Entre na voz antes de compartilhar a tela.");setBusy(true);setError("");try{const capability=await getServerEntitlement();await room.localParticipant.setScreenShareEnabled(true,{audio:true,video:{displaySurface:surface},resolution:{width:capability.maxWidth,height:capability.maxHeight,frameRate:capability.maxFps},contentHint:"motion",surfaceSwitching:"include",systemAudio:"include"});setPanel(false)}catch(cause){if((cause as DOMException)?.name!=="NotAllowedError")setError(cause instanceof Error?cause.message:"Não foi possível iniciar a transmissão.")}finally{setBusy(false)}}
 async function stop(){setBusy(true);try{await room?.localParticipant.setScreenShareEnabled(false)}finally{setBusy(false)}}
 return <section className="stream-card"><header><div><small>LIVEKIT STREAM</small><h2>Compartilhamento de tela</h2></div>{localShare?<span className="stream-live"><Radio size={12}/> {reconnecting?"RECONECTANDO":"LIVE"}</span>:null}</header>{localShare?<div className="stream-active"><b>{localShare.quality}</b><span>{Math.max(0,(room?.numParticipants||1)-1)} participante(s) na sala</span><div><button onClick={()=>setViewerId(localShare.ownerId)}><Expand size={14}/> Abrir tela</button><button onClick={stop} disabled={busy}><Square size={13}/> Parar</button></div></div>:<button className="stream-start" onClick={()=>setPanel(true)} disabled={!room||reconnecting}><MonitorUp size={16}/> Compartilhar tela</button>}{remoteShares.map(share=><button className="stream-available" key={share.ownerId} onClick={()=>setViewerId(share.ownerId)}><span><Radio size={12}/> {share.ownerName} está transmitindo</span><b>Abrir tela</b></button>)}{error?<p className="stream-error">{error}</p>:null}
 {panel?<div className="stream-modal-bg" role="dialog" aria-modal="true" aria-labelledby="share-title"><div className="stream-modal"><button className="modal-close" onClick={()=>setPanel(false)} aria-label="Fechar"><X/></button><small>PREPARAR TRANSMISSÃO</small><h2 id="share-title">O que você quer compartilhar?</h2><p>A escolha final sempre acontece no seletor seguro do navegador.</p><div className="source-grid">{[["monitor","Tela inteira"],["window","Janela"],["browser","Aba"]].map(([value,label])=><button className={surface===value?"selected":""} onClick={()=>setSurface(value as typeof surface)} key={value}><MonitorUp/>{label}</button>)}</div><div className="stream-capability"><Volume2 size={16}/>{audioSupported?"Áudio disponível quando oferecido e selecionado no navegador.":"Seu navegador não oferece áudio para esta captura."}</div><div className="quality-row"><span>Plano {entitlement.tier.toUpperCase()}</span><b>{entitlement.maxHeight}p · até {entitlement.maxFps} FPS</b></div><button className="auth-primary" onClick={start} disabled={busy}>{busy?<GrindLoading label="Preparando transmissão…"/>:"Abrir seletor do navegador"}</button></div></div>:null}
 {viewer?<div className="stream-viewer" role="dialog" aria-modal="true"><header><div><span>LIVE</span><b>{viewer.ownerName}</b><small>{viewer.local?"Prévia local":"Transmissão LiveKit"}</small></div><button onClick={()=>setViewerId(null)} aria-label="Fechar viewer"><X/></button></header><div className="stream-stage"><StreamVideo share={viewer} volume={volume}/></div><footer><span>{viewer.quality}</span><label><Volume2 size={14}/><input type="range" min="0" max="100" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label><button onClick={()=>document.querySelector<HTMLDivElement>(".stream-stage")?.requestFullscreen()}><Expand size={14}/> Fullscreen</button></footer></div>:null}</section>;
}
