"use client";
import {useEffect,useRef,useState} from "react";import {Expand,MonitorUp,Radio,Square,Volume2,X} from "lucide-react";import {ConnectionState,LocalVideoTrack,RemoteAudioTrack,RemoteVideoTrack,Room,RoomEvent,Track,type VideoTrack} from "livekit-client";import {subscribeActiveLiveKitRoom} from "@/lib/webrtc/useLobbyVoice";import GrindLoading from "@/components/feedback/GrindLoading";
type Share={ownerId:string;ownerName:string;track:VideoTrack;audioTrack:RemoteAudioTrack|null;local:boolean};
function snapshot(room:Room|null):Share[]{if(!room||room.state!==ConnectionState.Connected)return[];const shares:Share[]=[];const local=room.localParticipant.getTrackPublication(Track.Source.ScreenShare)?.track;if(local instanceof LocalVideoTrack)shares.push({ownerId:room.localParticipant.identity,ownerName:room.localParticipant.name||"Você",track:local,audioTrack:null,local:true});for(const participant of room.remoteParticipants.values()){const track=participant.getTrackPublication(Track.Source.ScreenShare)?.track,audio=participant.getTrackPublication(Track.Source.ScreenShareAudio)?.track;if(track instanceof RemoteVideoTrack)shares.push({ownerId:participant.identity,ownerName:participant.name||"Player",track,audioTrack:audio instanceof RemoteAudioTrack?audio:null,local:false})}return shares}
function StreamVideo({share,volume}:{share:Share;volume:number}){const videoRef=useRef<HTMLVideoElement>(null),audioRef=useRef<HTMLAudioElement>(null);useEffect(()=>{const element=videoRef.current;if(!element)return;share.track.attach(element);return()=>{share.track.detach(element)}},[share]);useEffect(()=>{const element=audioRef.current,track=share.audioTrack;if(!element||!track)return;track.attach(element);element.volume=volume/100;return()=>{track.detach(element)}},[share.audioTrack,volume]);return <><video ref={videoRef} autoPlay playsInline muted/><audio ref={audioRef} autoPlay/></>}
export default function ScreenShare({isPro=false}:{isPro?:boolean}){
 const [room,setRoom]=useState<Room|null>(null),[shares,setShares]=useState<Share[]>([]),[panel,setPanel]=useState(false),[viewer,setViewer]=useState<Share|null>(null),[busy,setBusy]=useState(false),[surface,setSurface]=useState<"monitor"|"window"|"browser">("monitor"),[volume,setVolume]=useState(100),[error,setError]=useState("");
 useEffect(()=>subscribeActiveLiveKitRoom(setRoom),[]);useEffect(()=>{if(!room){setShares([]);return}const sync=()=>setShares(snapshot(room));sync();room.on(RoomEvent.Connected,sync).on(RoomEvent.ParticipantConnected,sync).on(RoomEvent.ParticipantDisconnected,sync).on(RoomEvent.TrackPublished,sync).on(RoomEvent.TrackUnpublished,sync).on(RoomEvent.TrackSubscribed,sync).on(RoomEvent.TrackUnsubscribed,sync).on(RoomEvent.LocalTrackPublished,sync).on(RoomEvent.LocalTrackUnpublished,sync).on(RoomEvent.Disconnected,sync);return()=>{room.off(RoomEvent.Connected,sync).off(RoomEvent.ParticipantConnected,sync).off(RoomEvent.ParticipantDisconnected,sync).off(RoomEvent.TrackPublished,sync).off(RoomEvent.TrackUnpublished,sync).off(RoomEvent.TrackSubscribed,sync).off(RoomEvent.TrackUnsubscribed,sync).off(RoomEvent.LocalTrackPublished,sync).off(RoomEvent.LocalTrackUnpublished,sync).off(RoomEvent.Disconnected,sync)}},[room]);useEffect(()=>{if(viewer&&!shares.some(item=>item.ownerId===viewer.ownerId))setViewer(null)},[shares,viewer]);
 const localShare=shares.find(item=>item.local),remoteShares=shares.filter(item=>!item.local),audioSupported=typeof navigator!=="undefined"&&Boolean(navigator.mediaDevices?.getDisplayMedia);
 async function start(){if(!room||room.state!==ConnectionState.Connected)return setError("Entre na voz antes de compartilhar a tela.");setBusy(true);setError("");try{await room.localParticipant.setScreenShareEnabled(true,{audio:true,video:{displaySurface:surface},resolution:isPro?{width:1920,height:1080,frameRate:60}:{width:1280,height:720,frameRate:30},contentHint:"motion",surfaceSwitching:"include",systemAudio:"include"});setPanel(false)}catch(cause){if((cause as DOMException)?.name!=="NotAllowedError")setError("Não foi possível iniciar a transmissão.")}finally{setBusy(false)}}
 async function stop(){setBusy(true);try{await room?.localParticipant.setScreenShareEnabled(false)}finally{setBusy(false)}}
 return <section className="stream-card"><header><div><small>LIVEKIT STREAM</small><h2>Compartilhamento de tela</h2></div>{localShare?<span className="stream-live"><Radio size={12}/> LIVE</span>:null}</header>{localShare?<div className="stream-active"><b>{isPro?"1080p · até 60 FPS":"720p · até 30 FPS"}</b><span>{Math.max(0,(room?.numParticipants||1)-1)} participante(s) na sala</span><div><button onClick={()=>setViewer(localShare)}><Expand size={14}/> Abrir tela</button><button onClick={stop} disabled={busy}><Square size={13}/> Parar</button></div></div>:<button className="stream-start" onClick={()=>setPanel(true)} disabled={!room}><MonitorUp size={16}/> Compartilhar tela</button>}{remoteShares.map(share=><button className="stream-available" key={share.ownerId} onClick={()=>setViewer(share)}><span><Radio size={12}/> {share.ownerName} está transmitindo</span><b>Abrir tela</b></button>)}{error?<p className="stream-error">{error}</p>:null}
 {panel?<div className="stream-modal-bg" role="dialog" aria-modal="true" aria-labelledby="share-title"><div className="stream-modal"><button className="modal-close" onClick={()=>setPanel(false)} aria-label="Fechar"><X/></button><small>PREPARAR TRANSMISSÃO</small><h2 id="share-title">O que você quer compartilhar?</h2><p>A escolha final sempre acontece no seletor seguro do navegador.</p><div className="source-grid">{[["monitor","Tela inteira"],["window","Janela"],["browser","Aba"]].map(([value,label])=><button className={surface===value?"selected":""} onClick={()=>setSurface(value as typeof surface)} key={value}><MonitorUp/>{label}</button>)}</div><div className="stream-capability"><Volume2 size={16}/>{audioSupported?"Áudio do sistema disponível quando oferecido pelo navegador.":"Seu navegador não oferece áudio para esta captura."}</div><div className="quality-row"><span>Plano {isPro?"PRO":"FREE"}</span><b>{isPro?"1080p · até 60 FPS":"720p · até 30 FPS"}</b></div><button className="auth-primary" onClick={start} disabled={busy}>{busy?<GrindLoading label="Preparando transmissão…"/>:"Abrir seletor do navegador"}</button></div></div>:null}
 {viewer?<div className="stream-viewer" role="dialog" aria-modal="true"><header><div><span>LIVE</span><b>{viewer.ownerName}</b><small>{viewer.local?"Prévia local":"Transmissão LiveKit"}</small></div><button onClick={()=>setViewer(null)} aria-label="Fechar viewer"><X/></button></header><div className="stream-stage"><StreamVideo share={viewer} volume={volume}/></div><footer><span>{isPro?"Até 1080p60":"Até 720p30"}</span><label><Volume2 size={14}/><input type="range" min="0" max="100" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label><button onClick={()=>document.querySelector<HTMLDivElement>(".stream-stage")?.requestFullscreen()}><Expand size={14}/> Fullscreen</button></footer></div>:null}</section>;
}
