create table if not exists public.voice_signals (
  id bigint generated by default as identity primary key,
  lobby_id uuid not null references public.lobbies(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  target_id uuid references public.profiles(id) on delete cascade,
  signal_type text not null check (signal_type in ('offer','answer','ice-candidate','leave')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '2 minutes')
);

create index if not exists voice_signals_poll_idx
  on public.voice_signals(lobby_id, created_at);
create index if not exists voice_signals_expiry_idx
  on public.voice_signals(expires_at);

alter table public.voice_signals enable row level security;

drop policy if exists "active lobby members read voice signals" on public.voice_signals;
create policy "active lobby members read voice signals"
on public.voice_signals for select
to authenticated
using (
  exists (
    select 1 from public.lobby_members member
    where member.lobby_id = voice_signals.lobby_id
      and member.user_id = (select auth.uid())
      and member.last_seen_at > now() - interval '30 seconds'
  )
  and (target_id is null or target_id = (select auth.uid()) or sender_id = (select auth.uid()))
);

drop policy if exists "active lobby members create voice signals" on public.voice_signals;
create policy "active lobby members create voice signals"
on public.voice_signals for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1 from public.lobby_members member
    where member.lobby_id = voice_signals.lobby_id
      and member.user_id = (select auth.uid())
      and member.last_seen_at > now() - interval '30 seconds'
  )
);

drop policy if exists "signal senders delete own voice signals" on public.voice_signals;
create policy "signal senders delete own voice signals"
on public.voice_signals for delete
to authenticated
using (sender_id = (select auth.uid()));
