'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {Crown,Gamepad2,Loader2,Search,Shield,Signal,Users,UserPlus} from 'lucide-react';

type Member={user_id:string;profile:{id:string;username:string;display_name:string;avatar:string|null;status:string}|null};
type Squad={id:string;name:string;captain_id:string;region:string;members:Member[]};
type Summary={season:{id:string;name:string}|null;squad:Squad|null;rating:{rating:number;peak_rating:number;placements_played:number;wins:number;losses:number}|null;queue:{id:string;status:string;average_gr:number;region:string;created_at:string}|null;activeMatch:{id:string;code:string;state:string}|null};
function initials(v:string){return v.trim().slice(0,1).toUpperCase()||'G'}
export default function ValorantCompetitive({userId}:{userId:string}){
 const [data,setData]=useState<Summary|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');const [name,setName]=useState('Grind Squad'),[members,setMembers]=useState(['','','','']);
 const load=useCallback(async()=>{try{const r=await fetch('/api/competitive/valorant',{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error||'Falha ao carregar competitivo.');setData(b);setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar competitivo.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(timer)},[load]);
 async function createSquad(){setBusy(true);try{const r=await fetch('/api/competitive/valorant/squad',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,region:'BR-SAO',members})}),b=await r.json();if(!r.ok)throw new Error(b.error||'Falha ao criar squad.');await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao criar squad.')}finally{setBusy(false)}}
 async function queue(){setBusy(true);try{const r=await fetch('/api/competitive/valorant/queue',{method:'POST'}),b=await r.json();if(!r.ok)throw new Error(b.error||'Falha ao entrar na fila.');if(b.matchId)location.href=`/competitive/valorant/match/${b.matchId}`;else await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao entrar na fila.')}finally{setBusy(false)}}
 if(loading)return <div className="competitive-loading"><Loader2 className="animate-spin"/>Carregando GRIND VALORANT</div>;
 const rating=data?.rating??{rating:1000,peak_rating:1000,placements_played:0,wins:0,losses:0};const squad=data?.squad;
 return <div className="competitive-shell"><header className="competitive-top"><Link href="/">← Dashboard</Link><div className="competitive-logo">GRIND <span>VALORANT</span></div><div className="competitive-season">{data?.season?.name||'Temporada indisponível'}</div></header><main className="competitive-page">
  <section className="competitive-hero"><div><span className="competitive-kicker">MÓDULO COMPETITIVO</span><h1>VALORANT 5v5</h1><p>Squad fechado, matchmaking por GR, aceite 10/10, veto e salas privadas automáticas.</p></div><div className="competitive-rating"><span>VALORANT GR</span><b>{rating.rating}</b><small>Peak {rating.peak_rating} · Placements {rating.placements_played}/5</small></div></section>
  {error?<div className="competitive-error">{error}</div>:null}
  {data?.activeMatch?<section className="competitive-active-match"><div><Signal size={18}/><span><b>Partida em andamento</b><small>{data.activeMatch.code} · {data.activeMatch.state}</small></span></div><Link href={`/competitive/valorant/match/${data.activeMatch.id}`}>Voltar para a partida</Link></section>:null}
  {!squad?<section className="competitive-panel squad-create"><div className="competitive-section-title"><div><span className="competitive-kicker">SQUAD 5V5</span><h2>Monte seu squad competitivo</h2></div><Users size={24}/></div><label>Nome do squad<input value={name} maxLength={40} onChange={e=>setName(e.target.value)}/></label><div className="competitive-member-inputs">{members.map((value,index)=><label key={index}>Jogador {index+2}<div><UserPlus size={15}/><input value={value} onChange={e=>setMembers(current=>current.map((v,i)=>i===index?e.target.value:v))} placeholder="@username"/></div></label>)}</div><button disabled={busy||members.some(v=>v.trim().length<3)} onClick={createSquad} className="competitive-primary">{busy?<Loader2 size={16} className="animate-spin"/>:<Shield size={16}/>}Criar squad</button><p className="competitive-hint">Todos os cinco precisam estar online e livres de outro squad competitivo.</p></section>:<div className="competitive-grid"><section className="competitive-panel"><div className="competitive-section-title"><div><span className="competitive-kicker">SEU SQUAD</span><h2>{squad.name}</h2></div><span className="competitive-region">{squad.region}</span></div><div className="competitive-roster">{squad.members.map(member=><article key={member.user_id}><span className="competitive-avatar">{member.profile?.avatar?<img src={member.profile.avatar} alt=""/>:initials(member.profile?.display_name||member.profile?.username||'P')}</span><span><b>{member.profile?.display_name||member.profile?.username||'Player'}{member.user_id===squad.captain_id?<Crown size={13}/>:null}</b><small>@{member.profile?.username||'player'} · {member.profile?.status||'offline'}</small></span><i className={member.profile?.status==='online'?'online':''}/></article>)}</div></section><section className="competitive-panel queue-panel"><span className="competitive-kicker">MATCHMAKING</span><h2>{data?.queue?'Buscando adversário':'Pronto para buscar'}</h2><div className={`competitive-scanner ${data?.queue?'active':''}`}><span/><div><Search size={30}/></div></div>{data?.queue?<><p>Comparando região e rating do squad.</p><b>{data.queue.average_gr} GR médio</b><small>Fila iniciada {new Date(data.queue.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></>:<><p>O capitão inicia a fila quando os cinco estiverem prontos.</p><button disabled={busy||squad.captain_id!==userId||Boolean(data?.activeMatch)} onClick={queue} className="competitive-primary">{busy?<Loader2 size={16} className="animate-spin"/>:<Gamepad2 size={16}/>}BUSCAR PARTIDA</button></>}</section></div>}
 </main></div>;
}
